### ISSUE TITLE
Better instructions for getting an HDRI to work

### ISSUE THREAD

**Issue by thinsoldier** [f3d-app/f3d#1001]
**Is your feature request related to a problem? Please describe.**
I'm not smart enough to figure out how to get an the built in HDRI to be visible or to define a custom hdri file.

**Describe the solution you'd like**
Better instructions and config file example somewhere on the website.

The gallery has examples like: `Animated realistic rendering: f3d gearbox/scene.gltf --hdri-file=future_parking_2k.hdr --hdri-skybox --hdri-ambient -uqxtgas`

I don't see `future_parking_2k.hdr` anywhere in the install folder. If it is built into the program directly, I have not figured out how to properly refer to it in the config file `10_global.json`.
I have also tried adding absolute paths to hdr files to the config and that doesn't work either:
`    "hdri-file": "C:\\Users\\thinsoldier\\Desktop\\HDRIs\\HDRI-haven\\autumn_hockey_2k.hdr",`

**Comment by Meakk** [comment]
What is your f3d version? Currently, the documentation is not versioned, so it's constantly updated with the master branch (related issue #845).  
The options you specified are not yet available in version 2.1.  
You have three solutions:
- update to nightly (it's fairly stable)
- wait for 2.2 (early october)
- select 2.1 tag on github in read the md files (https://github.com/f3d-app/f3d/blob/v2.1.0/doc/user/OPTIONS.md)

**Comment by Meakk** [comment]
Regarding hdri files, you can download some here: https://polyhaven.com/hdris

The files used in the gallery can be found here:
https://drive.google.com/file/d/1iRh0OeJjMjjaBDLG6b_iJSkC_Jt_YQuo/view?usp=sharing

**Comment by mwestphal** [comment]
And to be complete, there is no default HDRI in version <= 2.1.0 and the command line to load an hdri is:

`f3d --hdri=C:\path\to\hdri.hdr`

The name of the option in the config file is also just `hdri`.

**Comment by mwestphal** [comment]
And finally, the gallery contains a link to download all the data to reproduce everything, which contains futur parking :)
