### ISSUE TITLE
Lighting issue when showing edges on a textured .gltf

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1008]
**Describe the bug**

Lighting is wrong when showing edges of a textured .gltf

`f3d -e file.gltf`

![a](https://github.com/f3d-app/f3d/assets/3129530/b00d3921-ea7b-4fb2-8a01-118e97419d46)

![a](https://github.com/f3d-app/f3d/assets/3129530/449ac71f-e6f5-4088-b040-9d3f41b8a812)

![a](https://github.com/f3d-app/f3d/assets/3129530/1a3305e9-71e1-409a-af1b-c9c9be7b3090)

No problem with a non-textured gltf:

![a](https://github.com/f3d-app/f3d/assets/3129530/e7e17b77-7ea8-411a-bf00-7059201440ef)

Nor with a textured obj or fbx:

![a](https://github.com/f3d-app/f3d/assets/3129530/7c85d11d-f0da-451c-a76c-955d5ebce658)

![a](https://github.com/f3d-app/f3d/assets/3129530/c38bb283-8fde-42f2-b6a5-e74bdace5d15)

**Comment by mwestphal** [comment]
Regression between 2.0 and 2.1, should be bisected

**Comment by Meakk** [comment]
Looks related to the PBR shader. Should not be too hard to fix. Do you want me to take a look before the final release?

**Comment by mwestphal** [comment]
That can wait 2.3 tbh, nobody found it in the last three months.

**Comment by Meakk** [comment]
VTK fix: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10705
