### ISSUE TITLE
On Windows, F3D is very laggy when resizing the window IF the cheatsheet is shown

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1013]
**Describe the bug**
On Windows, F3D is very laggy when resizing the window IF the cheatsheet is shown

**To Reproduce**
 1. Open the file using `f3d --dry-run example.glb`
 2. Press `H` to show cheatsheet
 3. Resize window using the edge of the window
 4. Very laggy
 
**Expected behavior**
Showing the cheatsheet should not impact the performance of F3D during resize

**System Information:**
 - OS: Windows

**Comment by Meakk** [comment]
Just tried, cannot see any difference with or without the cheatsheet.

**Comment by Meakk** [comment]
Actually, I reproduce. It happens when the font inside the cheatsheet (or the metadata) window is changed because of the resizing.

**Comment by mwestphal** [comment]
Then it should happen with the filename too ?

**Comment by jspanchu** [comment]
@mwestphal I'm noticing this even on macOS. When the cheatsheet is shown, resizing is slow. Also, toggling any feature also takes time. Ex: try turning on/off the grid or increase light intensity. With the cheatsheet, it takes about 1-2 seconds for the feature to actually get toggled. Maybe something unintendedly introduces a delay in the interactor event processing loop?

**Comment by mwestphal** [comment]
Sounds like a different issue ?

**Comment by mwestphal** [comment]
I've seen similar things on Linux as well. Lets loop back on it once we have #1077

**Comment by mwestphal** [comment]
I confirm this is fixed on Linux, @Meakk I suppose this is fixed on Windows too ?

**Comment by Meakk** [comment]
Fixed on Windows
