### ISSUE TITLE
No information for the user when an option is invalid on Windows

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1015]
**Describe the bug**
When an invalid option is specified in the command line, F3D opens and close immediately without any information to the user

**To Reproduce**
 1. `f3d c:\path\to\file.vtp --invalid-option`
 2. F3D opens and close immediately

**Expected behavior**
We should have the blocking modal window asking to click OK to close the window.

**System Information:**
 - OS: Windows

**F3D Information**
2.2 RC2

**Comment by mwestphal** [comment]
this one I fixed during 2.1.0 release, unexpected
