### ISSUE TITLE
Opening an invalid file does not remove the previous one

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1017]
**Describe the bug**
Opening an invalid file does not remove the previous one when navigating in multi-file mode after having opened a valid file

**To Reproduce**
 1. Open the test folder using `f3d --dry-run f3d\testing\data`
 2. Press right until you hit an invalid file
 3. The previous file stays opened

![image](https://github.com/f3d-app/f3d/assets/6069752/c422aa7c-ed58-41dd-9cfa-8af1a073bfe1)

**Expected behavior**
The previous actor should be removed.

**System Information:**
 - OS: Windows

**F3D Information**
2.2 RC2

**Comment by mwestphal** [comment]
I remember fixing that and even adding a test for it.

**Comment by mwestphal** [comment]
I reproduce
