### ISSUE TITLE
It cant play Mixamo FBX

### ISSUE THREAD

**Issue by gerroon** [f3d-app/f3d#1033]
Load the fbx and press space to paly the animation.

![image](https://github.com/f3d-app/f3d/assets/8519469/b61407b9-c0c6-473c-a2d2-7e4df3279a98)

[Sword And Shield Attack (3).zip](https://github.com/f3d-app/f3d/files/12787016/Sword.And.Shield.Attack.3.zip)

**Comment by mwestphal** [comment]
duplicate of https://github.com/f3d-app/f3d/issues/414

Caused by assimp, you can use .gltf format instead of .fbx to work around the issue.
