### ISSUE TITLE
Non standard paths are not correctly supported when inside quotes

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1042]
**Describe the bug**
Opening a file with a non standard path (eg network or based on ~/) is not working

**To Reproduce**
 1. Open the file using `f3d --dry-run "~/example.glb"`
 2. fails to open

`File "/home/glow/dev/f3d/f3d/build/~/example.glb" does not exist`

This matters especially when using the libf3d.

**Comment by mwestphal** [comment]
closed in favor of #1044

**Comment by mwestphal** [comment]
Actually a different issue

**Comment by mqudsi** [comment]
Speaking as a shell developer, I don’t think regular apps are intended to understand shell syntax like ~ or $HOME. The paths shouldn’t be passed in escaped or single quoted to the app to begin with. I don’t think this is a bug.

**Comment by mwestphal** [comment]
Looks like you are absolutely right: https://stackoverflow.com/questions/998626/meaning-of-tilde-in-linux-bash-not-home-directory

Thanks for your input!

Closing this.
