### ISSUE TITLE
supress error window. 

### ISSUE THREAD

**Issue by spiraloid** [f3d-app/f3d#1060]
**Is your feature request related to a problem? Please describe.**
 when searching through folders, it keeps popping open for unknown file types. "unable to open foo.mtl"  unable to open foo.zip etc
 
**Describe the solution you'd like**
supress error dialog option for config

**Describe alternatives you've considered**
moving all my glb files into a folder on their own just to browse them.

**Additional context**

**Contribution**
Please tell us if you are able to contribute (Can you develop this new feature?)
Don't worry, you can still post a feature request if you cannot contribute!*

**Comment by Meakk** [comment]
Do you have the issue on the latest version?

**Comment by mwestphal** [comment]
@Meakk : Thinking about it we should just add `quiet` to the thumbnail conf.

**Comment by Meakk** [comment]
> @Meakk : Thinking about it we should just add `quiet` to the thumbnail conf.

Or just force it. I see no reason to output anything

**Comment by mwestphal** [comment]
wdym force it ?

**Comment by mwestphal** [comment]
Ha, write it directly in the line invoking F3D ? Lets not do that :)
