### ISSUE TITLE
A specific model disapear when using 4k HDRI with it

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#109]
**Describe the bug**
Nothing appears when showing a specific fbx model with any 4K HDRI, but no issues with 2K HDRI

![a](https://user-images.githubusercontent.com/3129530/144751354-2d50194c-9814-4f7e-85d6-7eda8d8fb29d.png)

**To Reproduce**
 0. https://sketchfab.com/3d-models/zelda-breath-of-the-wild-bf99374334a64291ae2876c83269adb6#download
 1. https://polyhaven.com/a/hikers_cave, 2K and 4k
 1. Open the file using `f3d zeldaPosed001.fbx --hdri=~/Downloads/hikers_cave_4k.hdr`
 2. Model does not appear
 3. Open the file using `f3d zeldaPosed001.fbx --hdri=~/Downloads/hikers_cave_2k.hdr`
 4. model appears
 5. note: **using --output works around the issue**

**Expected behavior**
Model appears

![a](https://user-images.githubusercontent.com/3129530/144751269-3b0d7e8f-acff-4f3b-a2d0-8d6bf16093d6.png)

**System Information:**
 - OS: ArchLinux
 - GPU and GPU driver: intel chipset

**F3D Information**
Paste the content of `f3d --version`:

```
[glow@violet ~/Downloads/models/zelda/source]$ ~/Downloads/f3d-1.2.0-Linux/bin/f3d zeldaPosed001.fbx --version                                           
f3d 1.2.0

F3D - A fast and minimalist 3D viewer
Version: 1.2.0
Build date: 2021-12-04 19:23:10
System: Linux-5.11.0-1021-azure x86_64
Compiler: GNU 7.5.0
RayTracing module: OFF
Exodus module: ON
OpenCASCADE module: 7.6.0 (no metadata)
Assimp module: 5.1.0
VTK version: 9.1.20211124 (build 20211124)

Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
Written by Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

**Additional context**

**Comment by Meakk** [comment]
Works fine on my side, even with 8k and 16k HDRIs on a RTX 3070. What's your GPU?

**Comment by mwestphal** [comment]
Unable to reproduce anymore here either, closing
