### ISSUE TITLE
Add support for ortographic projection

### ISSUE THREAD

**Issue by mrdeveloperdude** [f3d-app/f3d#1096]
As a user of f3d I would like to see support for [orthographic projection](https://en.wikipedia.org/wiki/Orthographic_projection).

Currently only perspective projection is supported. My use case is that I will render thumbnails of CAD models and it is customary to use orthographic projection in CAD.

It can possibly be faked by moving the camera far away and setting a low camera angle. Possible pitfalls of this hack is floating point precision problems, poor z-buffer dynamic range use and more.

**Comment by mwestphal** [comment]
Indeed a nice addition, shouldnt be too hard to add.

**Comment by Meakk** [comment]
For reference if someone wants to give it a try: https://vtk.org/doc/nightly/html/classvtkCamera.html#a87b276a44eb1817aa388c89dc9becfc5

Obviously we need an option to toggle it.

**Comment by aemreaydin** [comment]
I'd like to work on this as my first issue. I'm trying to write a simple Vulkan Engine as a hobby project and would love to work on f3d as well to learn more about graphics systems going forward!

**Comment by mwestphal** [comment]
Hi @aemreaydin !

You are very welcome! We have been discussing this issue on discord, did you join already ?

https://discord.f3d.app

**Comment by Meakk** [comment]
There's a draft by @lknknm done here #942 if you want to take over.

**Comment by mwestphal** [comment]
@kidharb so do you wanna try your hand at this one ?

**Comment by kidharb** [comment]
Yes, I'm just not sure regarding how the baselines work. So I've been trying to run the ctests locally which has led me down a path of learning cmake.
Should I just push the code, which is just aemreaydin code?

**Comment by mwestphal** [comment]
As you prefer, let me know if you need any help understanding how it works.

**Comment by mwestphal** [comment]
Still need a command line option, are you will to add it @kidharb ?

**Comment by mwestphal** [comment]
Fixed by #1315
