### ISSUE TITLE
Implementing a `f3d::image` save to memory API

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1104]
Saving to memory instead of a file could be useful.  
One example that comes to mind is embedding a `f3d.image` object to a notebook with Python.
See discussion on Discord: https://discord.com/channels/1046005690809978911/1186239207535026186/1186244784990461962

**Comment by mwestphal** [comment]
Could you had a bit more detail ? What does saving to memory means ?

**Comment by Meakk** [comment]
Saving to a file buffer instead of on disk.  
See https://vtk.org/doc/nightly/html/classvtkPNGWriter.html#a86f76b82b1c03bd60d14732072f3e3f0

**Comment by snoyer** [comment]
Currently we'd use the Python Imaging Library package to convert an `f3d.Image` (extract raw bitmap bytes and vertically flip the pixels) and save it to PNG format into a buffer:

```py
    def f3d_image_repr_png(f3d_img: f3d.Image) -> bytes:
        buf = BytesIO()
        f3d_to_pil(f3d_img).save(buf, format="png")
        buf.seek(0)
        return buf.getvalue()

    def f3d_to_pil(img: f3d.Image) -> Image.Image:
        size = img.width, img.height
        depth = img.channel_count
        im = Image.frombytes("RGB" if depth == 3 else "RGBA", size, img.content)
        return ImageOps.flip(im)
```

However VTK already knows how to do all that so we could skip the `PIL` dependency
