### ISSUE TITLE
Regarding F3D in Dart/Flutter

### ISSUE THREAD

**Issue by MostFull** [f3d-app/f3d#1107]
Welcome
I don't have a problem, but I have an important question
Can I use F3D in Dart and Flutter?
If he does not accept it, do you advise me on another alternative?

**Comment by Meakk** [comment]
It's possible to build libf3d as a native library on Android, I'd say it should be possible to use it with Flutter but we aren't really mobile developers.
We are interested in porting F3D on Android though and we already have a prototype working using JNI bindings.

**Comment by mwestphal** [comment]
By the way @MostFull , do not hesitate to ask on discord for such questions: https://discord.f3d.app :)

For reference, here is the issue for the android app: #27

Closing this

**Comment by mwestphal** [comment]
And if you would like to try out the JNI binding in your context, please let us know the results!
