### ISSUE TITLE
Add 3MF support using assimp plugin

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1126]
Assimp library support 3MF format, lets add support for it

Related to: #38 

Testing with #1123 , I tested the (single!) data from https://github.com/assimp/assimp and the data from https://github.com/3MFConsortium/3mf-samples/tree/master/examples

It looks like:

 - Texture seems non fonctionnal with the "core" datasets. It looks like the texture logic is a bit different that what we expect.
 - Many more complex files from "material" and "production" datasets are crashing.
 - Datasets from the "beam lattice" are outputting empty output
 - Datasets from the "slices" folder seems to be crashing for allocation size reason

More work needed before merging anything

**Comment by Meakk** [comment]
Thanks for investigating. Do you know if the crashes are coming from assimp or f3d?

**Comment by mwestphal** [comment]
crashes are coming from F3D most of the time. I would say the resulting data is not how F3D is expecting it.

**Comment by jtlechem** [comment]
Will 3MF support include the ability to obtain part volume and bounding box?

**Comment by mwestphal** [comment]
> Will 3MF support include the ability to obtain part volume and bounding box?

I'm not sure what that means.

**Comment by mwestphal** [comment]
https://github.com/f3d-app/f3d/pull/1138

**Comment by jtlechem** [comment]
> > Will 3MF support include the ability to obtain part volume and bounding box?
> 
> I'm not sure what that means.

I see your comment pointing to issue #1138. Perhaps I should have asked my question there. 
But I'll try to explain what I mean. When I open my .3mf part in f3d, will the app tell me the volume of the part? I'm also interested in the 3d bounding box of the part - the largest x, y, and z dimensions of the part relative to the base frame. See image.
![image](https://github.com/f3d-app/f3d/assets/72457304/65e97e90-a56d-4c55-a367-194253ac285d)

**Comment by Meakk** [comment]
@jtlechem can you share your file?

**Comment by jtlechem** [comment]
The image I shared is a random image from a google search to illustrate what I mean by 'bounding box'. I haven't downloaded f3d to try .3mf files yet, but I just wondered if these functionalities exist before I download it. 

Here is a better illustration. Here you can see the object volume and the x, y, and z dimensions of the object relative to the ground coordinate frame shown in the bottom left. Note the volume is that of the object, not the volume of the bounding box.
![image](https://github.com/f3d-app/f3d/assets/72457304/e8418b3f-202d-4118-a3ab-7294d23acfe6)
![image](https://github.com/f3d-app/f3d/assets/72457304/177256d8-c833-4947-85d2-49a423c6d889)

These are my own screenshots from PrusaSlicer, but I'm looking for a fast minimalist 3d viewer (like f3d) where I can rotate the object then get this information from the command line.
(also, I can't upload a .3mf file, it's not supported by github)

**Comment by Meakk** [comment]
You can zip the file before sending it on github.  
Regarding the bounding box with f3d, it's printed in the console, but there's no feature to visualize it (yet).

**Comment by mwestphal** [comment]
> but there's no feature to visualize it (yet).

Interesting idea, create an issue for it maybe ? :)

**Comment by mwestphal** [comment]
Available in the nightly release https://github.com/f3d-app/f3d/releases/tag/nightly
