### ISSUE TITLE
Is it possible to set colors of models more extensible? 

### ISSUE THREAD

**Issue by nikl234** [f3d-app/f3d#1132]
What i imagine is setting a second color which is used for the dark tones. 
So instead of creating color -> black gradient on the model it would be more like color1 -> color2 gradient. 

This is useful if you want to create thumbnails which are fitting into your desktop styling or even webpage.

Example (Here its from green -> blue):
![image](https://github.com/f3d-app/f3d/assets/15277321/7bf3c4c6-9a2b-4f07-a868-659e7ecff861)

**Comment by mwestphal** [comment]
Please share your data or at least share your data format.

Such questions are more adapted for our discord: https://discord.f3d.app

**Comment by Meakk** [comment]
It should be possible to achieve such effect by using a HDRI file with the dark color tone.

**Comment by mwestphal** [comment]
hi @nikl234 any news ? Did you try with an HDRI ?

**Comment by nikl234** [comment]
I never worked with HDRI files and i have university stress rn. 
Thats why i didnt started yet.

**Comment by mwestphal** [comment]
Waiting on your feedback @nikl234

**Comment by mwestphal** [comment]
with no feedback or clarification from @nikl234 , closing this.
