### ISSUE TITLE
Build of the Python extension fails: Expression did not evaluate to a known generator expression

### ISSUE THREAD

**Issue by yurivict** [f3d-app/f3d#1149]
**Describe the bug**
```
-- Configuring done (21.9s)
CMake Error at CMakeLists.txt:58 (file):
  Error evaluating generator expression:

    $<:/$<CONFIG>>

  Expression did not evaluate to a known generator expression


CMake Error at CMakeLists.txt:58 (file):
  Error evaluating generator expression:

    $<:/$<CONFIG>>

  Expression did not evaluate to a known generator expression


CMake Error:
  Error evaluating generator expression:

    $<:/$<CONFIG>>

  Expression did not evaluate to a known generator expression


CMake Error at CMakeLists.txt:58 (file):
  Error evaluating generator expression:

    $<:/$<CONFIG>>

  Expression did not evaluate to a known generator expression


CMake Error at CMakeLists.txt:58 (file):
  Error evaluating generator expression:

    $<:/$<CONFIG>>

  Expression did not evaluate to a known generator expression


-- Generating done (0.0s)
```

**To Reproduce**

cmake -DFREEBSD_PYTHON_VER=3.9  -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -I/usr/local/include/f3d -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -I/usr/local/include/f3d -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -I/usr/local/include/f3d -isystem /usr/local/include  -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -GNinja -DPython_ADDITIONAL_VERSIONS=3.9 -DPython_EXECUTABLE:FILEPATH="/usr/local/bin/python3.9" -DPython3_EXECUTABLE:FILEPATH="/usr/local/bin/python3.9" -DBOOST_PYTHON_SUFFIX:STRING=39 .

**Expected behavior**
n/a

**System Information:**
 - OS: FreeBSD 14.0

**F3D Information**
Paste the content of `f3d --version`: 2.2.1

cmake-core-3.27.9

**Comment by yurivict** [comment]
Adding ```-DF3D_MULTI_CONFIG_GENERATOR:BOOL=OFF``` didn't fix the problem for me for some reason.

**Comment by Meakk** [comment]
> Adding `-DF3D_MULTI_CONFIG_GENERATOR:BOOL=OFF` didn't fix the problem for me for some reason.

That's surprising 🤔 
  
Can you try to change line 24 from
```cmake
set(f3d_module_dir "${CMAKE_BINARY_DIR}$<${F3D_MULTI_CONFIG_GENERATOR}:/$<CONFIG>>/${f3d_python_package_name}")
```
to 
```cmake
set(f3d_module_dir "${CMAKE_BINARY_DIR}/${f3d_python_package_name}")
```

Let me know if it's working.

**Comment by yurivict** [comment]
This replacement fixed the problem.

**Comment by Meakk** [comment]
Great. I'll fix this issue in the upcoming release.

**Comment by Meakk** [comment]
The fix is done and will be merged soon (https://github.com/f3d-app/f3d/pull/1150). There are more changes to make in the CMake file in case you want to patch it.  
Please note we are currently in a release phase and the 2.3 version will be out very soon with this fix included.
