### ISSUE TITLE
USD file causes shader failure

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1167]
A specific USD file causes a shader failure with F3D 2.3.0-RC1

[pancakes.usdz](https://developer.apple.com/augmented-reality/quick-look/models/pancakes/pancakes.usdz)

[out.txt](https://github.com/f3d-app/f3d/files/13922295/out.txt)

**Comment by Meakk** [comment]
Working on my branch [#usd](https://github.com/f3d-app/f3d/pull/1169)

![pancake](https://github.com/f3d-app/f3d/assets/6069752/83895d93-7cf3-46d5-9e50-56d8161dba8a)

**Comment by mwestphal** [comment]
Fixed for pancakes.usdz, not fixed for https://github.com/mwestphal/assets/tree/main/full_assets/CarbonFrameBike

**Comment by mwestphal** [comment]
And another shader failure: https://github.com/mwestphal/assets/tree/main/full_assets/McUsd

**Comment by mwestphal** [comment]
And another one: https://github.com/mwestphal/assets/tree/main/test_assets/USDZ/DamagedHelmet

**Comment by Meakk** [comment]
Fixed

![damaged](https://github.com/f3d-app/f3d/assets/6069752/695f75b2-ddf9-4e16-a17f-7cb8dd761ee0)

**Comment by mwestphal** [comment]
Confirmed fixed
