### ISSUE TITLE
Weird display of dxf file

### ISSUE THREAD

**Issue by jubalh** [f3d-app/f3d#1171]
**Describe the bug**
Someone created a file in Freecad and sent me the dxf.
f3d displays it this way:
![test1](https://github.com/f3d-app/f3d/assets/1658215/ec0346aa-4128-4bce-bc0a-0735cd7843e9)

They also sent me an svg of what it should look like:
![test2](https://github.com/f3d-app/f3d/assets/1658215/46b782d0-5496-4a6a-bd24-40cef697cf4a)

**To Reproduce**
* Open the file in f3d
* 
**Expected behavior**
Display similar to the provided svg.

**System Information:**
 - OS: openSUSE Tumbleweed
 - GPU and GPU driver: NVIDIAf

**F3D Information**
F3D - A fast and minimalist 3D viewer
Version: 2.2.1.
Build date: 2024-01-10 00:00:00.
Build system: Linux 64-bits.
Compiler: GNU 13.2.1.
External rendering module: OFF.
Raytracing module: OFF.
VTK version: 9.3.0.
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2023 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Additional context**
This is the file in question. I uploaded it with the `.txt` ending because tgz and dxf were not allowed.

[Test1.dxf.txt](https://github.com/f3d-app/f3d/files/13928202/Test1.dxf.txt)

**Comment by Meakk** [comment]
We do not support curves yet, only polylines. See #1127
