### ISSUE TITLE
USD: Texture not working for a specific file

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1182]
**Describe the bug**
Texture are not showing up for a specific file: https://developer.apple.com/augmented-reality/quick-look/models/toycar/toy_car.usdz

**To Reproduce**
f3d:
![a](https://github.com/f3d-app/f3d/assets/3129530/0a39febf-6a11-4d34-abae-aaf65c0b46dd)

**Expected behavior**
blender:

![a](https://github.com/f3d-app/f3d/assets/3129530/9ecc8703-126c-4b46-b7bc-e9711be7dacc)

No warnings in terminal

**Comment by Meakk** [comment]
The material is bound on mesh subset, that's the first time I'm seeing that. Here's how it looks like with materials in f3d:

![car](https://github.com/f3d-app/f3d/assets/6069752/1e950d8a-3d95-43c7-9bc4-05aa5c5d8d08)

**Comment by mwestphal** [comment]
perfect

**Comment by mwestphal** [comment]
confirmed fixed.
