### ISSUE TITLE
Please add the configuration summary section

### ISSUE THREAD

**Issue by yurivict** [f3d-app/f3d#1216]
**Context**
F3D has many CMake options, that can be turned on or off. It would help packagers to provide a summary at the end of the configuration so that they can easily discover new options and make sure none were forgotten.

**Suggested implementation**
Add a dedicated CMake code in the main CMakeLists.txt that provide a summary of the options enabled and the optional dependency, their location as well as their versions.

**Skills needed**
- knowing CMake is a plus

**Notes**

Original Issue:

Since you support many formats and options it would be good to tell the user what options are and aren't enabled at the end of the configure screen.

**Comment by mwestphal** [comment]
Very good point @yurivict , I will edit the issue to give more info.
