### ISSUE TITLE
`animation-time=0` does not work when time range is not starting at 0

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1222]
**Describe the bug**
animation-time=0 does not work when time range is not starting at 0

**To Reproduce**
 1. Open this file [testTime2.e.zip](https://github.com/f3d-app/f3d/files/14064866/testTime2.e.zip)  using `f3d --dry-run --animation-time=0 testTime2.e`
 2. Incorrect timestep is rendered
 
![dev](https://github.com/f3d-app/f3d/assets/3129530/bd902a92-168d-45ab-8902-a6d301319c57)

**Expected behavior**
Correct timestep is loaded

**Suggested fix**
In `loader_impl.cxx` check for `animationTime != TimeRange[0]` instead of `animationTime != 0`

Add a test using a new dateset with a time range [0] < 0

**Comment by z-shaffer** [comment]
Handling it
