### ISSUE TITLE
F3D does not error out when specifying non-existent path on --interaction-test-record

### ISSUE THREAD

**Issue by 0x006E** [f3d-app/f3d#1231]
**Describe the bug**
Opening f3d with --interaction-test-record and giving it a path which is a non-existing directory bugs out the program. Escape does not work and the killing the process with Ctrl + C does not generate the log file. Other toggles seems to work correctly

**To Reproduce**
 1. Open the file using `f3d example.glb --interactive-test-record path/does/not/exist/abc.log`
 2. Try closing the program using Escape

**Expected behavior**
Print an error stating that the path does not exist and exit

**System Information:**
 - OS: Gentoo Linux
 - GPU and GPU driver: Intel Corporation Alder Lake-P Integrated Graphics Controller, i915

**F3D Information**
F3D 2.2.1

F3D - A fast and minimalist 3D viewer
Version: 2.2.1-55-g77596024.
Build date: 2024-01-23 03:42:40.
Build system: Linux 64-bits.
Compiler: GNU 13.2.1.
External rendering module: OFF.
Raytracing module: OFF.
VTK version: 9.3.0.
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2023 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Additional context**
The attached video shows this behaviour when specifying an non-existent path

https://github.com/f3d-app/f3d/assets/14817339/00466046-2219-4015-be61-ccdca2fb359d

**Comment by mwestphal** [comment]
I confirm the issue, although there is an error in the terminal when using `--verbose`:

```
ERROR: In vtkInteractorEventRecorder.cxx, line 130
vtkF3DInteractorEventRecorder (0x64dc8559bbe0): Unable to open file: /home/glow/dev/f3d/f3d/build/path/does/not/exist/abc.log
```

However we should display the error at F3D level, not VTK level (and even without verbose) and support exiting anyway.

**Comment by chirag-droid** [comment]
Can I take this issue

**Comment by mwestphal** [comment]
Go for it :)
