### ISSUE TITLE
MacOS (Silicon) F3D-2.3.0-macOS-arm64.dmg not launching with error "“F3D-2.3.0.app” is damaged and can’t be opened. You should move it to the Trash."

### ISSUE THREAD

**Issue by mediumlabspax** [f3d-app/f3d#1237]
**Describe the bug**
A clear and concise description of what the bug is, a screenshot helps a lot.

**To Reproduce**
 1. Open the file using `f3d --dry-run example.glb`
 2. step 2
 3. step 3

**Expected behavior**

**System Information:**
 - OS:
 - GPU and GPU driver:

**F3D Information**
Paste the content of `f3d --version`:

**Additional context**

**Comment by mwestphal** [comment]
https://f3d.app/doc/user/LIMITATIONS_AND_TROUBLESHOOTING.html#macos

**Comment by mediumlabspax** [comment]
Great, thanks for the fast response!
