### ISSUE TITLE
Need help testing Flatpak package.

### ISSUE THREAD

**Issue by kevinsmia1939** [f3d-app/f3d#124]
I recently create PR to update F3D to 1.2.0.
For unknown reason, I could not get any model to display.

https://github.com/flathub/com.kitware.F3D/pull/33

To install it, first install flatpak.

Ubuntu
`sudo apt install flatpak`
openSUSE
`sudo zypper in flatpak`

To install F3D from the PR.
`flatpak install --user https://dl.flathub.org/build-repo/67847/com.kitware.F3D.flatpakref`

To run it.
- Click the F3D icon on the menu.
- Use command `flatpak run com.kitware.F3D`

Thanks.

**Comment by mwestphal** [comment]
Working flawlesly here:
![a](https://user-images.githubusercontent.com/3129530/145476323-4e63ab5b-5aad-49d8-a856-e09187840b1e.png)

**Comment by kevinsmia1939** [comment]
Alright thanks for the help.

**Comment by kevinsmia1939** [comment]
> btw the org name of F3D has changed, it should be f3d-app ideally.

Hmm, I will look into it, probably can be done by resubmitting it as a new app and delete the old one.

**Comment by kevinsmia1939** [comment]
> btw the org name of F3D has changed, it should be f3d-app ideally.

I will depreciate the current app and submit it again with the new name.

**Comment by mwestphal** [comment]
> Would you prefer com.kitware.f3d-app

shoudl be com.f3d-app.f3d, but if it is simpler to not change it, its fine.

**Comment by hfiguiere** [comment]
`com.f3d-app.f3d` isn't valid. It should be `com.f3d_app.f3d` as this is also used for D-Bus permission, etc.

See https://docs.flatpak.org/en/latest/conventions.html#application-ids

**Comment by hfiguiere** [comment]
btw `f3d-app.com` doesn't resolve. So it break requirement of being a "domain" under your control.

**Comment by Meakk** [comment]
So according to the doc, it should be `io.github.f3d_app.f3d` right @hfiguiere ?

**Comment by hfiguiere** [comment]
yes
