### ISSUE TITLE
Shallow clipping on flat models

### ISSUE THREAD

**Issue by snoyer** [f3d-app/f3d#1247]
**Describe the bug**
when viewing a "flat" mesh, eg. with small z values compared to x or y the clipping is quite shallow in the z direction and it cuts the grid

**To Reproduce**
1.  open a "flat" mesh, eg. with small z values compared to x or y 
2.  observe the clipping is quite shallow in the z direction and it cuts the grid

**Expected behavior**
the clipping is not quite shallow in the z direction and does not cut the grid

**F3D Information**
```Version: 2.3.0-RC5.
Build date: 2024-01-21 14:18:24.
Build system: Linux 64-bits.
Compiler: GNU 8.4.0.
External rendering module: ON.
Raytracing module: ON.
VTK version: 9.3.0-1702-geb008dfe7b (date: 20240111).
```

**Additional context**
- [screen cast of the problem](https://github.com/f3d-app/f3d/assets/489715/e963f5a1-0b1e-440a-8a13-8b04d8070e4b)
- [zipped `.glb` file to reproduce](https://github.com/f3d-app/f3d/files/14114069/flat.glb.zip)

**Comment by Meakk** [comment]
Related code: https://github.com/f3d-app/f3d/blob/b7e8fc8edaaf146a8dc28ace999ef30a21d56258/library/VTKExtensions/Rendering/vtkF3DOpenGLGridMapper.cxx#L213
