### ISSUE TITLE
Provide multiple colormaps

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1257]
**Is your feature request related to a problem? Please describe.**
F3D already provide a default colormap named "inferno".
It is also possible to set a colormap manually.
It would be beneficial to provide a few colormap preset.

First, because "inferno" is just one and its good to have alternatives.
Second because it would open to have colorblind dedicated colormaps.

**Describe the solution you'd like**
 - Add a `colormap-preset` option
 - Add a few colormaps from https://sciviscolor.org/colormaps/

**Additional context**
 - Discussion about colorblind mode here: #1239 
 - Discussion about colormaps in ParaVIew: https://discourse.paraview.org/t/replacement-default-color-map-and-background-palette/12712

**Comment by Meakk** [comment]
Also, colormaps details in ParaView can be found here: https://gitlab.kitware.com/paraview/paraview/-/blob/master/Remoting/Views/ColorMaps.json

On my side, instead of a new option `colormap-preset`, I think we should extend the current option to accept preset strings (if possible).

**Comment by mwestphal** [comment]
done in #1309
