### ISSUE TITLE
Improve animation documentation

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1258]
**Context**
F3D doc has a short paragraph about animation: https://f3d.app/doc/user/USAGE.html#animations
While informative, it doesn't convey the full complexity of interacting with animation in F3D and animations in 3D formats in general.

Let's expand this doc in its own page

**Suggested solution**
 - Add a dedicated markdown file to cover how are animations defined in 3D models and how to interact with them in F3D
 - Move the short paragraph there as well
 - Add links wherever needed
 
**Skills**
 - Markdown

**Comment by mwestphal** [comment]
discussed here initially: #1242

**Comment by mwestphal** [comment]
@kathleenhang wanna take this one ?

**Comment by kathleenhang** [comment]
> @kathleenhang wanna take this one ?

Hi Mathieu, sure thing! Let me know if there are any best practices I should know about for writing F3D documentation. Otherwise, I will go ahead and add my notes as I see best fit !

**Comment by mwestphal** [comment]
For now animation is just a single paragraph.

I we want to expand this doc, we may be better adding a dedicated .md file for it, which means it should be listed in the index.
