### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#126]
**Describe the bug**
A clear and concise description of what the bug is, a screenshot helps a lot.

**To Reproduce**
 1. Open the file using `f3d --dry-run example.glb`
 2. step 2
 3. step 3

**Expected behavior**

**System Information:**
 - OS:
 - GPU and GPU driver:

**F3D Information**
Paste the content of `f3d --version`:

**Additional context**

**Comment by mwestphal** [comment]
having fun ? :p
