### ISSUE TITLE
Improve testing developement documentation

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1260]
**Context**
F3D has a short doc about adding tests when contributing: https://f3d.app/doc/dev/TESTING.html
This doc could be expanded and improved so that new developpers have a easier time figuring it out.

**Suggested solution**
 - Expand the current doc to cover all usecases, especially the bit about interaction test and recover baseline from CI
 
**Skills**
 - Markdown

**Comment by kidharb** [comment]
Please assign this to me

**Comment by mwestphal** [comment]
any news on this one @kidharb ?

**Comment by kidharb** [comment]
I have entered a rabbit, ie I am learning `cmake` as well as the testing environment in `f3d`.
I will start improving the docs soon.

**Comment by mwestphal** [comment]
Any ongoing work on that @kidharb ? :)

**Comment by kidharb** [comment]
Thanks for following up. 

In addition to the above mentioned topics of retrieving baselines and interactive testing, I will also cover recording tests cases and abit about the testing framework is implemented with cmake.
I should have something by the end of this week

**Comment by mwestphal** [comment]
Awesome!

**Comment by kidharb** [comment]
Can we close this issue?
