### ISSUE TITLE
thumbnail is not working with step file

### ISSUE THREAD

**Issue by zhangcanfeng612** [f3d-app/f3d#1270]
**System Information:**
 - OS: windows 10

![image](https://github.com/f3d-app/f3d/assets/22046100/872bfe70-d311-460b-9e9d-d34d59d00181)

**Comment by Meakk** [comment]
What is the size of your files?

**Comment by zhangcanfeng612** [comment]
![image](https://github.com/f3d-app/f3d/assets/22046100/afa971b8-a93f-407d-ae97-c7c7a639161d)
![image](https://github.com/f3d-app/f3d/assets/22046100/4ef4b2a2-77b0-4451-9bca-b0203fb65bad)

**Comment by zhangcanfeng612** [comment]
![image](https://github.com/f3d-app/f3d/assets/22046100/5aa53f3d-4fb7-4232-b29b-639c8479bdf6)

**Comment by mwestphal** [comment]
Which version of F3D ?

**Comment by zhangcanfeng612** [comment]
I am using the latest version(2.3.0)， and I have installed 3ds max. This software also has the function of generating thumbnails. I don’t know if it will have any impact.

**Comment by mwestphal** [comment]
> This software also has the function of generating thumbnails. I don’t know if it will have any impact.

This may be related, could you try on another computer without 3ds max ?

**Comment by mwestphal** [comment]
Please try on the last release, closing.
