### ISSUE TITLE
F3D crashes on resizing diagonally on windows

### ISSUE THREAD

**Issue by chirag-droid** [f3d-app/f3d#1286]
**Describe the bug**
F3D crashes on Windows if you resize too fast.

**To Reproduce**
 1. Open F3D app
 2. Do a fast resize

**Expected behavior**
F3D doesn't crash just like on Linux.

**System Information:**
 - OS: Windows 11
 - GPU and GPU driver: GTX 1650 & v551.23

**F3D Information**
Paste the content of `f3d --version`: 2.3.0

**Additional Context**

https://github.com/f3d-app/f3d/assets/81347541/850a5908-3c8d-46e9-acc0-e4ec12b28b42

**Comment by mwestphal** [comment]
@Meakk I remember a similar issue, but cant find it anymore.

**Comment by mwestphal** [comment]
this one https://github.com/f3d-app/f3d/issues/835

**Comment by chirag-droid** [comment]
Given the window in his demo doesn't crash the crash occurs on newer version of vtk

**Comment by mwestphal** [comment]
Im unable to reproduce with F3D 2.3.0

**Comment by mwestphal** [comment]
Unable to reproduce with the nightly

**Comment by chirag-droid** [comment]
I am able to consistently reproduce it by resizing diagonally and then stretching horizontally. This doesn't happen when you resize on horizontal or vertical axis alone.

https://github.com/f3d-app/f3d/assets/81347541/f9166f68-a668-4a76-b957-81c35c3a5f25

**Comment by mwestphal** [comment]
Im still unable to reproduce.

@Meakk what about u ?

**Comment by mwestphal** [comment]
caused by a "software" called nahimic. Unrelated to our stack.

ImGui and other software have the same issue/

https://github.com/ocornut/imgui/issues/3321
