### ISSUE TITLE
Add a hotkey to load all file in current containing folder

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#129]
Would it be possible to add a key that allows to add all files from a folder after opening one file out of it? E.g. I drop a file from a folder, then - while looking at the file - consider to look at all. Also (it's a shame to say that, but) as I am forced to use win at work I got used to its picture viewer that by default allows to browse all files in the same folder.

from @drtrigon

**Comment by drtrigon** [comment]
Thanks a lot! In which version will this be released (except of nightly) ?
