### ISSUE TITLE
f3d 2.3.0 tar.gz checksum mismatch

### ISSUE THREAD

**Issue by iMichka** [f3d-app/f3d#1294]
**Describe the bug**
The https://github.com/f3d-app/f3d/archive/refs/tags/v2.3.0.tar.gz file has a different checksum now than on the release day.

**To Reproduce**
The actual checksum: 9c2906b62f3066f075effbabd6501964391e8a8ffad6ed773c33db12580cc466

**Expected behavior**
The expected checksum: 13d33b49bad71a5a1bb9d1ecc927cc2d26d767daebaa6dba145bcc411b8d5f27

**System Information:**
macOS / Linux

**F3D Information**
N/A

**Additional context**
The checksum change was detected in Homebrew, see this pull request https://github.com/Homebrew/homebrew-core/pull/154232

**Comment by mwestphal** [comment]
History was rewritten, github created a new .tar.gz, hence the new checksum.

**Comment by iMichka** [comment]
Thanks for the confirmation; we will update the checksum and ship a new version in Homebrew.

Just wanted to let you know that from a package manager perspective, this was not the right thing to do: https://git-scm.com/docs/git-tag#_on_re_tagging (but you might already be aware of that and had your reasons). Nothing really bad happened, but due to increased scrutiny / security reasons on our side, we are always worried when checksums change ...

**Comment by mwestphal** [comment]
Yeah, that was definitely a bad thing that we will never do again. Sorry about that. I found no other way to cleanup the LFS file that were preveting anyone to push to the project on the main fork.

Sorry again.
