### ISSUE TITLE
Upon app launch on macOS, key press does not register until user clicks within window 

### ISSUE THREAD

**Issue by kathleenhang** [f3d-app/f3d#1295]
**Describe the bug**
Upon app launch, key presses do not register until user clicks within window.

**To Reproduce**
 1. Open F3D app
 2. Press "H" to open cheatsheet menu
 3. F3D does not register key press. System error beep sound plays.

**Expected behavior**
Upon app launch, key presses are registered without user having to click within the window.

**System Information:**
 - OS: macOS Sonoma 14.1.2

**F3D Information**
F3D - A fast and minimalist 3D viewer
Version: 2.3.0-72-gd1952fda.
Build date: 2024-02-27 22:40:01.
Build system: Darwin 64-bits.
Compiler: AppleClang 15.0.0.15000100.
External rendering module: OFF.
Raytracing module: OFF.
VTK version: 9.2.6.

**Additional Information**
- macOS issue

**Comment by Meakk** [comment]
Sounds like a focus issue. Maybe related: https://developer.apple.com/documentation/appkit/nsapplication/activationoptions/1525559-activateignoringotherapps

The fix should probably be in VTK directly, but we might be able to test it easily by putting this call in https://github.com/f3d-app/f3d/blob/7bc53ec1c839012a11fc1709e6b2505911f315b1/application/F3DNSDelegate.mm#L37

See https://stackoverflow.com/questions/5089598/set-nswindow-focused#comment37953271_5089809

**Comment by mwestphal** [comment]
@kathleenhang since you are on mac, you should be able to check that easily :)

**Comment by kathleenhang** [comment]
Thanks! I added the fix  `[[NSApplication sharedApplication] activateIgnoringOtherApps:YES];` but it still runs into the same issue. 

It seems like the app does gain focus because I can drag the app around my desktop from its mac header bar. However, I still am not able to use the hotkeys. 

The hot keys only work once I click within the window.

**Comment by Meakk** [comment]
Fixed here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11084

**Comment by mwestphal** [comment]
VTK updated here: https://github.com/f3d-app/f3d/pull/1394

**Comment by mwestphal** [comment]
Lets wait for the next nightly before closing this.

**Comment by Meakk** [comment]
Checked the nightly, it's fixed
