### ISSUE TITLE
[SOLVED] Not a bug - Navigate next/previous file with arrow keys doesn't work properly (has workaround)

### ISSUE THREAD

**Issue by VeganPete** [f3d-app/f3d#1300]
[SOLVED] Not a bug - After opening a 3D file (glb), using left and right arrow keys (to navigate through next/previous files) doesn't work as intended. When pressing left/right, a white progress bar appears but the exact same file is loaded, rather than the next/previous file. As a workaround (temporary fix), one can press the 'down' arrow first (just once), the left/right arrows work perfectly until the preview window is closed/reopened - then left/right will stop functioning again.

**To Reproduce**
 1. Open the file using `f3d`
 2. step 2, click right arrow
 3. step 3, click left arrow
 4. ...click as many times as you like nothing will happen except a brief appearance of a white progress bar.
 5. Now click 'down' arrow.
 6. Left/Right arrows now start working.

**Expected behavior**
Without needing to press the down arrow first, Next/previous files should be opened/displayed using the left/right keys.

**System Information:**
 - OS:Windows 11 10.22631
 - GPU and GPU driver: Ryzen 7840u (780M) with Adrenalin 24.1.1

**F3D Information**
2.3.0 installed

**Note**
This issue was also present on my older system (Win10, Nvidia GTX1060).

**Comment by mwestphal** [comment]
Opening a single file open a single file, this is expected.

When you press down arrow, it loads the whole folder:

From: https://f3d.app/doc/user/INTERACTIONS.html

> ↓: add current file parent directory to the list of files, reload the current file and reset the camera.

Maybe this behavior could be reworked and we could open automatically a folder when opening a single file using an option though.

**Comment by VeganPete** [comment]
I see, that's perfect. Thanks for the info. I hadn't even spotted the github doc, just the help-file that ships with f3d app when pressing 'h' key. Maybe worth adding an automatic folder open, if it's not  too much hassle, in a future update - or just add the 'down key' info in the help file as it's not much effort for users just to press an extra key. Thank you.

**Comment by mwestphal** [comment]
> Maybe worth adding an automatic folder open,

This can be problematic for users with thousands of files in folder but adding it optional makes sense.

> or just add the 'down key' info in the help file as it's not much effort for users just to press an extra key.

What do you mean the help file, this ? its already documented.

![image](https://github.com/f3d-app/f3d/assets/3129530/80c0a305-b62e-412e-b028-c8222e7d086c)

**Comment by VeganPete** [comment]
Oh, I see it now. I simply didn't comprehend the wording. Thanks. I understand now, best to leave it as is then. I do actually have thousands of files and thought it was odd to have to open and close each file individually, rather than have a simple way of flicking through them - that's the only reason I signed up to comment - but I see it was my mistake, the feature is there and working correctly and documented correctly. Thanks for explaining.
