### ISSUE TITLE
About how to localize

### ISSUE THREAD

**Issue by Hzh873851987** [f3d-app/f3d#1318]
**Is there any way to localize the text in it?**

**Comment by mwestphal** [comment]
What do you mean ?

**Comment by snoyer** [comment]
> What do you mean ?

Translate in a different language for non-english speaking users

**Comment by mwestphal** [comment]
No, F3D is not localized and I dont think we will plan it. BTW the amount of text is quite small. 

WDYT @Meakk ?

**Comment by Hzh873851987** [comment]
Indeed, most of our staff don't understand English very well
It seems that I can only teach them how to use F3D correctly in a simple way first
This issue can be closed, thanks for the answer
