### ISSUE TITLE
Factorize Mesa installation in CI and SB

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1352]
**Is your feature request related to a problem? Please describe.**
Mesa installation is different in the CI and the super build.
Let's try to create an external `f3d-app/install-mesa` github action we can reuse anywhere

**Comment by mwestphal** [comment]
- Action added here: https://github.com/f3d-app/install-mesa-windows-action
- Available in marketplace here: https://github.com/marketplace/actions/install-mesa-windows
- Used in f3d here: https://github.com/f3d-app/f3d/pull/1387
- Used in fsb here: https://github.com/f3d-app/f3d-superbuild/pull/172
