### ISSUE TITLE
Windows 10 thumbnail .stl

### ISSUE THREAD

**Issue by Viper-by** [f3d-app/f3d#1371]
Hello
After reinstalling Windows 10, I cannot enable thumbnail .stl using F3D.
I tried a full installation into the system as in the picture, but it didn’t help. What am I doing wrong, please help
![1](https://github.com/f3d-app/f3d/assets/89794540/5288f8b5-6487-439b-b19e-731479fadcf1)

**Comment by mwestphal** [comment]
Which version if F3D ? 

What happens when you go to a folder ?

**Comment by Viper-by** [comment]
F3D last version - F3D-2.4.0-Windows-x86_64-raytracing
![image](https://github.com/f3d-app/f3d/assets/89794540/2775a60f-3ab4-4ee2-b993-0d572ccd49ed)

**Comment by Viper-by** [comment]
Perhaps F3D uses Microsoft libraries? Do they need to be updated after reinstalling the OS?

**Comment by mwestphal** [comment]
Can you try this: https://f3d.app/doc/user/DESKTOP_INTEGRATION.html#windows ?

**Comment by mwestphal** [comment]
@Viper-by , so I checked F3D 2.4.0 on windows 10 and the thumbnailer is working great. You must have something special.eg: https://github.com/f3d-app/f3d/issues/1129

**Comment by Viper-by** [comment]
> Can you try this: https://f3d.app/doc/user/DESKTOP_INTEGRATION.html#windows ?
Activated manually F3DShellExtension.dll
![2](https://github.com/f3d-app/f3d/assets/89794540/dad86ee9-7e02-42e2-bd32-140dab727db0)
Before reinstalling the OS, thumbnail f3d also worked correctly - I’ll read the topic above, thank you

**Comment by mwestphal** [comment]
> Activated manually F3DShellExtension.dll

Ok, so using the command manually works for you ?

**Comment by Viper-by** [comment]
Unfortunately, it doesn’t work - I posted a screenshot of the manipulation done, but the thumbnail is not displayed

**Comment by mwestphal** [comment]
Does other thumbnails works ? for example Windows supports showing thumbnails for .png and .jpg files.

**Comment by Viper-by** [comment]
Other thumbnails works
![image](https://github.com/f3d-app/f3d/assets/89794540/f4deb401-0d20-4d55-a5ec-78344442a432)

**Comment by mwestphal** [comment]
(By the way, you may want to come over to our discord to discuss this and so that more people could help: 
https://discord.f3d.app)

**Comment by mwestphal** [comment]
with no feedback from @Viper-by . Ill close this, feel free to reopen if you have more info so we can understand what is going on.
