### ISSUE TITLE
F3D build not reproducible because of executable full path in man page

### ISSUE THREAD

**Issue by mzf-guest** [f3d-app/f3d#1376]
**Describe the bug**
After [this commit](https://github.com/f3d-app/f3d/commit/7a1cfa789eed73c3514003a77e758ee4cef9dd0f#diff-7c425fb94271a2540a78bd3b67b26cf5f90dd107db21df60aaf3a57137b379f2L214), the help message displays the full path of the executable. As the man page is generated with from this help message, it makes the build not reproducible with `F3D_LINUX_GENERATE_MAN=ON`

You may check [f3d_man.zip](https://github.com/f3d-app/f3d/files/14968514/f3d_man.zip) which contains the generated man pages from two different build folders.

**To Reproduce**
 1. build f3d in a first path with `F3D_LINUX_GENERATE_MAN=ON` CMake variable
 2. build f3d in a different path with `F3D_LINUX_GENERATE_MAN=ON` CMake variable
 3. Compare the f3d.1 files, they differ in the Usage and Example sections.

**Expected behavior**
The exact same manual page not depending on build folder path.

**System Information:**
 - OS: Debian unstable
 - GPU and GPU driver: Not relevant

**F3D Information**
Paste the content of `f3d --version`: 2.4.0

**Additional context**
For the Debian package, I would simply revert the `ExecutableName` variable to `F3D::AppName` in `application/F3DOptionsParser.cxx`.
However, please advise how to fix it for the general case and I would be happy to provide a PR.

Thanks!

**Comment by Meakk** [comment]
FYI @snoyer  
The suggested solution looks good to me, wdyt?

**Comment by snoyer** [comment]
If I remember correctly `F3D::AppName` is `F3D` (all caps) and at the time the choices for the "f3d" instances in the help text were:
1. leave them hardcoded in the strings
2. introduce a new global variable containing lowercase f3d
3. just use the existing `ExecutableName`

I went with the last one assuming in nominal use the app would be aliased to simply `f3d` and that's what users would see when calling `f3d -h`

I guess now the options are:
1. ~~leave~~ have them hardcoded in the strings again
2. introduce a new global variable containing lowercase f3d
3. ~~just~~ use the existing `ExecutableName` with some `std::fs::path` stuff to keep only the name part
4. fudge it from cmake. `ExecutableName` is basically `argv[0]` not the actual absolute path of the executable, so changing the working directory or doing something like `exec -a` could work

**Comment by mwestphal** [comment]
Indeed, this is incorrect.


> have them hardcoded in the strings again
> `F3D::ExecutableName`

This is the simplest way to go. Its not like we are going to change the executable name at any point.

Want to take care of it @snoyer ?

**Comment by snoyer** [comment]
> This is funny though:
> 
> ```
> $ ../../f3d/build/bin/f3d --help
> F3D - A fast and minimalist 3D viewer
> Usage:
>   ../../f3d/build/bin/f3d [OPTIONS...] file1 file2 ...
> ```

The real funny part is, from [`help2man`'s manual](https://www.gnu.org/software/help2man/#g_t_002d_002dhelp-recommendations):
> Use `argv[0]` for the program name in these synopses, just as it is, with no directory stripping. This is in contrast to the canonical (constant) name of the program which is used in `--version`. 

If I read it correctly it means we're doing it right actually?

I was hoping for `help2man` to have an argument to override `argv[0]` but I can't see one :(
Best I can come up with is:
```sh
echo "exec -a f3d /foo/bar/baz/bin/f3d \$*" > /tmp/f3d.sh
help2man /tmp/f3d.sh
```
- pros: app uses `argv[0]`, doesn't hardcode `"f3d"`, manpage issue solved at manpage generation
- cons: is dirty hack?

**Comment by mwestphal** [comment]
I dont think GNU ever considered reproducible build in that doc.

I'd rather not use a dirty hack and assume that we are not following GNU recommandation here.

inputs @mzf-guest ?

**Comment by mwestphal** [comment]
@snoyer so, do you want to do it ?
