### ISSUE TITLE
Segmentation fault in cli when not in graphic environment

### ISSUE THREAD

**Issue by xenatis** [f3d-app/f3d#1392]
**Describe the bug**
Connected by ssh: 
`f3d file.stl --output=file.png` returns error `Segmentation fault`

Using terminal in graphic environment (Gnome), no problem.

**To Reproduce**
 1. Connect by ssh
 2. run `f3d file.stl --output=file.png`

**System Information:**
 - OS: Debian 11
 - GPU and GPU driver: 00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

- OS: Debian 12
- GPU and GPU driver: 01:00.0 VGA compatible controller: NVIDIA Corporation GP107GL [Quadro P400] (rev a1)

**F3D Information**
F3D 2.4.0

F3D - A fast and minimalist 3D viewer
Version: 2.4.0.
Build date: 2024-04-03 14:13:39.
Build system: Linux 64-bits.
Compiler: GNU 8.4.0.
External rendering module: ON.
Raytracing module: ON.
VTK version: 9.3.0-2200-g1312f8a726 (date: 20240312).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2024 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Comment by mwestphal** [comment]
Indeed, with the standard release, xorg server is needed.

You should use the headless release instead:)

https://github.com/f3d-app/f3d/releases/tag/v2.4.0

**Comment by mwestphal** [comment]
Please note F3D now support headless and non-headless in a single version, you can try the last nightly for that: https://github.com/f3d-app/f3d/releases/tag/nightly
