### ISSUE TITLE
Add a Pan method

### ISSUE THREAD

**Issue by Nokse22** [f3d-app/f3d#1430]
**Is your feature request related to a problem? Please describe.**
When having an external window there is not method to pan.

**Describe the solution you'd like**
A Pan method where you pass the delta x and y to pan vertically or horizontally.

**Describe alternatives you've considered**
Calculate the new camera position and focal point in the external program.

**Additional context**
[Here](https://github.com/Nokse22/Exhibit/blob/3f6b2118d0365da4eeab1e8cc87d760cb5c54dbd/src/window.py#L204-L212) is the solution thanks to @snoyer that I have in my app.

**Comment by mwestphal** [comment]
Good point @Nokse22 , good addition idea!
