### ISSUE TITLE
How to produce Thumbnail PNG for a chosen color

### ISSUE THREAD

**Issue by shannatarajan** [f3d-app/f3d#1452]
Hi

I would like to create a thumbnail for different colors. I have no way of doing it other than setting some values for --color in the options. But I don't know exactly what value to set.

In other words,  need to produce thumbnail image for  particular RGB value or Hex value in css

The documentation is not very clear. Can anyone help?

Thank You

**Comment by Meakk** [comment]
The RGB value has to be specified as float values, eg:
- black: 0,0,0
- red: 1,0,0
- dark blue: 0,0,0.5

**Comment by snoyer** [comment]
F3D expects colors to be in `r,g,b` format where `r`, `g`, and `b` are between `0` and `1`.
CSS hex encodes color as `#rrggbb` where `rr`, `gg` and `bb` are between `00` and `ff` (that is between `0` and `255`).
You should be able to find tools online to convert, for example https://www.rapidtables.com/convert/color/hex-to-rgb.html

**Comment by shannatarajan** [comment]
Thank you very much, This is exactly what I am looking for.  This will be of great help. Thank You

**Comment by shannatarajan** [comment]
Hi, sorry for being a pain and keep getting back to the same point, this conversion tool worked great to get few shades, but most of the time, it generates totally irrelevant colors. I am trying to get an image of yellow color, but when I use this tool to get the r, g,b values, it produces totally different. Is there any other parameters or settings I need to change to get the same color what I aim for. For example #dfff00 , but it never works as I expected. Is there anyone who can help? Thanks in advance.

**Comment by mwestphal** [comment]
> this conversion tool worked great to get few shades, but most of the time, it generates totally irrelevant colors. 

Could you share more info about your data, the color you are using, the command line you use and so on.

**Comment by mwestphal** [comment]
Do not hesitate to come to our discord to discuss!

https://discord.f3d.app
