### ISSUE TITLE
Avoid failing when provided animation time is outside of time range

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1501]
**Describe the bug**
Loading a timestep outside of the temporal range fails in 

```
Provided time value: t is outside of animation time range: [t0, t1] 
```

Instead it could be a warning only and load the closest time instead.

**Comment by mwestphal** [comment]
Should I assign this to you @snoyer ?

**Comment by snoyer** [comment]
> Should I assign this to you @snoyer ?

sure, PR is #1504
