### ISSUE TITLE
Improve libf3d API in regards to time management

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1502]
**Describe the bug**
Improve libf3d API in regards to time management

There is currently no way in libf3d to:
 - extract the timerange
 - select a timestep and ONLY call LoadAtTime, not a complete loadScene

**Comment by Nokse22** [comment]
For Exhibit to be able to show animations I need to know the time range and if any animation is preset so #1628 would be needed. Then using `scene.animation.time` I can play animations controlling them from the app.

**Comment by snoyer** [comment]
> select a timestep and ONLY call LoadAtTime, not a complete loadScene

For this one, as discussed a while back on Discord, there are 2 ways to go about it:

1. expose `LoadAtTime()` in the API somehow
2. have `scene.animation.time` _not_ be a "load time" option, and internally call `LoadAtTime()` if the value of `scene.animation.time` has changed between calls to `render()`

The second one would be more convenient for users and doesn't require expanding the API, but there's a concern about silently triggering IO as some readers may require reloading the whole file.
