### ISSUE TITLE
*.brep default config is missing

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1505]
**Describe the bug**
The *.brep default config is missing.  
It should be the same as *.step and *.iges files

**Context**
Each plugin in F3D is responsible to describe the configuration to use for each format
The OCCT plugin provide support for .brep file, but the config is missing.

**Solution**
 - Add brep in `plugins/occt/configs/*.d/10_occt.json`
 - Check it works with brep file

**Comment by NWc0de** [comment]
pull request for this (:

https://github.com/f3d-app/f3d/pull/1546

**Comment by Meakk** [comment]
PR merged, closing it
