### ISSUE TITLE
F3D Web first render is incorrectly lit

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1506]
**Describe the bug**
F3D Web first render is incorretly lit

**To Reproduce**
 1. got to https://f3d.app/web
 2. Load a file
 4. FIle is not correctly lit
 5. Move camera around
 6. Ligthing is corrected

https://github.com/f3d-app/f3d/assets/3129530/eed3abc3-c834-4f4b-bdee-49bcc4d73efa

**Expected behavior**
Correct lighting right away

**Additional context**
occlusion texture generation is not updated for some reason, related to SSOA, better to reproduce in python if possible to check if this is WASM specific

**Comment by mwestphal** [comment]
This seems related to SSAO

**Comment by mwestphal** [comment]
First render of f3d.vtp:

![a](https://github.com/user-attachments/assets/3095eecf-0807-47d5-a3af-97606707155e)


Then it looks perfect after:

![a](https://github.com/user-attachments/assets/e292115a-b33d-4dfc-84af-0cce80369fb6)

**Comment by snoyer** [comment]
first render looks like missing normals as per #1553

**Comment by Meakk** [comment]
fixed here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11417

**Comment by Meakk** [comment]
Fix by updating VTK in https://github.com/f3d-app/f3d-docker-images/pull/18
