### ISSUE TITLE
Cannot build 2.5.0 (RPATH/RUNPATH)

### ISSUE THREAD

**Issue by jubalh** [f3d-app/f3d#1511]
I'm maintaining f3d for openSUSE and get a build failure that I don't quite understand for 2.5.0.
2.3.0 still build fine with same recipe.
I'll adapt the issue template since think it is more appropriate, hope that's okay.

The error:
```
[   63s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/f3d-2.5.0-13.1.x86_64/usr/lib64/libf3d.so.2
[   63s] CMake Error at library/cmake_install.cmake:74 (file):
[   63s]   file RPATH_CHANGE could not write new RPATH:
[   63s] 
[   63s]     
[   63s] 
[   63s]   to the file:
[   63s] 
[   63s]     /home/abuild/rpmbuild/BUILDROOT/f3d-2.5.0-13.1.x86_64/usr/lib64/libf3d.so.2.5
[   63s] 
[   63s]   The current RUNPATH is:
[   63s] 
[   63s]     /home/abuild/rpmbuild/BUILD/f3d-2.5.0/build/lib:
[   63s] 
[   63s]   which does not contain:
[   63s] 
[   63s]     /usr/lib64:/home/abuild/rpmbuild/BUILD/f3d-2.5.0/build/lib:
[   63s] 
[   63s]   as was expected.
[   63s] Call Stack (most recent call first):
[   63s]   cmake_install.cmake:57 (include)
```

Full [build log](https://build.opensuse.org/package/live_build_log/graphics/f3d/openSUSE_Tumbleweed/x86_64).

[Build recipe](https://build.opensuse.org/projects/graphics/packages/f3d/files/f3d.spec?expand=1).
The expanded macros can be seen in the log mentioned above.

**Comment by mwestphal** [comment]
Hi @jubalh 

A few remarks about the recipe:

```
rm -fv %{buildroot}%{_libdir}/libVTKExtensions*.a
```
Should not be needed if you use VTK 9.3.0

```
# this is needed so f3d autoloads the plugins for those filetypes specified in the configs
mkdir -p %{buildroot}%{_sysconfdir}/f3d/config.d
install -Dm644 plugins/assimp/configs/config.d/10_assimp.json %{buildroot}%{_sysconfdir}/f3d/config.d/10_assimp.json
install -Dm644 plugins/alembic/configs/config.d/10_alembic.json %{buildroot}%{_sysconfdir}/f3d/config.d/10_alembic.json
install -Dm644 plugins/exodus/configs/config.d/10_exodus.json %{buildroot}%{_sysconfdir}/f3d/config.d/10_exodus.json
install -Dm644 plugins/native/configs/config.d/10_native.json %{buildroot}%{_sysconfdir}/f3d/config.d/10_native.json
install -Dm644 plugins/occt/configs/config.d/10_occt.json %{buildroot}%{_sysconfdir}/f3d/config.d/10_occt.json
```

Should not be done manually, instead use the right install component:

https://f3d.app/doc/dev/BUILD.html#installing

You may want to enable other optional components.

As to the issue itself, you probably should try:

`-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON`

I'm not sure why it is needed though.

**Comment by mwestphal** [comment]
Related to this: https://github.com/f3d-app/f3d/pull/1217

**Comment by jubalh** [comment]
> Should not be needed if you use VTK 9.3.0

Indeed :)

> You may want to enable other optional components.

For some of them we don't have the dependencies packaged yet.

> -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON

That works as well!

Thank you!

**Comment by mwestphal** [comment]
You definitely should not install `dependencies` component in the context of a distribution package.

**Comment by jubalh** [comment]
Sure, not doing that :)
