### ISSUE TITLE
Step file is not a supported file fomat

### ISSUE THREAD

**Issue by LimesKey** [f3d-app/f3d#1548]
**Describe the bug**
I'm attempting to render a KiCad exported Step file of my PCB. Opening F3D with the `.step` file produces `/home/ryan/Downloads/extruderevolved.step is not a file of a supported file format`, when it should be supported, I verified that the 3d model is in fact a step file and isn't corrupted or anything by using various online 3d model viewers and it rendered my 3d. I'm using the latest version of KiCad and F3D.

**To Reproduce**
 1. Export a STEP file in KiCad with the default settings
 2. Install F3D as a system package 
 4. Run F3D either by opening it with the file explorer or by typing `f3d /home/ryan/Downloads/extruderevolved.step` with the step file

**Expected behavior**
A rendered 3D Model

**System Information:**
 - OS: Linux Mint 21.3 Cinnamon
 - GPU and GPU driver: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics]

**F3D Information**
Paste the content of `f3d --version`:
```
f3d 1.2.1

F3D - A fast and minimalist 3D viewer
Version: 1.2.1
Build date: 2022-02-20 15:49:12
System: Linux x86_64
Compiler: GNU 11.2.0
RayTracing module: OFF
Exodus module: ON
OpenCASCADE module: OFF
Assimp module: OFF
VTK version: 9.1.0 (build 0)
```
**Additional context**
The issue only occurs if I install F3D as a system package however it works perfectly with my 3d model if I install it as a flatpak. I can attach my `.step` 3d model file if needed.

**Comment by mwestphal** [comment]
Opencascade module is not enabled in this package. This is a question for the maintainer of this package. Use the binary .deb from our download page instead: https://f3d.app
