### ISSUE TITLE
App launches and crashes (segfault)

### ISSUE THREAD

**Issue by Beefysam211** [f3d-app/f3d#1549]
**Describe the bug**
opening f3d just makes a window popup and immediately closes without displaying any error

**To Reproduce**
 1. open f3d as normal or even open it directly with any 3d model file out there

**Expected behavior**
the application should just work like normal

**System Information:**
 - OS: arch linux 6.10.0-zen1-2-zen
 - GPU and GPU driver: AMD Ryzen 7 5700U (16) @ 4.37 GHz AMD Lucienne [Integrated]

**F3D Information**
F3D 2.5.0

F3D - A fast and minimalist 3D viewer
Version: 2.5.0.
Build date: 2024-07-17 12:28:30.
Build system: Linux 64-bits.
Compiler: GNU 14.1.1.
External rendering module: ON.
Raytracing module: ON.
VTK version: 9.3.0.
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2024 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Additional context**
Opening the application through the terminal give me this output:
```
[thinkchadarch:33247:0:33247] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:  33247) ====
 0 0x000000000004d212 ucs_event_set_fd_get()  ???:0
 1 0x000000000004d3dd ucs_event_set_fd_get()  ???:0
 2 0x000000000003d1d0 __sigaction()  ???:0
 3 0x0000000000163b5e vtkRenderer::GetActiveCamera()  ???:0
 4 0x00000000000ddb24 vtkF3DRenderer::Initialize()  ???:0
 5 0x00000000000de376 vtkF3DRendererWithColoring::Initialize()  ???:0
 6 0x00000000000a40d0 vtkF3DGenericImporter::UpdateTimeStep()  ???:0
 7 0x0000000000091e10 f3d::log::debugInternal()  ???:0
 8 0x000000000005e8e7 std::_Function_handler<bool (char), std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, true, true> >::_M_manager()  ???:0
 9 0x0000000000054513 std::_Function_handler<bool (char), std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, true, true> >::_M_manager()  ???:0
10 0x0000000000018779 ???()  /usr/bin/f3d:0
11 0x0000000000025e08 __libc_init_first()  ???:0
12 0x0000000000025ecc __libc_start_main()  ???:0
13 0x0000000000018f25 ???()  /usr/bin/f3d:0
=================================
Segmentation fault (core dumped)
```

**Comment by Meakk** [comment]
I suspect a gpu issue but it's hard to tell. What's the driver you are currently using? Are you using X or Wayland?

**Comment by Beefysam211** [comment]
> How did you install F3D ?

through the official arch repo, it was working fine for me before I updated my system yesterday.

**Comment by Beefysam211** [comment]
> I suspect a gpu issue but it's hard to tell. What's the driver you are currently using? Are you using X or Wayland?

RADV vulkan drivers on wayland

**Comment by mroetsc** [comment]
Hey there, I have the same problem with the same terminal output.
I am on Arch Linux as well and installed f3d through the official arch repos.

**System Information:**
* OS: Arch Linux 6.10.0-arch1-2
* CPU: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
* GPU: integrated graphics

**F3D Information**
F3D 2.5.0

F3D - A fast and minimalist 3D viewer
Version: 2.5.0.
Build date: 2024-07-17 12:28:30.
Build system: Linux 64-bits.
Compiler: GNU 14.1.1.
External rendering module: ON.
Raytracing module: ON.
VTK version: 9.3.0.
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2024 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Comment by mwestphal** [comment]
Can you try with the binary archive from http://f3d.app ?

**Comment by mwestphal** [comment]
Then this sounds like a arch package issue.

**Comment by Beefysam211** [comment]
> Using the binary from [here](https://f3d.app/doc/user/INSTALLATION.html#current-release-packages-250) (Linux portable in bin) works as expected

Just installed the portable version, can confirm it does indeed work.

**Comment by flaviut** [comment]
I think your guess about this being an AMD GPU drivers issue is right, I can also reliably reproduce this:

```
OpenGL renderer string: AMD Radeon RX 6600 XT (radeonsi, navi23, LLVM 18.1.8, DRM 3.57, 6.9.7-arch1-1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.1.4-arch1.2
```

**Comment by Beefysam211** [comment]
@mwestphal hey, any ETA on the official arch repo package fix, for now the portable binary is fine but when should we expect a patch to arrive. Thanks for your attention.

**Comment by mwestphal** [comment]
As I said, its a package issue, so you want to report it on the arch linux package, which is not maintained by F3D maintainers.

Maybe @svenstaro can help though.

**Comment by mwestphal** [comment]
BTW, you can also try f3d-git or f3d-bin from the AUR.

**Comment by Beefysam211** [comment]
> BTW, you can also try f3d-git or f3d-bin from the AUR.

Alright, thanks!

**Comment by svenstaro** [comment]
Please report this on the Arch bug tracker so we can triage this.

**Comment by mwestphal** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/f3d/-/issues/2
