### ISSUE TITLE
GLTF file makes F3D crash

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1550]
**Describe the bug**
When opening the following file, F3D crashes
[crash.zip](https://github.com/user-attachments/files/16389758/crash.zip)

**To Reproduce**
 1. Open the file using `f3d --dry-run crash.glb`
 2. Crash

**Expected behavior**
F3D shouldn't crash

**System Information:**
 - OS: Windows
 - GPU and GPU driver: NVIDIA 2070M

**F3D Information**
Paste the content of `f3d --version`:
```
F3D - A fast and minimalist 3D viewer
Version: 2.5.0-RC2.
Build date: 2024-06-30 11:06:59.
Build system: Windows 64-bits.
Compiler: MSVC 19.40.33811.0.
External rendering module: ON.
Raytracing module: OFF.
VTK version: 9.3.0-3457-gecf3646d64 (date: 20240620).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2024 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

**Comment by mwestphal** [comment]
Still present in VTK master, fix incoming.
