### ISSUE TITLE
SSAO isn't working with model without normals

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1553]
**Describe the bug**
When there's no normals on the model, SSAO is not working properly

![image](https://github.com/user-attachments/assets/e279e225-51cd-4203-a892-de3d61d3b6bc)

**To Reproduce**
 1. Open a file without normals
 2. Enable SSAO

**Expected behavior**
SSAO should work with generated flat normals

**Comment by Meakk** [comment]
Shader G-buffer output (last image is black but it should contain the normals)

![image](https://github.com/user-attachments/assets/9cd2b920-6056-4766-bd5e-fbe33d2b6b7b)

Fragment output is set with:
```cpp
fragOutput2 = vec4(normalVCVSOutput, 1.0);
```

But without normal, the shader contains:

```cpp
    // Generate the normal if we are not passed in one
    vec3 primitiveNormal;
    if (primitiveSize == 1) {
        primitiveNormal = vec3(0.0, 0.0, 1.0);
    }
    else if (primitiveSize == 2) {
        float addOrSubtract = (dot(fdx, fdy) >= 0.0) ? 1.0 : -1.0;
        vec3 lineVec = addOrSubtract*fdy + fdx;
        primitiveNormal = normalize(cross(vec3(lineVec.y, -lineVec.x, 0.0), lineVec));
    }
    else {
        primitiveNormal = normalize(cross(fdx, fdy));
        if (cameraParallel == 1 && primitiveNormal.z < 0.0) {
            primitiveNormal = -1.0*primitiveNormal;
        }
        if (cameraParallel == 0 && dot(primitiveNormal, vertexVC.xyz) > 0.0) {
            primitiveNormal = -1.0*primitiveNormal;
        }

    }
    vec3 vertexNormalVCVS = primitiveNormal;
    vec3 normalizedNormalVCVSOutput = normalize(vertexNormalVCVS);
```

So I'd say we should do something like:
```cpp
fragOutput2 = vec4(normalizedNormalVCVSOutput, 1.0);
```

**Comment by Meakk** [comment]
Fix in VTK: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11417

**Comment by Meakk** [comment]
Fixed by updating VTK in https://github.com/f3d-app/f3d-docker-images/pull/18

**Comment by mwestphal** [comment]
So this was F3DWeb specific right ?
