### ISSUE TITLE
Documenation error

### ISSUE THREAD

**Issue by iplayfast** [f3d-app/f3d#1557]
In Documentation at https://github.com/f3d-app/f3d/blob/master/doc/dev/GETTING_STARTED.md#linux
It says
cmake ../src
which won't work.
Should be cmake ..

**Comment by Meakk** [comment]
No I think the documentation is right.
When you are in `./build`, you need to point CMake to the source dir located in `./src`.

**Comment by mwestphal** [comment]
Confirmed, not a bug, src and build are at the same level if you follow the guide correctly.

**Comment by snoyer** [comment]
In other words it's not `cmake ..` because the guide does not `cd` into the source directory after cloning.

Here's what you'd need for a `cmake ..` version that would put `build` inside of `src`:
```diff
 mkdir f3d
 cd f3d
 git clone https://github.com/f3d-app/f3d src
+cd src
 mkdir build
 cd build
-cmake ../src
+cmake ..
 make
```

**Comment by Meakk** [comment]
By the way, I think we shouldn't have `cd` in the guide and rely on `-S` and `-B` cmake options instead.

**Comment by Meakk** [comment]
Something like that maybe? Looks cleaner to me.

```patch
 mkdir f3d
 cd f3d
 git clone https://github.com/f3d-app/f3d src
-mkdir build
-cd build
-cmake ../src
+cmake -S src -B build
-make
+cmake --build build
```

**Comment by mwestphal** [comment]
I'm not against it, beginners may be a bit confused by the syntax, but it's a guide to follow blind anyway, so I'm fine with such changes
