### ISSUE TITLE
image::save and image::saveToBuffer should check type is compatible with format

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1559]
**Describe the bug**
image::save and image::saveToBuffer should check type is compatible with format

**To Reproduce**
 1. Open the file using `f3d --dry-run example.glb`
 ```
 f3d::image hdrImg("palermo_park_1k.hdr");
hdrImg.save("path/to/disk.png");
 ```
 3. no error but it should fail instead
 
**Expected behavior**

Exception thrown

**Comment by Meakk** [comment]
Isn't it fixed now @mwestphal ?

**Comment by mwestphal** [comment]
it is, fixed by https://github.com/f3d-app/f3d/pull/1565
