### ISSUE TITLE
viewer plugin for windows explorer

### ISSUE THREAD

**Issue by Ulf3000** [f3d-app/f3d#1564]
**Is your feature request related to a problem? Please describe.**
Theres no 3d preview handler in windows, they had a the 3d viewer but that was never developed any further

**Describe the solution you'd like**
a preview handler for the preview pane in explorer which shows the 3d model
**Describe alternatives you've considered**
i dont think there are any 

**Additional context**
the decription: "It can provide thumbnails, support interactive hotkeys, drag&drop and integration into file managers."
peaqued my interest.. i hope its possible

**Contribution**

can you give me pointers ? what would "integration into file managers" mean, i guess you already made some tests in this regard ? 

EDIT: Ive seen that you already provide a thumbnail generator for explorer , but that one is quite buggy , any folder with lots of 3d models will crash the explorer window when f3d fails. It would be good if a safety measure could prevent that.

otherwise request still stands , please provide a mini 3d viewer for the preview pane.

**Comment by mwestphal** [comment]
Hi @Ulf3000 

If I'm not mistaken, this is a duplicate of https://github.com/f3d-app/f3d/issues/900

We want to offer such support but we need some dedicated WinAPI devs to look at it as we (F3D maintainers) are not familiar with it.

Lets discuss on discord :)

**Comment by mwestphal** [comment]
not a duplicate, but similar

**Comment by Ulf3000** [comment]
yep i wrote you on discord, its the long pathname problem. now here: https://github.com/f3d-app/f3d/issues/1566
