### ISSUE TITLE
Avoid displaying grid on the main axes

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1612]
**Describe the bug**
F3D can display a grid however, it could be improved as it display the grid on the main axis lines (there is a weird mix between black and the axis color which is sometimes a bit ugly)

![2024-06-05-114026_693x410](https://github.com/f3d-app/f3d/assets/6069752/702c094c-292f-470b-a1c9-b39705cad605)

**To Reproduce**
 1. Open the file using `f3d -g file`
 2. Zoom on the grid

**Expected behavior**
Do not display the grid on the main axes

**Suggested implementation**
In `vtkF3DOpenGLGridMapper.cxx`, identify the case where the grid is on the main axes and do not display the grid in that case. 

**Skills needed**
C++, OpenGL shaders, VTK

**Comment by rhysaelliott** [comment]
I would like to work on this issue

**Comment by mwestphal** [comment]
Nice, just assigned it to you
