### ISSUE TITLE
Proper dynamic window type support

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1621]
**Is your feature request related to a problem? Please describe.**
VTK recently introduced support for dynamic loading of graphical stack: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11367

Once https://github.com/f3d-app/f3d/pull/1620 is merged, we will support it implicitely but our current API
in regards to the WindowType does not reflect this, lets improve it

**Describe the solution you'd like**
 - Add a new window type, `dynamic`, which will be the default and just create a RenderWindow
 - Make `native` window type create actual native window
 - Add `egl` and `osmesa` window types (optional)
 - Add a log warning when trying to use F3D in interactive mode while not using `dynamic` or `native`.
 - Add testing in the lib for these
 - Rework headless CI to just position the env var instead of the CMake options
 - Add headless CI for windows too
 - In superbuild, remove headless build
 - In superbuild, add a simple headless test in CI using env var, on linux and windows

**Comment by apchenstu** [comment]
Looking forward to this update! I am also wondering whether the [pyf3d](https://pypi.org/project/f3d/) supports egl window and headless rendering?

**Comment by mwestphal** [comment]
It currently does not but once https://github.com/f3d-app/f3d/pull/1620 is merged it should!

**Comment by mwestphal** [comment]
This was adressed by https://github.com/f3d-app/f3d/pull/1631, however our nightly binary is not uploading for unrelated reasons, so you will need to wait a bit more
