### ISSUE TITLE
`--help` argument priority

### ISSUE THREAD

**Issue by snoyer** [f3d-app/f3d#1636]
**Issue**
Running `f3d foo.bar --upp=y -h` exits after printing the suggestion to correct the option typo and does not show the help message.

The arguments (`--help`, `--version`, ...) that output a message and exit early instead of starting the F3D GUI should be checked and handled first.

**Suggested fix**

In F3DOptionTools.cxx, invert the order to check for unknow options and F3DExNoProcess options.

**Comment by brown-eric** [comment]
Hey! I'm new to this, how could I help with this issue?

**Comment by mwestphal** [comment]
Hey @brown-eric , could you come to our discord ? I'll be happy to mentor you :)

**Comment by mwestphal** [comment]
https://discord.f3d.com

**Comment by SlayerPower** [comment]
omg bro eres el mejor jaja, nose pe como que s chakali, o algo pe, pues "maanna taamaanngilanga"
 literalmente lo que dice alli, igual gracias por el trabjao

**Comment by mwestphal** [comment]
> omg bro eres el mejor jaja, nose pe como que s chakali, o algo pe, pues "maanna taamaanngilanga" literalmente lo que dice alli, igual gracias por el trabjao

@SlayerPower this is an english speaking repository.

**Comment by snoyer** [comment]
fixed by #1644, thanks @brown-eric!
