### ISSUE TITLE
I would like to become a sponsor to f3d and f3d-app

### ISSUE THREAD

**Issue by drtrigon** [f3d-app/f3d#1659]
I would like to become a sponsor, but dislike to have to give my bank information to github.

Could you please share an bank account (IBAN, etc.) in order to issue a bank transfer?

Thanks in advance and greetings

**Comment by mwestphal** [comment]
Hi @drtrigon 

Thanks a lot!

We are planning to add more sponsor platform like patreon, tipeee and such.
Would that work for you ? Any specific platform you have in mind ?

More info here: https://github.com/f3d-app/f3d/issues/1262

Best,

**Comment by drtrigon** [comment]
Ad requested just give me an IBAN to send money to yout bank account please. That would be most simple to me.

Thanks in advance!


Am 7. Oktober 2024 13:18:49 MESZ schrieb Mathieu Westphal ***@***.***>:

**Comment by mwestphal** [comment]
Here it is, thanks a lot @drtrigon !

IBAN : FR76 1009 6180 0200 0768 2290 278

**Comment by mwestphal** [comment]
I've received it, thanks a lot!

**Comment by mwestphal** [comment]
Do not hesitate to join the discord if you want to have access to the VIP room.

**Comment by mwestphal** [comment]
I will also acknowledge your contribution in the next release. I sadly cannot add you as a "sponsor" in the github sponsor list as I have no control over that.
