### ISSUE TITLE
https://f3d.app/web not work

### ISSUE THREAD

**Issue by Mannshoch** [f3d-app/f3d#1665]
**Describe the bug**
I downloaded the [example files](https://drive.google.com/file/d/1hYGAHr67T7tBrUKFrCF_uc_jnvJaQF-A/view?usp=sharing)
Tested the linked viewer https://f3d.app/web/

**To Reproduce**
 1. Open the website https://f3d.app/web/
 2. Open
 3. Choose `DamagedHelmet.glb` or any other supported files
 4. nothing happens
 5. press F12
```
Loading failed for the <script> with the source "https://f3d.app/web/f3d.js". web:87:47
Uncaught ReferenceError: f3d is not defined
    <anonymous> https://f3d.app/web/:117
```

**Expected behavior**
See the files 

**System Information:**
 - OS: Ubuntu 24.04 
 - GPU and GPU driver: VM-Ware
 - Browser: Firefox

**Comment by Meakk** [comment]
Indeed, I reproduce.  
Thanks for reporting, we'll take a look.

**Comment by Meakk** [comment]
Here's the error: https://github.com/f3d-app/f3d/actions/runs/11271374639/job/31344070485#step:3:235  
```
/src/vtkext/private/module/vtkF3DGenericImporter.cxx:163:9: error: no member named 'ActorCollection' in 'vtkF3DGenericImporter'
  163 |   this->ActorCollection->AddItem(this->Pimpl->GeometryActor);
      |   ~~~~  ^
1 error generated.
```

I think the wasm Docker image needs a VTK update. The CI job is passing even if there is a compilation error, which should not happen.

**Comment by Meakk** [comment]
It's now fixed but the grid is not working for some reason. This needs more investigation.

**Comment by Meakk** [comment]
Grid fix: https://github.com/f3d-app/f3d/pull/1667
