### ISSUE TITLE
Thumbnailer tries to use X11 and crashes (GNOME)

### ISSUE THREAD

**Issue by hadess** [f3d-app/f3d#1674]
Using `f3d-2.5.0-1.fc40.x86_64`

GNOME, [since at least 2017](https://www.hadess.net/2017/07/security-for-security-gods-sandboxing.html), sandboxes thumbnailers without any network access, including X11 access which f3d seems to require, as it's always crashing on the first XSync() call.

```
Stack trace of thread 2:
#0  0x00007f2c357052a2 XSync (libX11.so.6 + 0x4a2a2)
#1  0x00007f2c37ff4424 _ZN26vtkXRenderWindowInteractor10InitializeEv (libvtkRenderingUI.so.1 + 0x14424)
#2  0x00007f2c39fe6683 _ZN3f3d6engineC1ENS_6window4TypeE (libf3d.so.2 + 0x4b683)
#3  0x000055ee4cf39d7d _ZSt11make_uniqueIN3f3d6engineEJNS0_6window4TypeEEENSt8__detail9_MakeUniqIT_E15__single_objectEDpOT0_ (f3d + 0x50d7d)
#4  0x000055ee4cf40b3d _ZN10F3DStarter5StartEiPPc (f3d + 0x57b3d)
#5  0x000055ee4cf03232 main (f3d + 0x1a232)
#6  0x00007f2c39a39088 __libc_start_call_main (libc.so.6 + 0x2a088)
#7  0x00007f2c39a3914b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
#8  0x000055ee4cf038a5 _start (f3d + 0x1a8a5)

Stack trace of thread 3:
#0  0x00007f2c39af2c13 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xe3c13)
#1  0x00007f2c39afec47 __nanosleep (libc.so.6 + 0xefc47)
#2  0x000055ee4cf358e0 _ZL12_dmon_threadPv.lto_priv.0 (f3d + 0x4c8e0)
#3  0x00007f2c39aa66d7 start_thread (libc.so.6 + 0x976d7)
```

**Comment by mwestphal** [comment]
Indeed, with the standard release, xorg server is needed.

Use the headless version instead: https://github.com/f3d-app/f3d/releases/tag/v2.5.0

See the complete discussion here: https://github.com/f3d-app/f3d/issues/439

Please note that this should change in the future, with F3D 3.0 release, there will be a single release that will support headless and non-headless mode

**Comment by hadess** [comment]
Right, that's a packaging bug then, thanks!

**Comment by mwestphal** [comment]
Please note F3D now supports headless and non-headless in the same release assuming VTK 9.4.0 is used.
You can use the nightly release to do that right away: https://github.com/f3d-app/f3d/releases/tag/nightly
