### ISSUE TITLE
Add a `--command-script` CLI option

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1694]
**Is your feature request related to a problem? Please describe.**
libf3d has a command API to to trigger behavior based on a string, lets add a CLI option to provide a script containing commands in a file.

**Describe the solution you'd like**
 - Add a CLI option in F3DOptionsTools:  `--command-script`
 - in F3DStarter.cxx, process the provided file and use `interactor::triggerCommand` to trigger the commands
 - Add testing and documentation

**Comment by mwestphal** [comment]
Yes, it is open! I've just assigned it to you.

**Comment by mwestphal** [comment]
Do not hesitate to join our discourse for guidance: https://discord.f3d.app

**Comment by mwestphal** [comment]
Hi @amannages 

Do you need any help moving forward ?

**Comment by amannages** [comment]
Hello @mwestphal 

Thank you for reaching out, for now since I am just beginning to work on this issue, I do not yet require any help to move forward, but I'll be sure to reach out through the discord if/when I need help.

**Comment by mwestphal** [comment]
Great! Do not hesitate :)

**Comment by mwestphal** [comment]
Hi @amannages

Do you need any help moving forward ?

**Comment by Meakk** [comment]
@mwestphal this is fixed right?

**Comment by mwestphal** [comment]
indeed!
