### ISSUE TITLE
Update documentation about headless version for thumbnails

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1698]
**Is your feature request related to a problem? Please describe.**
The documentation refers to a headless version, however, since https://github.com/f3d-app/f3d-superbuild/pull/204 has been merged, there is no specific headless version.

**Describe the solution you'd like**
The doc should be updated :
 - Remove the limitations, its not a limitation anymore
 - In desktop_integration, mention that sandbox is supported and that it may be required to add a `--rendering-backend` option in the thumbnail config

**Comment by Aarav-07** [comment]
is this issue solved??

**Comment by mwestphal** [comment]
Sure

**Comment by Aarav-07** [comment]
please check the pr once if its okay or not

**Comment by mwestphal** [comment]
fixed by https://github.com/f3d-app/f3d/pull/1703
