### ISSUE TITLE
Minimal screenshot interaction bind "F11" should be moved to "CTRL+F12"

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#1715]
**Describe the bug**
It is possible to take a minimal screenshot in F3D using `F11`, however this was due to a limitation of the key bindings mechanism, this was fixed recently, lets move it to "CTRL+F12".

**Comment by samoncrief** [comment]
Could you assign this to me? I think I see where to make the change.

**Comment by samoncrief** [comment]
https://github.com/f3d-app/f3d/pull/1759
PR for this issue

**Comment by mwestphal** [comment]
Fixed in #1759
