### ISSUE TITLE
Implements a file dialog command

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1737]
**Describe the bug**
Create a new command triggering a file dialog open to pick up a file.  
A binding to CTRL+O seems appropriate.

We can rely on `tinyfiledialogs` for that.

**Comment by hant-hub** [comment]
Hey, I'm working on this on my own as a first time contributor. Is there any documentation on how f3d integrates dependencies and external code? The coding style guide doesn't really have the answers I'm looking for. It looks like the previous dependent code uses installed packages but tinyfiledialogs does not have a package to install and it seems the preferred usage is directly compiling with the source.

**Comment by Meakk** [comment]
We have a few small dependencies in `external`

**Comment by mwestphal** [comment]
@hant-hub please note this issue is quite propective, we are not sure that `tinyfiledialogs` is the right choice, but maybe it is :). The idea is to first investigate how it would look.

You may want to join our discord to discuss the results :)

https://discord.f3d.app

**Comment by mwestphal** [comment]
Implemented in #1751
