### ISSUE TITLE
gltf animation

### ISSUE THREAD

**Issue by zengzhengrong** [f3d-app/f3d#1754]
Importing GLTF models uses VTK, so how do you load the built-in animations? How do you start the animations with vtkGLTFImporter?

**Comment by Meakk** [comment]
You can use [vtkImporter::UpdateTimeStep()](https://vtk.org/doc/nightly/html/classvtkImporter.html#a3a736c2cd1f7b483c78ae19ef78a2a43)  

Do you have any issue with F3D or is it a VTK question?

**Comment by mwestphal** [comment]
Hi @zengzhengrong 

Such questions are more adapted either to  our discord (https://discord.f3d.app) or to VTK discourse (https://discource.vtk.org)
