### ISSUE TITLE
Help: options must be a string, a boolean or a number

### ISSUE THREAD

**Issue by philberndt** [f3d-app/f3d#1758]
F3D log window tells me that

> options must be a string, a boolean or a number

This is my extremely simple json file.

```
[
  {
    "options": {
      "anti-aliasing": true,
      "raytracing": true,
      "samples": 10,
      "denoise": true,
      "hdri-ambient": true,
      "hdri-skybox": true,
      "tone-mapping": true,
      "hdri-file": "image.hdr",
      "ambient-occlusion": true,
      "grid": false,
      "filename": false
    }
  }
]
```

What am I missing here? Any help is greatly appreciated.

**Comment by mwestphal** [comment]
The doc in https://f3d.app is for current master, not for 2.5.0 sadly (see this: https://github.com/f3d-app/f3d/issues/845)

For the 2.5.0 doc that should help you, see this: https://github.com/f3d-app/f3d/blob/v2.5.0/doc/user/CONFIGURATION_FILE.md

In any case, what you want is probably:

```
  {
    "global": {
      "anti-aliasing": true,
      "raytracing": true,
      "samples": 10,
      "denoise": true,
      "hdri-ambient": true,
      "hdri-skybox": true,
      "tone-mapping": true,
      "hdri-file": "image.hdr",
      "ambient-occlusion": true,
      "grid": false,
      "filename": false
    }
  }
  ```

**Comment by philberndt** [comment]
> The doc in https://f3d.app is for current master, not for 2.5.0 sadly (see this: #845)
> 
> For the 2.5.0 doc that should help you, see this: https://github.com/f3d-app/f3d/blob/v2.5.0/doc/user/CONFIGURATION_FILE.md
> 
> In any case, what you want is probably:
> 
> ```
>   {
>     "global": {
>       "anti-aliasing": true,
>       "raytracing": true,
>       "samples": 10,
>       "denoise": true,
>       "hdri-ambient": true,
>       "hdri-skybox": true,
>       "tone-mapping": true,
>       "hdri-file": "image.hdr",
>       "ambient-occlusion": true,
>       "grid": false,
>       "filename": false
>     }
>   }
> ```

Thanks! Issue solved, closing. ⚡
