### ISSUE TITLE
how to use in .net WPF?

### ISSUE THREAD

**Issue by xzbaijj** [f3d-app/f3d#1784]
how to use in .net WPF?

**Comment by mwestphal** [comment]
F3D is not a .net application, what do you have in mind exactly ?

**Comment by xzbaijj** [comment]
> F3D is not a .net application, what do you have in mind exactly ?

yes, For example, the same as java

**Comment by mwestphal** [comment]
Please join our discord if you want to ask questions: https://discord.f3d.app
