### ISSUE TITLE
The window. trackball navigation and the camera asset when the next asset is loaded

### ISSUE THREAD

**Issue by gerroon** [f3d-app/f3d#182]
**Describe the bug**
Going through the loaded assets resets the window size and the camera. Please see the video below  for both issues.

**To Reproduce**
 1. Load a bunch of .FBX files
 2. Resize the window
 3. Rotate the viewport
 4. Enable the trackball method
 5. Load the next asset with the arrow key.

**Expected behavior**
It should not reset the window placement/sizing and the camera with each asset 

**System Information:**
 - OS: Windows 10

**F3D Information**
Paste the content of `f3d --version`:
This command does not print anything on Windows.

`V1.2.1`

https://user-images.githubusercontent.com/8519469/147856588-2b24ec3c-51a8-48c7-8034-2edcf5f769c9.mp4

**Comment by mwestphal** [comment]
this is the expected behavior, but we have a feature request to add an option that correspond to the behavior you want: #130

**Comment by gerroon** [comment]
> this is the expected behavior, but we have a feature request to add an option that correspond to the behavior you want: #130
> 
> Let us know what you think.

Thanks, it would be nice to be able to have an option to not to reset these parameters.

**Comment by mwestphal** [comment]
ok, I'm going to close this one then.
