### ISSUE TITLE
glTF lights support

### ISSUE THREAD

**Issue by SamuelTS** [f3d-app/f3d#184]
Hello, does F3D support [glTF Khronos Lights Punctual extension](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_lights_punctual)?

I would like to set a directional light in glTF input file to benefit sun light and shadow in F3D.

**Comment by Meakk** [comment]
Hi @SamuelTS  
Yes, F3D supports Khronos punctual lights extension.  
However, shadows are only supported with the raytracing backend (press `R` or specify `--raytracing` if your version of F3D have the raytracing module enabled)

**Comment by Meakk** [comment]
Issue related to shadows: https://github.com/f3d-app/f3d/issues/13

**Comment by SamuelTS** [comment]
Super! 🙂 By the way, does F3D other glTF extensions? IOR for example?

**Comment by Meakk** [comment]
Only `KHR_lights_punctual` and `KHR_materials_unlit` right now, but `KHR_materials_ior` and `KHR_materials_clearcoat` should be easy to implement.  
I'd like to add `KHR_draco_mesh_compression` support too soon.

**Comment by SamuelTS** [comment]
Ok. Thank you!
