### ISSUE TITLE
Interact with F3D using HTTP requests

### ISSUE THREAD

**Issue by SamuelTallet** [f3d-app/f3d#185]
It would be great to have a way to send commands to F3D window using HTTP.

For example:

1. Third-party modeler runs once F3D in server mode. F3D includes a local HTTP server listening on a configurable port.
2. Modeler exports model to file then opens a F3D window to load this file.
3. Modeler updates input file.
4. Modeler calls F3D server with HTTP request `/getCamera`. JSON response (position, focal point, etc.) is saved on the disk by the modeler.
5. Modeler notifies F3D that a file reload is necessary with HTTP request `/reloadInput`.
6. Modeler closes then reopens F3D window during another modeling session.
7. Modeler restores F3D camera with HTTP request `/setCamera` and JSON payload previously saved.

**Comment by mwestphal** [comment]
This may be possible once we adress #52

**Comment by SamuelTallet** [comment]
I now think it'll better to directly call F3D DLL. This way, F3D stays light w/o too much dependencies.
