### ISSUE TITLE
Can f3d work in docker?

### ISSUE THREAD

**Issue by xzhub** [f3d-app/f3d#210]
**Describe the bug**
I tried to build a f3d docker to run f3d under command line. I can only get it output help message. When run f3d with real glb model, I see "segmentation fault"

**To Reproduce**
```
docker build -t glb2video .
wget https://github.com/f3d-app/f3d/raw/master/testing/data/WaterBottle.glb
docker run -i -v $PWD:/data -w /data glb2video f3d --help # now we can see the output

# this command gives no output
docker run -i -v $PWD:/data -w /data glb2video f3d --input WaterBottle.glb --output wb.png --dry-run

# run these to see 'segmentation fault'
docker run -it -v $PWD:/data -w /data glb2video bash
root@0056f6fba11c:/data# f3d --input WaterBottle.glb --output wb.png --dry-run
Segmentation fault
```

Dockerfile(I tried 3 different base images, none of them works):

```
#FROM python:3.9.9-slim-buster
#FROM ubuntu:18.04
FROM nvidia/opengl:1.2-glvnd-devel-ubuntu18.04
COPY f3d-1.2.1-Linux.deb /
RUN (dpkg -i /f3d-1.2.1-Linux.deb || true ) && apt-get update && apt-get install -y -f && dpkg -i /f3d-1.2.1-Linux.deb && rm -f /f3d-1.2.1-Linux.deb
```

**Comment by mwestphal** [comment]
> Can f3d work in docker

Yes, you can take a look at our CI which is running in docker.

> docker build -t glb2video .

What is glb2video ? Can you run glxinfo ?

**Comment by xzhub** [comment]
glb2video is the docker name that I generate by command :

```
docker build -t glb2video .

```

**Comment by xzhub** [comment]
$ docker run -it glb2video bash
root@425471d1d3af:/# glxinfo
bash: glxinfo: command not found
root@425471d1d3af:/# f3d
Segmentation fault

**Comment by mwestphal** [comment]
> glb2video is the docker name that I generate 

Ok

> Can f3d work in docker

Yes, but you need a Xorg server running, either inside or outside docker with a passthrough

> glxinfo

You need to install it of course, from mesa-utils package.

But what are you trying to achieve here ? Why are you using docker ?

**Comment by xzhub** [comment]
I am trying to run it in amazon lambda service, or a headless ec2 server to generate preview picture or video of a given GLB file. I think docker might be the best way to achieve this goal. 

Can I run it in headless server?

**Comment by xzhub** [comment]
And I found f3d can't run on Windows server 2016. The error log windows flashed but I can't see what it says, before it closed automatically. That's why I finally switched to docker and hope Linux can resolve this issue.

**Comment by SamuelTallet** [comment]
> f3d can't run on Windows server 2016. The error log windows flashed but I can't see what it says, before it closed automatically.
@xzhub

To debug, run `f3d.exe --input WaterBottle.glb --output wb.png --dry-run > f3d_error.log 2>&1` then inspect `f3d_error.log`.

**Comment by xzhub** [comment]
> 
> Yes, but you need a Xorg server running, either inside or outside docker with a passthrough
> 

@mwestphal Thanks, I run f3d inside xvfb-run, and now I can get the result.

Dockerfile:
```
FROM ubuntu:18.04
COPY f3d-1.2.1-Linux.deb /
RUN (dpkg -i /f3d-1.2.1-Linux.deb || true ) && apt-get update && apt-get install -y -f && dpkg -i /f3d-1.2.1-Linux.deb && rm -f /f3d-1.2.1-Linux.deb
RUN apt-get install -y wget xvfb
```

command:
```
docker run -it -v $PWD:/data -w /data glb2video bash
xvfb-run -a --server-args="-screen 0, 1280x720x24" f3d --input WaterBottle.glb --output w.png --dry-run
```

**Comment by xzhub** [comment]
> > f3d can't run on Windows server 2016. The error log windows flashed but I can't see what it says, before it closed automatically.
> > @xzhub
> 
> To debug, run `f3d.exe --input WaterBottle.glb --output wb.png --dry-run > f3d_error.log 2>&1` then inspect `f3d_error.log`.

I'll find out what the error message is, then probably open another issue.

**Comment by mwestphal** [comment]
> Thanks, I run f3d inside xvfb-run, and now I can get the result.

Great

**Comment by Meakk** [comment]
@mwestphal this is probably something we need to document.

**Comment by mwestphal** [comment]
The usage of xvfb-run ? I'm not sure, this is a very generic usecase for any Xorg application.

**Comment by mwestphal** [comment]
Please note F3D now support headless and non-headless in a single version, you can try the last nightly for that: https://github.com/f3d-app/f3d/releases/tag/nightly
