### ISSUE TITLE
Failed to run in Windows Server 2016

### ISSUE THREAD

**Issue by xzhub** [f3d-app/f3d#213]
**Describe the bug**
f3d 1.2.1 crashes every time, with or without input file. 

**To Reproduce**
after install f3d, run these command to see the error:

```
user@EC2AMAZ-9D73J1O MINGW64 ~/Downloads
$ f3d --input WaterBottle.glb --output w.png --dry-run > f3d.log 2>&1
Segmentation fault

user@EC2AMAZ-9D73J1O MINGW64 ~/Downloads
$ cat f3d.log
ERROR: In D:\a\f3d\f3d\dependencies\vtk\Rendering\OpenGL2\vtkWin32OpenGLRenderWindow.cxx, line 680
vtkWin32OpenGLRenderWindow (000002D045EA90D0): failed to get wglChoosePixelFormatARB

ERROR: In D:\a\f3d\f3d\dependencies\vtk\Rendering\OpenGL2\vtkWin32OpenGLRenderWindow.cxx, line 758
vtkWin32OpenGLRenderWindow (000002D045EA90D0): failed to get valid pixel format.

ERROR: In D:\a\f3d\f3d\dependencies\vtk\Rendering\OpenGL2\vtkOpenGLRenderWindow.cxx, line 511
vtkWin32OpenGLRenderWindow (000002D045EA90D0): GLEW could not be initialized: Missing GL version
```

**System Information:**
 - OS: Windows Server 2016
 - GPU and GPU driver: NVIDIA T4 GPUs

**F3D Information**
Paste the content of `f3d --version`:

1.2.1

**Comment by mwestphal** [comment]
Windows Server is running headless and F3D needs a graphical server to render anything. You need to run a graphical server or to build VTK with OSMesa and build F3D against this VTK. This is not something that F3D dev team will fix imo. We would basically needs to provided a OSMesa specific binary, and this is outside of the scope of F3D I believe.

Wdyt @Meakk ?

**Comment by Meakk** [comment]
You have to find how to support OpenGL in Windows Server. It looks like it's possible: https://social.technet.microsoft.com/wiki/contents/articles/31771.server-2016-experience-guide-enabling-opengl-support-for-vgpu.aspx  
Alternatively, you have to build VTK with OSMesa or EGL (I'm not sure it's possible on Windows though). But I agree with @mwestphal, I don't think we will provide headless binaries anytime soon.

**Comment by mwestphal** [comment]
Closing this then.

**Comment by xzhub** [comment]
I just read through the post of https://social.technet.microsoft.com/wiki/contents/articles/31771.server-2016-experience-guide-enabling-opengl-support-for-vgpu.aspx, but I couldn't find "Physical GPUs" under "HyperV Settings" of  "HyperV Manager".
I am using Amazon EC2 gd4n instance, which has a TESLA GPU driver and I am using the remote desktop, so this is not a headless server.

I understand it's not an easy task to get it up and run. I'll spend a little more time here, in case I can get it up and run I'll update it here.

**Comment by Meakk** [comment]
Have you tried the recommendation from the troubleshooting section?

> OpenGL applications like F3D can have issues when launched from a guest Windows because the access to the GPU is restricted. You can try to use a software implementation of OpenGL, called [Mesa](https://github.com/pal1000/mesa-dist-win/releases).
> 
> - Download the latest release-msvc.
> - copy x64/OpenGL32.dll and x64/libglapi.dll in the same folder as f3d.exe.
> - set the environment variable MESA_GL_VERSION_OVERRIDE to 4.5.
> - run f3d.exe.

**Comment by xzhub** [comment]
@Meakk in this AWS g4dn ec2 server, most of the desktop software can use the TESLA GPU without any issue. So I think there should be no restriction of using the GPU card. Also if I install Mesa, does it mean I can only use CPU for rendering? The speed should be very slow considering I am trying to rendering every angle of the model then generate a video of the model.

**Comment by xzhub** [comment]
I'd like to report that after using Mesa, f3d runs without any problem. However, besides the two mentioned DLL file, I have to copy another one `libgallium_wgl.dll` as well to make f3d run. So according to my experience, these 3 are required:
```
x64/OpenGL32.dll
x64/libglapi.dll
x64/libgallium_wgl.dll
```

**Comment by Meakk** [comment]
Yes, indeed, the rendering will be slower, so consider it's only a workaround.  
If you manage to use hardware rendering in the future, please document it in this issue page. Thanks!
