### ISSUE TITLE
Partial scene reload

### ISSUE THREAD

**Issue by SamuelTallet** [f3d-app/f3d#216]
In an iterative process, I would need a partial reload of the scene. Let's say:

1. In a third-party modeler, I have a scene composed of three actors:
- A sun (directional light)
- A hill (mesh and materials)
- A tree (mesh and materials)
2. Modeler exports them as three files: "sun.gltf", "hill.gltf" and "tree.gltf".
3. Modeler asks F3D to render these three files in same 3D space. #127
4. I change sun position in modeler to test another light setup.
5. Modeler exports and overwrites only "sun.gltf" file.
6. Modeler asks F3D to reload only sun in real time. Hill and tree are lit differently. ~~#86~~ #52
7. Repeat :)

**Comment by mwestphal** [comment]
Interesting but indeed not possible until #127 and #86 are adressed

**Comment by SamuelTallet** [comment]
Changed my mind: I now put my hope in F3D API #52 for reload step.

**Comment by SamuelTallet** [comment]
I switched to a 3D renderer with built-in sun light. It's easier for me 😅

**Comment by mwestphal** [comment]
Do you mean you are not using F3D anymore 💔 ?

Just kidding, let us know if you see features in other software you feel like should be in F3D.

**Comment by SamuelTallet** [comment]
F3D is a very good viewer 😉 but I need a renderer with ray tracing out-of-the-box...
I know it's possible to get rays with F3D but compilation seems hard/long for now #9
And hybrid rendering (rasteriser/ray tracer) better fits my real-time ligthning needs.

A scene descriptor (*.f3d?) could solve current issue.

**Comment by mwestphal** [comment]
Yeah, #9 should be solved.

> A scene descriptor (*.f3d?) could solve current issue.

This is what .gltf files are for.
