### ISSUE TITLE
When render with hdr background and '-u' , the background could be stretched (wrong x/y ratio)

### ISSUE THREAD

**Issue by xzhub** [f3d-app/f3d#217]
**Describe the bug**
When render with hdr skybox photo, and using different x/y for the output picture, we can see the background is stretched.

First, the pictures without -u, I don't see obvious issues, background picture looks fine.
1200x1200:
![1200x1200](https://user-images.githubusercontent.com/3990687/150414553-76eb4572-63df-4296-bc05-a957ae2881c2.png)

2400x1200:
![2400x1200](https://user-images.githubusercontent.com/3990687/150414570-02bb3260-5969-4355-a783-acea8b6f6ccf.png)

However, after turn on background blur, the second one looks wrong (the light shape is oval):
1200x1200 with -u:
![1200x1200u](https://user-images.githubusercontent.com/3990687/150414881-a005539a-2aa4-433b-9db4-094f5d5dbf04.png)

2400x1200 with -u:
![2400x1200u](https://user-images.githubusercontent.com/3990687/150414908-eab241b0-ebe5-420f-bc19-d4210fb389ed.png)

 
**To Reproduce**

```
f3d --input WaterBottle.glb --output 2400x1200u.png --camera-position=0.584518,0.0,0.0 -u -t --hdri christmas.hdr --resolution=2400,1200 --dry-run
```
background img: 
[christmas.hdr.zip](https://github.com/f3d-app/f3d/files/7908256/christmas.hdr.zip)

**Expected behavior**

background should look similar with different resolution

**System Information:**
 - OS: Linux 
 - GPU and GPU driver: None

**F3D Information**
Paste the content of `f3d --version`:

1.2.1

**Comment by Meakk** [comment]
Thanks for reporting the issue, it's now fixed in the master branch.

**Comment by xzhub** [comment]
That was fast, thank you! When should I expect to see the new release installer? Might try to build it on my own, but it feels difficult.

**Comment by xzhub** [comment]
Inside a debian buster docker, I got error like this. How to resolve this issue?
```
wget https://www.vtk.org/files/release/9.1/VTK-9.1.0.tar.gz
wget https://github.com/f3d-app/f3d/archive/refs/heads/master.zip
unzip master.zip
tar zxf VTK-9.1.0.tar.gz

apt-get install -y cmake mesa-common-dev mesa-utils freeglut3-dev ninja-build g++
cd VTK-9.1.0
mkdir build
cd build/
cmake ..

cd ../../f3d-master/
VTK_DIR=../VTK-9.1.0/build/ cmake .
make
```

error:
```
make[2]: *** No rule to make target '/data/VTK/VTK-9.1.0/build/lib/libvtkInteractionWidgets-9.1.so.9.1.0', needed by 'src/library/libf3d.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:114: src/library/CMakeFiles/libf3d.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by Meakk** [comment]
> # maybe I should run make here, but it runs super slow... will see if this could resolve the issue.

Yes, you have to build VTK. You can use `make -j N` to build in parallel. Depending on your machine, it takes ~20 minutes.

**Comment by mwestphal** [comment]
You can also directly download the binary: 
https://drive.google.com/file/d/1YaWJAijh_MA4HA27g0QsJny3X9jIRtII/view?usp=sharing

**Comment by xzhub** [comment]
Thank you so much @mwestphal! 
On my macbook, the build of VTK only progressed 60% overnight.

**Comment by mwestphal** [comment]
I sent you the linux version, let me know if you want the MacOS or Windows version.

**Comment by xzhub** [comment]
@mwestphal Linux version is all I need. The deb file you provided working perfect :)
![new2400x1200u](https://user-images.githubusercontent.com/3990687/150574396-4cd24b21-b603-4169-915d-b5c3ea305e42.png)
