### ISSUE TITLE
[General] Can I get this background hdr image?

### ISSUE THREAD

**Issue by xzhub** [f3d-app/f3d#219]
I like this background very much, can I get a free copy? Thanks
![image](https://user-images.githubusercontent.com/3990687/150602835-f877d239-1dc9-4f62-beea-c4b7f9e80745.png)

**Comment by mwestphal** [comment]
It is documented on the gallery page:
https://f3d-app.github.io/f3d/gallery/

Venice Sunset HDRI by Greg Zaal

https://polyhaven.com/a/venice_sunset

**Comment by xzhub** [comment]
Thanks! Didn't realize there is a homepage and the gallery. They look great!
