### ISSUE TITLE
f3d help is broken on Windows

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#223]
**Describe the bug**

`f3d --help` on Git bash on Windows is displaying the key bindings weirdly.

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/6069752/151397397-176b01bc-9a08-4f13-abe1-3d251c764453.png">

**To Reproduce**
 1. Launch a git bash terminal on Windows
 2. Run `f3d --help`

**System Information:**
 - OS: Windows
 - GPU and GPU driver: RTX 2070

**F3D Information**
Paste the content of `f3d --version`:
```
f3d 1.2.1

F3D - A fast and minimalist 3D viewer
Version: 1.2.1
Build date: 2021-12-13 23:27:00
System: Windows-10.0.17763 AMD64
Compiler: MSVC 19.29.30137.0
RayTracing module: OFF
Exodus module: ON
OpenCASCADE module: 7.6.0 (no metadata)
Assimp module: 5.1.0
VTK version: 9.1.20211124 (build 20211124)

Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
Written by Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

```

**Comment by Meakk** [comment]
yes

**Comment by Meakk** [comment]
in the windows terminal, nothing is displayed in the terminal, only in the output window.

**Comment by mwestphal** [comment]
seems to be fixed on master.
