### ISSUE TITLE
Thumbnailer on Debian only works for stl files (and uses weird angles)

### ISSUE THREAD

**Issue by Auravendill** [f3d-app/f3d#227]
**Describe the bug**
I installed f3d, because it seemed to offer exactly what I needed: A way to view and preview obj files. But I discovered, that while obj files can be opened without issue, their thumbnails do net get generated. So only stl thumbnails seem to be actually generated (and I tbh I had a tool for that already)

**To Reproduce**
 1. Install f3d for Debian 11 from the OpenSuse page 
 2. Reboot
 3. look at stls working fine and obj being ignored

**Expected behavior**
All supported files should get thumbnails generated (and the angle from which they are rendered should be sensible)

**System Information:**
 - OS: Debian 11
 - GPU and GPU driver: AMD RX 5700 XT

**F3D Information**
Paste the content of `f3d --version`:
f3d 1.2.1

F3D - A fast and minimalist 3D viewer
Version: 1.2.1
Build date: 2021-04-25 14:24:53
System: Linux x86_64
Compiler: GNU 10.2.1
RayTracing module: OFF
Exodus module: ON
OpenCASCADE module: OFF
Assimp module: OFF
VTK version: 9.0.1 (build 1)

Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
Written by Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Additional context**
While stls do work, they just don't look quite right either:
The stl thumbnails get generated from straight above, which in most cases is quite bad.  E.g. an owl from above in white on black isn't much more than a blob... The black background instead of no background (like with stl-thumb) also looks outdated.

**Comment by mwestphal** [comment]
See this guide to diagnose the issue. Thumbnails are a bit finicky.
https://github.com/f3d-app/f3d#linux-1

Since .stl thumbnails are "working", this is probably a mimetype issue, so you probably need to update your mimetypes with a command like:

```
sudo update-mime-database ~/.local/share/mime/
```
or

```
sudo update-mime-database /usr/share/mime
```

But make of the location of the mime type files installed by your package manager. 

As for the looks of the stl thumbnails, we had to make a choice for the Y direction, but you can change it by modyfing the f3d.thumbnailer file in:

```
/usr/share/thumbnailers
```

And modify it as you see fit. This is not perfect, we hope to improve that in the future.

**Comment by shdbwa** [comment]
I got some wired issues, opening a folder with _.obj_ files
`kioslave5  :  kf.kio.slaves.thumbnail: Failed to load "obj-thumbnailer"`
I have _.stl_ preview, but no _.obj, .fbx_ preview

**Comment by mwestphal** [comment]
Never seen that, check the content of your `/usr/share/thumbnailers` @shdbwa ?

**Comment by Poikilos** [comment]
> Never seen that, what is the content of your `/usr/share/thumbnailers` [@shdbwa](https://github.com/shdbwa) ?

Thanks!

It has a bad angle (top view). So I added `--camera-azimuth-angle=0 --camera-elevation-angle=-45 --ambient-occlusion --tone-mapping --anti-aliasing` (extra options are slower but make the shape far more readable. Leave out --anti-aliasing if it is too slow for you) to f3d command in:
- /usr/share/thumbnailers/f3d-plugin-native.thumbnailer
- /usr/share/thumbnailers/f3d-plugin-assimp.thumbnailer
- Then clear files in ~/.cache/thumbnails

Player Character Pack 01 - Baseless by justinmiller87 on Thingiverse: https://www.thingiverse.com/thing:4156308

![Image](https://github.com/user-attachments/assets/1d40f45c-ff85-49b2-8e43-ed4da5381c30)

**Comment by mwestphal** [comment]
Thanks for the feedback @Poikilos , however I'm a bit confused how it relates to the issue at hand.

In any case, you may want to rely on configuration files instead of hard coded thumbnailers file.

**Comment by Poikilos** [comment]
ok, "and uses weird angles" is the part of this issue I'm commenting on primarily
- and threw in the other options since regardless of angle, you often can't tell what the model is without ambient occlusion, so I was nipping the next question in the bud (that problem is immediately apparent after fixing the angle).

**Comment by Poikilos** [comment]
More about weird angles here: https://github.com/f3d-app/f3d/issues/2063


> In any case, you may want to rely on configuration files instead of hard coded thumbnailers file.

I looked at the [Configuration File documentation](https://f3d.app/doc/user/CONFIGURATION_FILE.html) but putting this in ~/.config/f3d/config.json has no effect:

```json
[
  {
    "options": {
      "load-plugins": "assimp",
      "camera-azimuth-angle": 0,
      "camera-elevation-angle": -45,
      "ambient-occlusion": true,
      "tone-mapping": true,
      "anti-aliasing": true
    }
  }
]
```

**Comment by mwestphal** [comment]
Works fine here, please join the discord for interactive support :)

https://discord.f3d.app
