### ISSUE TITLE
Option to suppress log popup

### ISSUE THREAD

**Issue by RobbyMeeker** [f3d-app/f3d#229]
I have several models that have referenced materials that are missing (intended). This does not affect viewing the model, however f3d's log will not shut up about it, and keeps popping up every time I open one of these files. It is incredibly annoying.

It would be fantastic to have some kind of "-suppress" config option to ignore these errors on opening, to avoid this issue. Otherwise I will have to cleanup all of these files and it is just not feasible for my use case.

**Comment by RobbyMeeker** [comment]
> Have you tried the `--quiet` option?

Jesus, it was on the commands list the whole time! 

It works perfectly.
Thanks for the help, and apologies.

**Comment by mwestphal** [comment]
Thanks for using F3D @RobbyMeeker !
