### ISSUE TITLE
Custom window thumbnail option allow show thumbnail with wireframe

### ISSUE THREAD

**Issue by thesolitudeofnoblesoul** [f3d-app/f3d#254]
**Is your feature request related to a problem? Please describe.**
I have a lot model obj mesh file act as base with may kind of topology, poly budget, some quad and other tris only. They all construct different but have same shape/form.
The problem is that with thumbnail they all look the same. I must manual open each of them to see what kind of topology/budget they are.

**Describe the solution you'd like**
Current window thumbnail don't not allow custom. I would like to able have some option when generate windows thumbnail.
A field "thumbnail" option in file "config.json" or another config file name "thumbnail.json" in f3d folder would do the job.
But I think we can add more customize for generate thumbnail dependent on a file ".f3d" config in a ancestor folder. This technique would very well for programing custom tool. I think F3D can benefit greatly from it and make F3D become a standard for thumbnail viewer 3D files.

Thanks and regards!

**Comment by mwestphal** [comment]
we have been thinking of a config file dedicated thumbnails, so that would be a first step.

Your idea for a config file location in the folder containing the file is in interesting one, we need to think about it.

**Comment by mwestphal** [comment]
related to #300 and #349

**Comment by mwestphal** [comment]
Will be adressed by #399

**Comment by mwestphal** [comment]
@thesolitudeofnoblesoul , So there is now a dedicated thumbnail config file that you can edit for your needs. 
Actually, the thumbnailer will look for thumbnail.json in all standard place, so you can put your own in your userspace.

We have not implemented your .f3d idea. It could be implemented in the future if there is still a need for it, but it requires making some choice which may not be the right one without some feedbacks on the current implementation first.

Let me know what you think.

as far showing as Wireframe, wireframe is not supported by F3D yet, SurfaceWithEdges is though, but feel free to open an issue if needed.
