### ISSUE TITLE
Provide specialized version of the default config file

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#28]
Each community of users may want to have different default config file, especially regarding interaction style, up direction, coloring.

It would be nice to provide default config file for each of the basic usage of F3D, eg:
- 3D Printing
- Gamedev
- Animation
- Sciviz
- Medical

Ideally, for the NSIS windows installer, a dedicated screen would let the user choose the default config to install.

**Comment by mwestphal** [comment]
Will be possible once #399 is merged

**Comment by mwestphal** [comment]
So this is no trivial to implement. Should we do it or is it a bad idea @Meakk ?

**Comment by mwestphal** [comment]
to put in context of #374

**Comment by Meakk** [comment]
I think it's a good idea!

**Comment by mwestphal** [comment]
added medical to the list

**Comment by mwestphal** [comment]
I'm still unsure this is a very good idea as config files are proving already challenging to use for most users. moving back anyway

**Comment by mwestphal** [comment]
@Meakk I'm thinking of closing this one. What do you think ?

**Comment by mwestphal** [comment]
Closing this without feebdbacks
