### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by DuncanLithgow** [f3d-app/f3d#282]
**Is your feature request related to a problem? Please describe.**

It would be great if your license was standard. It looks like a 3 clause BSD so maybe you could just cal it that in the text? That makes it easier for people like me trying to maintain software lists to refer to the license.

https://wiki.osarch.org/index.php?title=AEC_Free_Software_directory

**Comment by mwestphal** [comment]
Hi @DuncanLithgow ,

Indeed, we are missing a section in the README.md specifying that we are using the 3 clause BSD. I'll add it soon.

**Comment by mwestphal** [comment]
Should be clearer now.
