### ISSUE TITLE
Consider installing system libraries

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#30]
We are currently building VTK and F3D using the static system library on Windows.  
Should we add `InstallRequiredSystemLibraries` CMake module in order to support the shared system library?

See https://cmake.org/cmake/help/latest/module/InstallRequiredSystemLibraries.html

**Comment by mwestphal** [comment]
https://gitlab.kitware.com/f3d/f3d/-/issues/200

**Comment by drtrigon** [comment]
Would that mean f3d needs to be installed and the zip release could not be provided anymore?

**Comment by mwestphal** [comment]
The binary will always be provided, this issue is more on the technical side about how the package will be generated.

**Comment by mwestphal** [comment]
Is this still a thing @Meakk ?

**Comment by mwestphal** [comment]
this is now handled by the https://github.com/f3d-app/f3d-superbuild
