### ISSUE TITLE
Generate thumbnail .jpg in same folder with a click

### ISSUE THREAD

**Issue by astandarduser** [f3d-app/f3d#302]
One other feature I thought of would be the ability to generate thumbnail .jpg in same folder with a click named the same as the original file, again it may be outside the scope but no other software does that easily. Very useful when transferring to another machine that doesn't have this software or external storage backups

**Comment by Meakk** [comment]
It's out of scope indeed.  
However, you can use f3d to do what you want. You can try something like this: https://superuser.com/questions/444726/windows-how-to-add-batch-script-action-to-right-click-menu  
In case you have something working, please post the reg file here, we can it to the documentation.

**Comment by Meakk** [comment]
Closing this issue. If you manage to make it work, please don't forget to post the script snippet here, it could be useful for other users.
