### ISSUE TITLE
vtkOBJImporter fails with a specific file

### ISSUE THREAD

**Issue by astandarduser** [f3d-app/f3d#303]
Attached is a problematic glb file and obj, although I find most obj's are ok and most glb's are problematic on my windows pc

[https://we.tl/t-FJARm55q1E](url)

**Comment by Meakk** [comment]
Your GLB file is using DRACO extension which is not supported yet. Related issue: https://github.com/f3d-app/f3d/issues/59  
The OBJ file looks good on my side:

![image](https://user-images.githubusercontent.com/6069752/170983369-9a706e64-49c6-4efe-9f5a-8c5f3e05ae4b.png)

**Comment by astandarduser** [comment]
Even the thumbnail of the obj loads ok? I am using windows 10, not sure if that would make a difference

**Comment by Meakk** [comment]
Indeed the thumbnail is weird

![image](https://user-images.githubusercontent.com/6069752/170984580-bf7c6795-a376-40ef-a764-48ea4dda3a61.png)

**Comment by Meakk** [comment]
Works fine with `--geometry-only` option. It's probably an issue with `vtkOBJImporter`

**Comment by Meakk** [comment]
[s1.zip](https://github.com/f3d-app/f3d/files/8798120/s1.zip)

Attaching the file here in case the WT link dies.

**Comment by mwestphal** [comment]
reproduced

**Comment by Meakk** [comment]
OBJ importer fixed here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9488

**Comment by Meakk** [comment]
Fixed in master

**Comment by mwestphal** [comment]
Here is a nightly version, containing the fix, if you want @astandarduser : 
[f3d-windows-latest-commit.zip](https://github.com/f3d-app/f3d/files/9390702/f3d-windows-latest-commit.zip)

**Comment by astandarduser** [comment]
> Here is a nightly version, containing the fix, if you want @astandarduser : [f3d-windows-latest-commit.zip](https://github.com/f3d-app/f3d/files/9390702/f3d-windows-latest-commit.zip)

obj works perfect now, the glb file does not but that's ok (I don't have that specific glb file so tested with another, I'll link it). Still good to get the new version to test so appreciate the upload. It imports into blender ok [https://we.tl/t-WTDsnh5rbB](url)

**Comment by mwestphal** [comment]
As stated be meak, the glb file is a different issue, tracked here: #59
