### ISSUE TITLE
No render for spider.fbx

### ISSUE THREAD

**Issue by p4paul** [f3d-app/f3d#327]
**Describe the bug**
Unable to view the spider.fbx (downloaded from https://free3d.com/3d-model/spider-257546.html)

**To Reproduce**
1. download https://free3d.com/3d-model/spider-257546.html
2. extract zip
3. use the command line to open the file `./f3d ~/Downloads/31-spider/spider.fbx`

**Expected behavior**
See the animated spider.  Other online viewers seem to be able to render the fbx image and we tested it with [three.js](https://threejs.org/editor/)
Perhaps the object is too big for the scene, or the camera is too close?

**System Information:**
 - OS: OS X 10.15.7
 - GPU and GPU driver: Radeon Pro 555X 4 GB / Intel UHD Graphics 630 1536 MB

**F3D Information**
f3d 1.2.1

F3D - A fast and minimalist 3D viewer
Version: 1.2.1
Build date: 2021-12-13 23:27:01
System: Darwin-19.6.0 x86_64
Compiler: AppleClang 12.0.0.12000032
RayTracing module: OFF
Exodus module: ON
OpenCASCADE module: 7.6.0 (no metadata)
Assimp module: 5.1.0
VTK version: 9.1.20211124 (build 20211124)

Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
Written by Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Comment by p4paul** [comment]
Thank you for confirming the issue.

**Comment by Meakk** [comment]
I'm closing it for now since it's a duplicate. But it's definitely a major issue we will try to fix soon.

**Comment by libing64** [comment]
`./f3d xxx/spider.fbx
xxx/spider.fbx is not a file of a supported file format`

**Comment by mwestphal** [comment]
Some data to test with:
[untitled.zip](https://github.com/f3d-app/f3d/files/10608526/untitled.zip)


stl: 
![stl](https://user-images.githubusercontent.com/3129530/216765950-94c96eb8-913f-4a9a-8bdd-e95bbf1940df.png)

glb:
![glb](https://user-images.githubusercontent.com/3129530/216765963-0af61694-0c03-4e4c-b426-f383b4700377.png)

dae:
![dae](https://user-images.githubusercontent.com/3129530/216765972-82fd09a7-7d9d-46e9-942a-28db79351667.png)

fbx:
![fbx](https://user-images.githubusercontent.com/3129530/216765978-74681071-20a7-4995-a6f2-93cea689a2a0.png)


So there seems to be an issue specific to fbx, and a more generic issue with importers in general
