### ISSUE TITLE
--texture-base-color with opacity and depth peeling is not correct

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#332]
**Describe the bug**
Using a texture base color with opacity and depth peeling, without setting --opacity, cause a wrong rendering

**To Reproduce**
 1. Open the file using `f3d --dry-run WaterBottle.glb --texture-base-color=/home/glow/f3d/src/testing/data/albedo_mod.png --depth-peeling --geometry-only` : 
![albedo_mod](https://user-images.githubusercontent.com/3129530/178157806-9a09988b-6a79-42d8-a65c-d80e3c20492e.png)

 2. wrong rendering:
 
![wrong](https://user-images.githubusercontent.com/3129530/178157876-66e97abd-58e6-423d-86c9-446e2db9128e.png)

 4. Using the following provide a correct rendering: `f3d --dry-run WaterBottle.glb --texture-base-color=/home/glow/f3d/src/testing/data/albedo_mod.png --depth-peeling --geometry-only --opacity=0`

**Expected behavior**
Correct translucent rendering, like this:
![right](https://user-images.githubusercontent.com/3129530/178157900-c082db41-1682-4a47-908a-c2d66ddce67d.png)

5. The --opacity parameter is not taken into account at all, apart from enabling translucentsy, it should multiply.

**Comment by Meakk** [comment]
Indeed. This texture is RGBA, with an alpha channel containing translucent pixels. But VTK isn't aware the object is translucent. My suggestion is to force the translucent flag on the actor if the color texture has 4 channels.

**Comment by mwestphal** [comment]
Sounds like a good approach

**Comment by mwestphal** [comment]
Looks like this should be set inside VTK, not in F3D.

**Comment by mwestphal** [comment]
Added a note a about the fact this is not multiplied.

**Comment by mwestphal** [comment]
See #333 for more info
