### ISSUE TITLE
Windows 11 Pro Help disappears

### ISSUE THREAD

**Issue by Pantarheon** [f3d-app/f3d#343]
Just installed v1.2.1 under Windows 11 Pro Build 22000, with a 2 TB drive C  (1.8TB free). Whenever I type **f3d -h**, a window pops up (presumably with some help information) and closes immediately, so I cannot see, let alone read, what it says.

**Comment by mwestphal** [comment]
Duplicate of https://github.com/f3d-app/f3d/issues/223, which is fixed in master

**Comment by mwestphal** [comment]
@Pantarheon let us know if you want to download a nightly, we can send link.

**Comment by Pantarheon** [comment]
Yes, that would be nice. Thank you.

**Comment by mwestphal** [comment]
https://we.tl/t-tvndA9RPrv

**Comment by Pantarheon** [comment]
Thank you. That one works. :)
