### ISSUE TITLE
`--line-width` and `--point-size` have no effect with the full scene

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#346]
**Describe the bug**
`--line-width` and `--point-size` have no effect with the full scene

`./bin/f3d ../src/testing/data/WaterBottle.glb --line-width=3 -e `

![full](https://user-images.githubusercontent.com/3129530/183092969-9133079a-29aa-4783-b67d-d6e99ab22830.png)

**Comment by Meakk** [comment]
Add line-width support in `vtkF3DRenderer::ShowEdge`
