### ISSUE TITLE
--scalar and --texture-base-color create stange artifacts

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#348]
**Describe the bug**
Using --scalar and --texture-base-color together create stange artifacts

**To Reproduce**
` ./bin/f3d ../src/testing/data/WaterBottle.glb --geometry-only --texture-base-color=../src/testing/data/red.jpg --scalars=TANGENT --output=a.png`

![a](https://user-images.githubusercontent.com/3129530/183093925-1d5ade65-216b-4f95-b636-e102101c5eb6.png)

It is not clear to me what should be expected, but something better than this, Im sure. To check against #347

**Comment by mwestphal** [comment]
@Meakk any insight on this one ?

**Comment by Meakk** [comment]
Using `--scalars=TANGENT` makes visualization of vector magnitude using the default color map (inferno). Then it's blended with the red texture.  
I'd say it's not a bug, it's the expected result. Can you check if the result is different with another color map? (something like 0=black to 1=white)

**Comment by mwestphal** [comment]
With red.jpg:

![a](https://github.com/f3d-app/f3d/assets/3129530/795384c7-1fa2-4cf4-8d9c-fc2f044233a1)


Without red.jpg:

![b](https://github.com/f3d-app/f3d/assets/3129530/950daf73-a9f3-48be-88ea-d6699c0f7ef0)


I agree it looks fine, closing.
