### ISSUE TITLE
Log should be behind model window by default (Windows)

### ISSUE THREAD

**Issue by astandarduser** [f3d-app/f3d#350]
Each time I open a model the log window is always directly covering the model window, not sure if it's possible currently but would be great to have it set behind the model window regardless of errors

**Comment by mwestphal** [comment]
Indeed, that would be nice. We will take a look if this is possible.

**Comment by astandarduser** [comment]
Deleted MTL's are probably a big reason, always end up deleting them

**Comment by astandarduser** [comment]
I know many artists do the same

**Comment by mwestphal** [comment]
What error do you have exactly ? Do you think F3D should avoid warning in that case ?

**Comment by astandarduser** [comment]
I'll get it for you tomorrow, it's always about missing mtls as I mentioned. It's worth keeping the warning so people know why their texture isn't missing but the logging window should still show up behind regardless, that's the case for all 3d software I have used

**Comment by astandarduser** [comment]
> What error do you have exactly ? Do you think F3D should avoid warning in that case ?

ERROR: In D:\a\f3d\f3d\dependencies\vtk\IO\Import\vtkOBJImporter.cxx, line 867
vtkOBJPolyDataProcessor (000002633F28DE60):  material 'lambert5SG' appears in OBJ but not MTL file?

**Comment by mwestphal** [comment]
Ok, I think this is a fair warning, you may want to edit your obj to avoid it. Anyway, we will take a look at putting the window behind.

**Comment by jiangsheng** [comment]
vtkF3DWin32OutputWindow::Initialize calls vtkWin32OutputWindow::Initialize() which calls ShowWindow(win, SW_SHOW); at the end. The ShowWindow call activates the vtkOutputWindow window and steals focus.

**Comment by mwestphal** [comment]
Thanks for the investigation! I will see of the right way to fix this in VTK.
