### ISSUE TITLE
Scenes are too dark

### ISSUE THREAD

**Issue by rafcon-dev** [f3d-app/f3d#352]
hi guys. For some reason I'm getting really dark scenes. For example, for this file:
https://downloadfree3d.com/3d-models/vehicles/ship/south-korean-destroyer-chung-mu/
This is what I get in the viewer:
![image](https://user-images.githubusercontent.com/85711398/183935071-aa1cf268-2a18-49a2-9c31-a48d4cc2029f.png)

and this is what I get in an online glTF viewer for example:
![image](https://user-images.githubusercontent.com/85711398/183935474-75dadbd9-d3fc-4af1-bdf2-ae5dec2780f2.png)

Similar thing happens with stl files for example, the image is just too dark and flat. Am I missing something?
I'm just running a simple commad with no options. I've tried --dry-run and a few more, nothing. Tried --geometry-only, and it renders without textures, but still too dark.

 - OS: Ubuntu 22.04.1 LTS
 - GPU and GPU driver: GTX 770 450.203.03
 - f3d --version`: 1.2.1

**Comment by Meakk** [comment]
It's a gltf file? You'll get best results using a HDRI file. You can also try to change the background color.

**Comment by rafcon-dev** [comment]
It's a .glb file.

Chaning background color doesn't seem to affect the lighting.
Adding a light grey hdr image indeed improved the lighting.
![image](https://user-images.githubusercontent.com/85711398/184186000-dbd1bc0d-c14d-4803-82de-543c4404879f.png)
Still, it's a bit too flat, a bit of directional lighting wouldn't hurt.
The thing is, for .obj files it becomes too washed out, so I have to use a different command for those than from glb/gltf. I'm  trying to generate previews for lf file manager.
I suppose this also happens with the thumbnails generated with f3d?
Still, for stls, the thumbnails are a bit flat, when compared with stl-thumbnailer, for example:
f3d result:
![image](https://user-images.githubusercontent.com/85711398/184188088-6b8f4486-2d5e-47f7-8f43-69dc19b00666.png)

stl-thumbnailer:
![image](https://user-images.githubusercontent.com/85711398/184187726-3da6ac56-daf4-4d9e-966b-854e0d1aed22.png)

So, 3 things:
* Probably glft and glb files could have a default light grey hdr applied for the thumbnailer
* Lighting in the default scene could be improved, a bit brighter and more directional
* default stl files orientation does not appear to be correct?

**Comment by Meakk** [comment]
- I don't want to add a special feature for a specific format, the default light setup should be used for all formats.
- There is no way to customize the punctual lights setup right now. This is something we'd like to add in the future though. In the short term, we could add a "light-intensity" option to increase the brightness of the default lights.  
- The orientation of the scene can be set using the --up option.  
- An option to hide the hdri in the background can be useful indeed. At least, the --no-background option should work with the --hdri option if it doesn't already.

**Comment by mwestphal** [comment]
This is fixed by #461 , set the light-intensity in your config files @rafcon-dev

**Comment by mwestphal** [comment]
This will be further improved with #944, where a default HDRI will be provided
