### ISSUE TITLE
Integration in QuickLook

### ISSUE THREAD

**Issue by Dragoy** [f3d-app/f3d#381]
Hi all, it would be cool to have an integration in the form of a plugin with [QuickLook ](https://github.com/QL-Win/QuickLook) file viewer. It's used to quickly browse files by pressing the space bar, just like in MacOS. [Here is the documentation for integration](https://github.com/QL-Win/QuickLook/wiki/Develop%2C-build-and-integrate). Just wondering if this integration is possible? 

Thank you for your reply.

**Comment by mwestphal** [comment]
This is a fairly similar request as the #55 about gnome sushi

**Comment by Dragoy** [comment]
Thanks for the clarification
