### ISSUE TITLE
Add a clear drop zone when not providing a filename to open

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#39]
## Actual Behavior

If no argument is provided, a rendering window is created with nothing shown (gray background). It can be difficult to know if the program is working or freezing.

## Expected Behavior

In case no argument is provided, we should expect that the program show a clear drop zone

## Specifications

    F3D - A fast and minimalist 3D viewer
    Version: 1.1.0
    Build date: 2021-04-07 11:48:28
    System: Linux-5.8.0-48-generic x86_64
    Compiler: GNU 10.2.0
    RayTracing module: OFF
    VTK version: 9.0.0 (build 20210406)
    Author: Kitware SAS

**Comment by mwestphal** [comment]
https://gitlab.kitware.com/f3d/f3d/-/issues/220

**Comment by jpouderoux** [comment]
In current code, the message `No file to load provided, please drop one into this window` is set as the file information string. In the past, it used to be displayed by default, but now it is not the case anymore. We could simply call `this->Renderer->ShowFilename();` at `F3DLoader.cxx:351` to fix this I guess.
OR we could do something more "complex" like drawing a centered drop rectangle with a similar message...

**Comment by mwestphal** [comment]
Still important but dropping a release

**Comment by mwestphal** [comment]
Here is a visual idea of what is expected:

![image](https://user-images.githubusercontent.com/3129530/192436884-886687cd-0e66-474f-a702-c38ee3367722.png)

The text should be simply: "Please drop a file into this window".

The dotted rectangle should ideally scale with the window (like 70%) but not critical if it does not.

**Comment by mwestphal** [comment]
It would be nice to add somewhere to press `H` to show the cheatsheet, as suggested by #774

**Comment by mwestphal** [comment]
done in #827
