### ISSUE TITLE
Native window position is not set

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#410]
**Describe the bug**

The default position of native windows is defined in VTK, and seems to be:
- 50,50 for Cocoa
- 0,0 for Windows and Linux (to confirm)

Moreover, Y=0 corresponds to the bottom of the screen for Cocoa, so the Y position must be reworked in VTK to flip it using the height of the screen.

Also, maybe a `setPosition` public API could be useful.

**Comment by Meakk** [comment]
Related: #409

**Comment by mwestphal** [comment]
Linux:
 - Awesome (floating) : Window is **not** positioned correctly, half of it is below the screen
 - Xfce: Window is positioned perfectly, top left, without hiding the "Xfce bar"

**Comment by mwestphal** [comment]
Fixed by #444
