### ISSUE TITLE
FBX skinning animation is not working as expected with recent version of assimp

### ISSUE THREAD

**Issue by GitCodeBoy** [f3d-app/f3d#414]
I loaded a fbx file and the f3d window can show the model, but when I press the space key to play animation,f3d cant play animation correctly like other software like motionbuilder or maya.

Here is the test fbx i use [:https://github.com/GitCodeBoy/test-fbx](https://github.com/GitCodeBoy/test-fbx) , when I open it on motionbuilder or 3D Viewer window 10 ,i can see a catwomen walk around.

**To Reproduce**
 1.open the f3d.exe
 2.drag the test file into the application window
 3. press 'space'
 4. find the model get strange
 5. 
![image](https://user-images.githubusercontent.com/52269611/188910912-fb68bd0b-a0fb-49d5-8ca3-89400fd91711.png)
 

**Expected behavior**
play animation correctly

**System Information:**
 - OS: Windows10

**F3D Information**
f3d 1.3.0

F3D - A fast and minimalist 3D viewer
Version: 1.3.0.
Build date: 2022-09-06 20:50:14.
Build system: Windows AMD64.
Compiler: MSVC 19.33.31629.0.
External rendering module: ON.
Raytracing module: OFF.
Exodus module: ON.
OpenCASCADE module: 7.6.0 (no metadata).
Assimp module: 5.1.0.
Alembic module: 1.8.3.
VTK version: 9.2.20220821 (build 20220821).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Comment by Meakk** [comment]
It's an issue in Assimp, it has been reported many times, for example here: https://github.com/assimp/assimp/issues/4620 https://github.com/assimp/assimp/issues/4487 https://github.com/assimp/assimp/issues/3390  
Animations were working well in Assimp 5.0  
Let's keep this issue open until it's fixed in Assimp.

**Comment by GitCodeBoy** [comment]
> 这是 Assimp 中的一个问题，已多次报告，例如这里：[assimp/assimp#4620 ](https://github.com/assimp/assimp/issues/4620) [assimp/assimp#4487 ](https://github.com/assimp/assimp/issues/4487) [assimp/assimp#3390](https://github.com/assimp/assimp/issues/3390) 动画在 Assimp 5.0 中运行良好 让我们保持这个问题开放，直到它在 Assimp 中得到修复。

Are there any temporary solutions?

**Comment by mwestphal** [comment]
Please note there is some texture issues wiht assimp 5.0

**Comment by mwestphal** [comment]
Another workaround would be to convert your fbx to gltf/glb.

**Comment by mwestphal** [comment]
Could you share the .glb file ?

**Comment by GitCodeBoy** [comment]
> Could you share the .glb file ?

I uploaded it on my test repo :[https://github.com/GitCodeBoy/test-fbx/upload](url)

**Comment by GitCodeBoy** [comment]
> Could you share the .glb file ?

If I need to do anything else when converting FBX files？

**Comment by mwestphal** [comment]
Looks like we forgot to check this one @Meakk

**Comment by mwestphal** [comment]
Closing as duplicate then. @GitCodeBoy you can work around it by positioning the camera in the right location.

**Comment by mwestphal** [comment]
Keeping it open for the Assimp bug though.

**Comment by mwestphal** [comment]
Workaround to try out: https://github.com/assimp/assimp/issues/4620#issuecomment-2186209971
