### ISSUE TITLE
python binding init engine need  arguments

### ISSUE THREAD

**Issue by GitCodeBoy** [f3d-app/f3d#416]
**Describe the bug**
I followed the [doc](https://github.com/f3d-app/f3d/blob/master/README_libf3d.md) to build python binding from source .But when I use the follow code:
`
engine = f3d.engine()
`
and console print
` 
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. f3d.engine(arg0: f3d.window.Type)
`

**Additional context**
Maybe the part about python binding of document need to be updated

**Comment by Meakk** [comment]
Yes indeed, I forgot to add the default value.  
Try `engine = f3d.engine(f3d.window.NATIVE)`

**Comment by Meakk** [comment]
Let's keep this issue open. We should fix the doc now, and modify the bindings to have a default value before f3d 2.0

**Comment by GitCodeBoy** [comment]
> The doc is wrong indeed, this should be:
> 
> `engine = f3d.engine(f3d.window.NATIVE)`
> 
> unless there is a way to specify a a default val with pybind11 @Meakk


Thanks for replying.If I want to use f3d.window.EXTERNAL to embed f3d windows into other applications like a qt(pyqt) application,Are there any more detailed instructions on what I should do?

**Comment by Meakk** [comment]
Take a look at this test: https://github.com/f3d-app/f3d/blob/master/library/testing/TestSDKExternalWindowQT.cxx  
It's in C++ but the Python API is very similar.

**Comment by Meakk** [comment]
You don't have to enable `BUILD_TESTING`.

> Does it mean that I need to customize mouse and keyboard events to make it interatable?

Yes, there is no `f3d::interactor` with an external window. You need to react to mouse/keyboard in QT and modify `f3d::camera` accordingly.

**Comment by GitCodeBoy** [comment]
> You don't have to enable `BUILD_TESTING`.
> 
> > Does it mean that I need to customize mouse and keyboard events to make it interatable?
> 
> Yes, there is no `f3d::interactor` with an external window. You need to react to mouse/keyboard in QT and modify `f3d::camera` accordingly.

Finally I use QWidget: : createWindowContainer to accommodate f3d window, let me to avoid the custom so many mouse and keyboard events, It's worked pretty well in my application so farbut I don't know if will have any side effects. Anyway, this seems to be beyond F3D's responsibility. Thank you for your patience

**Comment by mwestphal** [comment]
It may be a good idea to provide interaction for external window. Can you open an issue so we can track that ?
