### ISSUE TITLE
make Loader class able to remove file

### ISSUE THREAD

**Issue by GitCodeBoy** [f3d-app/f3d#417]
**Is your feature request related to a problem? Please describe.**
I want to edit the file list of loader when I use f3d python binding，but I can only find "addFile" and "loadFile" in f3d.loader class,I cant find  a way to edit or remove a file from loader

**Comment by mwestphal** [comment]
Good point, should be easy to add a method to remove the current file.

**Comment by mwestphal** [comment]
to put in context of #597

**Comment by mwestphal** [comment]
Will be fixed by https://github.com/f3d-app/f3d/pull/634
