### ISSUE TITLE
Cant set window name when debug

### ISSUE THREAD

**Issue by GitCodeBoy** [f3d-app/f3d#424]
**Describe the bug**
When I configure the solution to “release”，I can change the name of window by  using setWindowName.And cant do same things when the solution is configured to "debug" , the window name has changed,but not the name I wanted and the new name of window is just a bunch of garbled code

**To Reproduce**
Here is my simple test code:
```
if __name__ == '__main__':
    engine = f3d.engine(f3d.window.NATIVE)
    window:f3d.window = engine.getWindow()
    window.setWindowName("test")
    interactor:f3d.interactor = engine.getInteractor()
    interactor.start()
```

**Expected behavior**
can set window name in any mode

**System Information:**
 - OS: Windows 10

**Comment by Meakk** [comment]
Maybe it's specific to windows

**Comment by mwestphal** [comment]
Good point, should be checked.

**Comment by mwestphal** [comment]
I'm not able to load f3d module on windows, no idea if the PYTHONPATH is set is correct. Did you try @Meakk ?

**Comment by Meakk** [comment]
No, but it does work in the CI

**Comment by mwestphal** [comment]
@GitCodeBoy please test with the provided code and reopen if needed.
