### ISSUE TITLE
What does CMAKE_CONFIGUREATION_TYPE means?

### ISSUE THREAD

**Issue by GitCodeBoy** [f3d-app/f3d#425]
**Describe the bug**
What does the CMAKE_CONFIGUREATION_TYPE（Debug;Release;MinSizeRel;RelWithDebInfo） means?

**Comment by Meakk** [comment]
It's the configuration you will have in visual studio.  
See https://stackoverflow.com/a/59314670/2609654

**Comment by mwestphal** [comment]
closing this.
