### ISSUE TITLE
Expose all the public APIs in Python and Java

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#426]
**Describe the bug**
Make sure all APIs are correctly bound in Java and Python.
Let's try to craft a simple test that use all the public APIs and translate it to Java and Python.

**Comment by mwestphal** [comment]
sice we plan to rework the loader API further for 3.0, should we drop this for now ?

**Comment by Meakk** [comment]
We can drop it until the API is stabilized. However, it's not a big effort, so maybe it's worth spending a couple of hours on the bindings before the next release.

**Comment by mwestphal** [comment]
ok lets do that

**Comment by mwestphal** [comment]
python bindgins updated. javascript and java flagged as experimental.
