### ISSUE TITLE
Add an option or configuration to set default camera position

### ISSUE THREAD

**Issue by GitCodeBoy** [f3d-app/f3d#427]
**Is your feature request related to a problem? Please describe.**
I have to adjust the camera position once I load a new file.
Does there already exist a way for me to automatically move the camera to a fixed position every time I load a file?

**Describe the solution you'd like**
add a method like Window::SetDefaultCamaraPosition

**Comment by Meakk** [comment]
What's wrong with calling `f3d::camera::setPosition()`?

**Comment by mwestphal** [comment]
no answer from op, closing.

**Comment by mwestphal** [comment]
@GitCodeBoy , feel free to reopen with more information.
