### ISSUE TITLE
Thumbnail View

### ISSUE THREAD

**Issue by PLAmenPRINT** [f3d-app/f3d#442]
**Is your feature request related to a problem? Please describe.**
The request is more about features than problem.

Is it possible to change/custom the following things:
- the Thumbnail View from Top to Front or Front-Right?
- the color of Thumbnails
- the navigation buttons. For example Rotate - right mouse, Move - middle mouse push, Zoom - middle mouse scroll

**Describe the solution you'd like**
Could be created a dropdown menu.

**Describe alternatives you've considered**
Could be created some custom file that can be modified with the required parameters.

**Contribution**
I have no idea if my request is possible or hard to make. Unfortunately I can not help for the realization at all :(
Thank You very much for the attention

**Comment by mwestphal** [comment]
> the Thumbnail View from Top to Front or Front-Right?

Do you mean default camera position ?

> the color of Thumbnails

Do you mean the  --color or --scalars option ?

> the navigation buttons. For example Rotate - right mouse, Move - middle mouse push, Zoom - middle mouse scroll

Not supported I'm afraid, you can switch trackball on/off though.

**Comment by Meakk** [comment]
Related: https://github.com/f3d-app/f3d/pull/399  
We now have a new config file for thumbnails (available in the next release)

**Comment by mwestphal** [comment]
Regarding the camera position, there is also #45

**Comment by PLAmenPRINT** [comment]
> > the Thumbnail View from Top to Front or Front-Right?
> 
> Do you mean default camera position ? - I mean the Thumbnail Icon view
![image](https://user-images.githubusercontent.com/100955264/192773389-9d72b79a-c6ae-4052-9f17-c4cff8d65757.png)
> 
> > the color of Thumbnails - again the color of the Thumbnail Icon. Instead of Silver to be Blue or other contrast to black background color :)
> 
> Do you mean the --color or --scalars option ?
> 
> > the navigation buttons. For example Rotate - right mouse, Move - middle mouse push, Zoom - middle mouse scroll
> 
> Not supported I'm afraid, you can switch trackball on/off though.

**Comment by mwestphal** [comment]
So as @Meakk stated, in the next release you will be able to modify the thumbnail configuratione easily.

What about the default color @Meakk ? do you think we should change it in the context of the thumbnails ?

For the camera position, you will also be able to modify it but it will be better to adress it in #45.

For the interaction, I'm not sure we want to give F3D users this level of customization. Wdyt @Meakk ?

**Comment by Meakk** [comment]
> What about the default color @Meakk ? do you think we should change it in the context of the thumbnails ?

It will be customizable through the thumbnail config file, I think the current "silver" color is fine for the default color.

> For the interaction, I'm not sure we want to give F3D users this level of customization. Wdyt @Meakk ?

Clearly not the priority, but I guess it makes sense to provide different mouse/key bindings at some point.

**Comment by PLAmenPRINT** [comment]
Thank You.
Waiting the next release than :)
