### ISSUE TITLE
Lighting issue with FBX format

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#445]
**Describe the bug**
A .fbx with a light is not rendered correctly in F3D

**To Reproduce**
 0. Export a fbx with a point or spot light in blender, the default scene in blender is like that
 1. Open the file using `f3d --dry-run file.fbx`
 2. Cube is black

**Expected behavior**
Cube is visible

**Comment by Meakk** [comment]
The problem is coming from the light defined in the fbx file. In this case it's a point light, and we should force the cone angle to something > 90 degrees in this case.  
But even with this fix, the light is too bright so there's a problem in assimp or VTK:

![image](https://user-images.githubusercontent.com/6069752/193266422-7edc4242-247c-478a-84ae-54bf1298670f.png)

**Comment by Meakk** [comment]
For information, assimp is declaring `0, 0, 1e-7` for attenuation coefficients. The last parameter is quadratic, resulting in a huge attenuation factor (formula is `attenuation = 1 / (constant + linear * d + quadractic * d * d)`, `d` being the distance between the light and the fragment)

**Comment by mwestphal** [comment]
I think this one is important to fix for 2.0. Wdyt @Meakk ?

**Comment by mwestphal** [comment]
In my case it does not look like this at all @Meakk 

![a](https://user-images.githubusercontent.com/3129530/216758031-60bdbff6-7eab-420c-8caf-bd37da44cdd7.png)

**Comment by mwestphal** [comment]
A few more information:

- Issue is present with or without texture, maybe there are other issue with textures as pointed out by @Meakk , but it may be another issue
- Issue is present **only** with point light or spot light. Sun light and area light are working
- Issue is **not** present with DEA format, even though it is read by assimp too
- Issue is present with testing dataset from assimp (eg: pyramob.fbx)

example:

FBX with pointlight:

![a](https://user-images.githubusercontent.com/3129530/216761789-c93326db-4148-4b46-9450-76a6855f9989.png)

FBX with sunlight:

![b](https://user-images.githubusercontent.com/3129530/216761818-6883f848-90fc-4dee-9cdc-f07b3ef784df.png)

**Comment by mwestphal** [comment]
> But even with this fix,

Can you share this fix ? @Meakk

**Comment by mwestphal** [comment]
This seems to be fixed now:

- [pyramod.fbx](https://github.com/assimp/assimp/blob/master/test/models-nonbsd/FBX/2013_BINARY/pyramob.fbx): 

![pyramod](https://user-images.githubusercontent.com/3129530/218272500-30553140-f695-440a-b6f7-3622d1e96e77.png)


- [CALLADA.dae](https://github.com/assimp/assimp/blob/master/test/models/Collada/COLLADA.dae)

![collada](https://user-images.githubusercontent.com/3129530/218272503-ade65f49-d52b-4a2b-8f76-8be4e9ea9dae.png)

**Comment by mwestphal** [comment]
Anyone having dark or fully white dataset with FBX/DAE, please share them and I will take a look. If not, I will consider this fixed.
