### ISSUE TITLE
F3D window class is "Vtk" on Linux

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#449]
**Describe the bug**
F3D window class is "Vtk" on Linux

Written in hard in vtk itself: vtkXOpenGLRenderWindow.cxx:512.

```
    char classStr[4] = "Vtk";
    char nameStr[4] = "vtk";
    xch.res_class = classStr;
    xch.res_name = nameStr;
    XSetClassHint(this->DisplayId, this->WindowId, &xch);
```

Adding a setter in VTK is needed

**Comment by Meakk** [comment]
Yeah I think we don't care. In the end it is a VTK window so having this information in the class name makes sense.  
We can close it I think.
