### ISSUE TITLE
Better default camera location

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#45]
https://gitlab.kitware.com/f3d/f3d/-/issues/232

**Comment by mwestphal** [comment]
FYI @Meakk

**Comment by mwestphal** [comment]
So I've been thinking about this. As a reminder, here are our current camera options:

```
 Camera options:
      --camera-position <X,Y,Z>
                                Camera position (default: 0)
      --camera-focal-point <X,Y,Z>
                                Camera focal point (default: 0)
      --camera-view-up <X,Y,Z>  Camera view up (default: 0)
      --camera-view-angle <angle>
                                Camera view angle (non-zero, in degrees)
      --camera-azimuth-angle <angle>
                                Camera azimuth angle (in degrees) (default: 
                                0)
      --camera-elevation-angle <angle>
                                Camera elevation angle (in degrees) 
                                (default: 0)

[...]
      --camera-index <index>    Select the camera to use (default: -1) 
```

**Comment by snoyer** [comment]
I ran into this issue when generating samples for #490, my quick and dirty solution was to move the camera absurdly far in a diagonal direction and then call `resetToBounds()`:
```py
camera = engine.getWindow().getCamera()
camera.setPosition(f3d.point3_t(10000,10000,10000))
camera.resetToBounds()
```

> We could add a new option, `--focal-vector` corresponding to an unary vector from the focal point to the camera position, incompatible with `--camera-position`.

That or `--camera-direction`, not sure which one would be more intuitive/user-friendly, could be either as long as the documentation is clear.

> We could even introduction a `--camera-reset-factor` option to control "how far" from the bounds we should reset to.

Would be nice too. Even better if it can be expressed in some kind of screen-space amount of padding around the model in the final render, eg. 0% padding (or 100% fill) would mean the bottom and top (or left and right depending on aspect ratios) parts of the object touch the edges of the image. However that would probably require a specific implementation of `resetToBounds()` using a camera-aligned bounding box of the model.
