### ISSUE TITLE
Small rendering differences between architectures for vtp file

### ISSUE THREAD

**Issue by mzf-guest** [f3d-app/f3d#450]
**Describe the bug**
Same execution of f3d across different architecture leads to slightly different images.

**To Reproduce**

All files (input, output and diff)  are in [cube_diffs.zip](https://github.com/f3d-app/f3d/files/9700229/cube_diffs.zip).

 1. open the `cube.vtp` file with f3d: `f3d -s --resolution=640,480 --output=output.png cube.vtp`
 2. compare the image against the reference from amd64: `compare amd64_cube_vtp.png output.png diff.png`
 3. `diff.png` contains differences (in red) for the following architectures: arm64, i386, ppc64el, s390x. F3D on the other platform looks fine: armel, armhf.

**Expected behavior**
No difference.

**System Information:**
 - OS: Debian
 - GPU and GPU driver: various from Debian CI

**F3D Information**
Paste the content of `f3d --version`:
```
f3d 1.3.1

F3D - A fast and minimalist 3D viewer
Version: 1.3.1.
Build date: 2022-10-02 10:20:26.
Build system: Linux.
Compiler: GNU 12.2.0.
External rendering module: OFF.
Raytracing module: OFF.
Exodus module: ON.
OpenCASCADE module: OFF.
Assimp module: OFF.
Alembic module: OFF.
VTK version: 9.1.0 (build 0).
```

**Additional context**
Using `idiff`, the output is:
```
  Mean error = 8.48482e-06
  RMS error = 0.000182411
  Peak SNR = 74.779
  Max error  = 0.00392157 @ (254, 301, R)  values are 0.552941, 0.478431, 0.27451 vs 0.556863, 0.478431, 0.27451
  1994 pixels (0.649%) over 1e-06
  1994 pixels (0.649%) over 1e-06
```

The differences are really subtle and I can't detect them looking at the files, so feel free to close this bug if you think it's not significant.

In addition, it may be an issue in the VTK library itself.

**Comment by Meakk** [comment]
It depends on the OpenGL implementation of the driver. Is it the same mesa/vendor driver version?

**Comment by mzf-guest** [comment]
As this is different platforms, the vendor driver version is likely not the same, which would explains the small differences. 

Out of curiosity, what is your comparison criterion when we use the `--ref` option in F3D? and what does the `--ref-threshold` mean?

My current criterion is that no more than 1% of the pixel should be strictly different at 1e-6, but I don't know if this is relevant.

Thanks

**Comment by mwestphal** [comment]
The treshold we use correspond to this: 
https://vtk.org/doc/nightly/html/classvtkImageDifference.html#a7dd3f6f2599d1dd55bdf16165ae1f71f

`vtkImageDifference::GetThresholdedError`
> The thresholded error is the error for a given pixel minus the threshold and clamped at a minimum of zero. 

The vtk doc is not super clear about this. By default, the threshold we use is 50, which let us avoid issue with driver and such.

**Comment by mzf-guest** [comment]
Thanks for the information!

You can close the issue, unless you want to keep track of these differences?
