### ISSUE TITLE
How to add a callback function to Loader::loadFile()

### ISSUE THREAD

**Issue by GitCodeBoy** [f3d-app/f3d#452]
**Is your feature request related to a problem? Please describe.**
I want to execute Loader::loadFile() asynchronously.

**Comment by mwestphal** [comment]
Not sure what you mean, you can call loadFile whenever you want.

**Comment by GitCodeBoy** [comment]
> Not sure what you mean, you can call loadFile whenever you want.

I use the Qt's createWindowContainer to embeded  a f3d application in my Qt application. If I call loadFile() in main thread, my Qt application will be blocked. I want to call loadFile() in another thread and call a callback fucntion when f3d has rendered the fbx file

**Comment by GitCodeBoy** [comment]
> Not sure what you mean, you can call loadFile whenever you want.

I'm sorry I asked a stupid question

**Comment by mwestphal** [comment]
Do not hesitate if you have any further questions @GitCodeBoy, adding asynchronous method is not planned.
