### ISSUE TITLE
Misplaced cmake lines related to the python binding

### ISSUE THREAD

**Issue by yurivict** [f3d-app/f3d#456]
[This line](https://github.com/f3d-app/f3d/blob/master/CMakeLists.txt#L195) really belongs [here](https://github.com/f3d-app/f3d/blob/master/python/CMakeLists.txt#L1).

And [this line](https://github.com/f3d-app/f3d/blob/master/cmake/installing.cmake#L38) belongs [here](https://github.com/f3d-app/f3d/blob/master/python/CMakeLists.txt#L27).

This way one could build the project in ```python/``` separately. But now these relevant lines are in other files.

**Comment by mwestphal** [comment]
What do you mean by building the project separately ?

**Comment by Meakk** [comment]
I suppose the idea is to split f3d in different packages (libf3d, f3d, pyf3d...)  
We should think about it indeed.  
It's also something I have in mind with the plugin architecture I'm currently implementing (occt/assimp/alembic could be a dependency of the plugin packages)

**Comment by yurivict** [comment]
> I suppose the idea is to split f3d in different packages (libf3d, f3d, pyf3d...)

Yes. I am going to add the FreeBSD port for f3d Python binding, and have encountered this problem with misplaced lines.

**Comment by Meakk** [comment]
There is also a dependency on `libf3d` target though, so we also maybe need to add something like:
```cmake
if (NOT TARGET libf3d)
  find_package(f3d REQUIRED)
  add_library(libf3d ALIAS f3d::libf3d)
endif()
```

**Comment by mwestphal** [comment]
> I suppose the idea is to split f3d in different packages (libf3d, f3d, pyf3d...)

That would be nice, but I'm not sure how @yurivict suggestion address this.

**Comment by yurivict** [comment]
> That would be nice, but I'm not sure how @yurivict suggestion address this.


This is the movement in the same direction.
The inner CMakeLists.txt can be a complete, separately buildable cmake file.

For example, the  [Faiss](https://github.com/facebookresearch/faiss/blob/main/CMakeLists.txt#L37) project does it this way.

**Comment by mwestphal** [comment]
Great, do you think you could provide a PR for this change ? @yurivict
