### ISSUE TITLE
Support for draco compressed gltfs

### ISSUE THREAD

**Issue by nickholt15** [f3d-app/f3d#469]
**Context**
F3D support glTF and Draco files, however, F3D does NOT support Draco-compressed glTF files.
As draco is used widely, it would be nice to add such support to both VTK and F3D.

Support for draco gltfs would make this a very powerful mesh preview tool. Currently the best alternative is to open a draco compressed gltf with Blender or use an online gltf viewer that supports draco compressed meshes.

**Suggested solution**
 - Improve vtkGLTFReader and vtkGLTFImporter in VTK (https://gitlab.kitware.com/vtk/vtk) so they support draco compressed data, using the libdraco as an optional dependency for VTK
 - Update VTK version in F3D

**Notes**
The F3D maintainers will be able to help with the implementation and the contribution to VTK!

**Comment by Meakk** [comment]
I agree.  
Related: https://github.com/f3d-app/f3d/issues/59  
It's on my to-do list but with low priority.  
If someone want to do it, I can help.

**Comment by Meakk** [comment]
FYI @paulfx

**Comment by stom66** [comment]
No other model viewer (that I am aware of) currently supports previewing draco compressed glTF models. I myself found this project by searching for one that does.

I vote +1 for this feature.

**Comment by mwestphal** [comment]
Increasing priority as this was mentionned a few times during the release

**Comment by mwestphal** [comment]
@Meakk any luck with this one ?

**Comment by Meakk** [comment]
Not yet. I can focus on that one after USD, I agree it's very important to support it.

**Comment by mwestphal** [comment]
@Meakk You still have this on your backlog if you do not know what to do :)

**Comment by Meakk** [comment]
Add that to the 2.4 plan and assign it to me.

**Comment by nickholt15** [comment]
Thanks for completing this issue! I'm excited to give it a try. I noticed your Windows nightly builds haven't been released for about two weeks. I'll try on Linux.

**Comment by Meakk** [comment]
Yes, Windows nightly generation is currently broken (https://github.com/f3d-app/f3d-superbuild/issues/154).  
Let me know if you find any issues with the Draco extension.

**Comment by nickholt15** [comment]
Was able to test the nightly build in WSL and it's working great. Thanks for this! I'll look forward to the 2.4 release for Windows
