### ISSUE TITLE
HTML doc on windows

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#47]
The following discussion from !265 should be addressed:

- [ ] @jpouderoux started a [discussion](https://gitlab.kitware.com/f3d/f3d/-/merge_requests/265#note_984860):  (+3 comments)

    > May be out of scope of this MR but quite related: it could be nice to generate a HTML file to be installed for Windows users.

https://gitlab.kitware.com/f3d/f3d/-/issues/235

**Comment by jpouderoux** [comment]
This requires an external tool to convert md to html. We could:
 - include one in a thirdparty directory and build it to generate the doc, 
 - or we can just expect the path on an executable.

**Comment by mwestphal** [comment]
imo, only needed in the package, so lets find the path to an exec and add the tool in the ci.

@Meakk

**Comment by mwestphal** [comment]
That being said, adding a link to the website during instlation would be enough imo.

**Comment by mwestphal** [comment]
lets drop this one
