### ISSUE TITLE
3MF support

### ISSUE THREAD

**Issue by H4kunaM4tata** [f3d-app/f3d#475]
Is there any future plan to include 3MF support??

STL is still somewhat largely being used but the adoption to 3MF is just around the corner.
If you got the new toy Bambu Lab X1 Carbon 3D printer, its slicer export to 3MF, the printer reads 3MF although you can still use the old g-code/stl. 
You do miss some features like the display showing the model thumbnail, etc.
Some models on the internet are starting to have 3MF format only available.

F3D is light, and works amazingly well in both Windows and Linux Mint.
It would be a dream having it to support 3MF too.

Thank you

**Comment by mwestphal** [comment]
Hi @H4kunaM4tata 

We have a centralized issue for new file formats, I've added your vote for 3MF: https://github.com/f3d-app/f3d/issues/38
