### ISSUE TITLE
Rework documentation

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#48]
Documentation is hard to maintain, here is the current state:

- README.md contains the whole user documentation
- GENERATE.md contains some developper oriented documentation
- documentation/* contains a duplicate, segmented and slightly modified version of the README.md
- src/F3DOptions code contains options, hotkeys and examples documentations to be delivered with --help
- man contains documentations generated from --help and --version
- We potentially will have one more version of the doc thanks to #47 
There is a few issues with this approach:

1. Generic doc is duplicated two times
2. Options/Hotkeys doc is duplicated three times
3. main README.md is getting very long and hard to read

This should be improved, here is what we need to have:

1. Complete user documentation should be available in a gitlab markdown format from the main README.md
2. Complete user documentation should be available in the webdoc
3. Limit duplication as much as possible

Here is a proposition to fix that:

1. Put only the most esential and nice looking information in the main README.md
2. Link from the main README.md to other logically organized .md files in a dedicated directory (see below for an example organization)
3. Generate webdocumentation .md files during build thanks to cmake custom commands (see below for more info)
4. If adressing #47, generate simple html doc during build OR generate actual web doc during build
5. (Optional) Find a way to generate a .h from the options/hotkeys .md file during build so that it can be used in the --help output (and other usages?)
6. (Optional) Use Pandoc instead of help2man to generate man, relying on generated .md file during build (see expected format here: https://www.pragmaticlinux.com/2021/01/create-a-man-page-for-your-own-program-or-script-with-pandoc/)

Example .md file organization, that could also be used as a webdoc organisation:

```
- README.md
- doc
-- OPTIONS.md
-- HOTKEYS.md
-- INSTALATION.md
-- USAGE.md
-- BUILD.md (should this go into dev?)
-- CONFIGURATION_FILE.md
-- LIMITATIONS.md
-- TROUBLESHOOTING.md
-- dev
--- GENERATE_WEBDOC.md
--- GENERATE_COVERAGE.md
--- GENERATE_MAN.md
--- DEVELOP.md
- webdoc
...
```

Differences between README.md and webdoc md files:

- Image paths are differents (could be fixable):

```
+ ![F3D Logo](./resources/logo.svg) 
- ![F3D Logo](logo.png) 
```

```
+ <img src="https://kitware.github.io/F3D/gallery/04-f3d.png"  width="640">
- ![F3D Demo](../gallery/04-f3d.png)
```

- many nbsp in the webdoc (could be fixable?)
```
+ Options &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&|Description
- Options|Description                                                                                                                                     
```

- Internals links are removed (should be fixable)
```
+ See the coloring cycle section for more info.
- See the [coloring cycle](#Cycling Coloring) section for more info. 
```

If all slight change are removed, simply symlinking from the webdoc to the doc.md could be a very easy solution to put into place.

**Comment by mwestphal** [comment]
https://gitlab.kitware.com/f3d/f3d/-/issues/236

**Comment by mwestphal** [comment]
@Meakk : for the time being, lets keep update the ReadME.md, but lets not touch the old doc for the website.

**Comment by mwestphal** [comment]
Doc should be added for the libf3d too.

**Comment by mwestphal** [comment]
Here is a an updated plan for the new doc:

```
- README.md: contains generic presentation, link to release, quick how to use and acknoledgements
- GALLERY.md: same content as https://f3d-app.github.io/f3d/gallery/
- doc
-- OPTIONS.md: contains # Options
-- HOTKEYS.md: contains # Interaction and # Cycling coloring
-- INSTALATION.md: contains # Instalation
-- USAGE.md: contains # File Formats, # Scene construction, # rendering precedence, and anything else 
-- CONFIGURATION_FILE.md:  contains # Configuration File
-- DESKTOP_INTEGRATION.md: contains # Desktop Integration
-- LIMITATIONS.md: contains # Limitations
-- TROUBLESHOOTING.md: contains # Troubleshooting
-- dev
--- BUILD.md: contains # Build
--- GENERATE_COVERAGE.md: info about generating coverage
--- GENERATE_MAN.md: info about generating man
--- DEVELOP.md: info about our process of developement and how to contribute to f3d
-- libf3d
--- OVERVIEW.md: generic information about the libf3d, partially contains README_libf3d.md
--- EXAMPLES.md: expanded set of examples usage of the libf3d, insipired by README_libf3d.md
--- doxygen: not sure of the feasiability of this, but doxygen should be used to generate actual ref for libf3d
```

wdyt @Meakk @Audrey ?

**Comment by mwestphal** [comment]
Please provide some feedback @Meakk

**Comment by Meakk** [comment]
We need a section for python/java bindings, otherwise looks good to me.

**Comment by mwestphal** [comment]
```
- README.md: contains generic presentation, link to release, quick how to use and acknoledgements
- GALLERY.md: same content as https://f3d-app.github.io/f3d/gallery/
- doc
-- OPTIONS.md: contains # Options
-- HOTKEYS.md: contains # Interaction and # Cycling coloring
-- INSTALATION.md: contains # Instalation
-- USAGE.md: contains # File Formats, # Scene construction, # rendering precedence, and anything else 
-- CONFIGURATION_FILE.md:  contains # Configuration File
-- DESKTOP_INTEGRATION.md: contains # Desktop Integration
-- LIMITATIONS.md: contains # Limitations
-- TROUBLESHOOTING.md: contains # Troubleshooting
-- dev
--- BUILD.md: contains # Build
--- GENERATE_COVERAGE.md: info about generating coverage
--- GENERATE_MAN.md: info about generating man
--- DEVELOP.md: info about our process of developement and how to contribute to f3d
-- libf3d
--- OVERVIEW.md: generic information about the libf3d, partially contains README_libf3d.md
--- EXAMPLES.md: expanded set of examples usage of the libf3d, insipired by README_libf3d.md
--- BINDINGS.md
--- doxygen: not sure of the feasiability of this, but doxygen should be used to generate actual ref for libf3d
```

**Comment by mwestphal** [comment]
Trying github upload

![dota](https://user-images.githubusercontent.com/3129530/194735261-dd6f1c1c-fa57-47b0-9d27-f735d18ccd5e.gif)
[can.webm](https://user-images.githubusercontent.com/3129530/194735269-b62216e6-33da-484c-9f0d-39befc8253bf.webm)
[dota.webm](https://user-images.githubusercontent.com/3129530/194735270-92d9876f-a772-4665-9728-cd0a42874862.webm)
![directScalars](https://user-images.githubusercontent.com/3129530/194735272-5bcd3e7c-a333-41f5-8066-9b0bec9885e8.png)
[gearbox.webm](https://user-images.githubusercontent.com/3129530/194735274-395839e9-e2cb-4a47-83b9-5c6987640032.webm)
![pointCloud](https://user-images.githubusercontent.com/3129530/194735348-7dd14922-f546-4f54-8bc2-b6602617c4cc.png)
![volumeMedical](https://user-images.githubusercontent.com/3129530/194735354-486999dd-3c57-4ab1-a9ad-b8e97bac0da0.png)
![cfd](https://user-images.githubusercontent.com/3129530/194735361-7e827d8e-531a-4938-b608-18825a9574f8.png)
![realisticMask](https://user-images.githubusercontent.com/3129530/194735363-d2be23bb-90b6-4e90-941d-14b6dc24b476.png)
![fbx](https://user-images.githubusercontent.com/3129530/194735366-e79a8d45-8b76-4a65-9445-4a0ca1b63876.png)
![step](https://user-images.githubusercontent.com/3129530/194735370-4d1f067c-704c-4118-9d94-c1adf4039c39.png)
![realisticHelmet](https://user-images.githubusercontent.com/3129530/194735376-3a476643-00d6-4cfc-9a88-e0dd33658564.png)
![volume](https://user-images.githubusercontent.com/3129530/194735377-127fa5d8-ece5-40c7-8176-672279ebdacc.png)
![cad](https://user-images.githubusercontent.com/3129530/194735378-b8be4df2-e030-4d13-b12f-24806cbb385b.png)

**Comment by mwestphal** [comment]
![typical](https://user-images.githubusercontent.com/3129530/194735416-3f386437-456c-4145-9b5e-6bb6451d7e9a.png)

**Comment by mwestphal** [comment]
![logo](https://user-images.githubusercontent.com/3129530/195972388-0dce5ae1-df70-408a-aff0-728ffff1d9ae.svg)

**Comment by mwestphal** [comment]
![logo](https://user-images.githubusercontent.com/3129530/195972508-dd29627c-439b-4b70-8ca7-c591aaa84a6c.png)

**Comment by mwestphal** [comment]
![Uploading logo.png…]()

**Comment by mwestphal** [comment]
![logo](https://user-images.githubusercontent.com/3129530/195972584-11ebb000-4939-47f4-9719-9d55e18867b0.png)

**Comment by mwestphal** [comment]
![Octicons-mark-github svg](https://user-images.githubusercontent.com/3129530/197902564-8866e335-4c37-46ed-923a-fb2b70059430.png)

**Comment by mwestphal** [comment]
![Octicons-mark-github svg](https://user-images.githubusercontent.com/3129530/197903476-11d9c41d-73b0-461f-93e8-c8c00c680e6e.png)

**Comment by mwestphal** [comment]
![logo32](https://user-images.githubusercontent.com/3129530/200879834-8b5d5df5-8432-4a37-b97a-8a1ed779065a.png)

**Comment by mwestphal** [comment]
Fixed by #364

**Comment by mwestphal** [comment]
![a](https://user-images.githubusercontent.com/3129530/200903167-335a5e80-4eee-4856-8fc9-3f8d5f72b898.png)

**Comment by mwestphal** [comment]
![194735416-3f386437-456c-4145-9b5e-6bb6451d7e9a](https://user-images.githubusercontent.com/3129530/201317344-092db03d-8616-45b9-b606-30d22cda2eff.png)
