### ISSUE TITLE
SlowMotion Playback

### ISSUE THREAD

**Issue by alianilir** [f3d-app/f3d#486]
**Describe the bug**
Can't play mixamo animation at realtime speed
**To Reproduce**
 1. Open the file using `f3d --any mixamo animation`
 2. Press spacebar for play
 3. Slow Motion playback issue

**Expected behavior**
Can't play mixamo animation at realtime speed
**System Information:**
 - OS: Mac 
 - GPU and GPU driver: Apple M1 Pro 32 GB Ventura 13.0.1 

**F3D Information**
Paste the content of `f3d --version`: Latest 

**Additional context**
I can't play any Mixamo animation at realtime speed. All them play slow motion

Here settings which i download for Unity
<img width="691" alt="image" src="https://user-images.githubusercontent.com/104074156/201875628-df995cff-e403-4de5-96a7-77a0c078dc7d.png">

https://user-images.githubusercontent.com/104074156/201876450-8fbed94e-a36f-4db8-bd8e-332dfd5bcc52.mp4

**Comment by Meakk** [comment]
> Paste the content of f3d --version: Latest

Please be more specific. In your case, the FBX animations highly depend on the Assimp version used internally by F3D.  
Also, please share the FBX file.

**Comment by mwestphal** [comment]
No answer from OP, closing. @alianilir, feel free to reopen.

**Comment by mwestphal** [comment]
Reproduced on windows with any animated fbx

**Comment by mwestphal** [comment]
@Meakk @alianilir : So I checked different versions and I only see this in our 1.3.1 release using Assimp 5.1.0.

This is fixed in F3D master using Assimp 5.2.4, you can download our nightly to try it:

https://github.com/f3d-app/f3d/releases/tag/nightly
