### ISSUE TITLE
Improve F3D testing data

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#531]
F3D provide some tests dataset, stored in LFS. There is a few issues with these data.

1. Total LFS size is ~30Mb and growing. This is not ideal because it means that cloning can takes some time AND github LFS bandwidth is metered, which has a cost
2. Some data files have not ideal license, eg: grabcad, sketchup, which is not great and may have impact when packaging F3D in some linux distribution

A few ideas to fix this:
- Remove/rework  all "big" datasets (WaterBottle, Dragon) so that max dataset size is < 5Mb, ideally < 1Mb.
- Remove all dubious licensed file and replace by file created from blender/freecad
- Compress all lfs data and uncompress them at configuration time

**Comment by mzf-guest** [comment]
> @mzf-guest YOu mentionned some problematic licenses, coul youd identify them ?

For the official Debian package, all files should comply the [Debian Free Software Guidelines (DFSG)](https://wiki.debian.org/DebianFreeSoftwareGuidelines). There is a dedicated page that lists [compatible licenses](https://wiki.debian.org/DFSGLicenses).

A quick scan at the [data licenses file](https://github.com/f3d-app/f3d/blob/master/testing/data/DATA_LICENSES.md) shows some licenses that should be checked against the DFSG:

- AttackGraffiti-3zRBM.ttf: wepfont: Freeware
- cube.stp: GrabCad/Skip Baker: Cross License
- KameraAnim.glb: flying dog software
- Robot_Color.tga: Unity Asset Store: Free to use
- robot_kyle_walking.fbx: Unity Asset Store: Free to use
- Robot_Normal.tga: Unity Asset Store: Free to use
- slime.fbx: Turbosquid: Turbosquid 3D Model License
- spacer.igs: GrabCad/Michel Deville: Cross License

Hope this helps!

Best,

**Comment by mwestphal** [comment]
@imperator-maximus @flyingdogsoftware could you precise the license for KameraAnim.glb which I found over here: https://www.flyingdog.de/downloads/kamera/KameraAnim.glb

**Comment by mwestphal** [comment]
@mzf-guest let me know what you think of this new list of license: https://github.com/f3d-app/f3d/blob/master/testing/data/DATA_LICENSES.md

**Comment by mzf-guest** [comment]
I'm late to the party as I'm just starting packaging 2.0.0 version for Debian.

The duck.dae file contains this copyright text :
```
Copyright 2006 Sony Computer Entertainment Inc.
Licensed under the SCEA Shared Source License, Version 1.0 (the
&quot;License&quot;); you may not use this file except in compliance with the
License. You may obtain a copy of the License at:
http://research.scea.com/scea_shared_source_license.html 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
```

Whereas the `DATA_LICENSES.md` mentions "duck.dae: assimp test models: BSD-3-Clause". Was it re-licensed?

Otherwise it looks good! Great work!

François

**Comment by mwestphal** [comment]
It is this file from assimp: https://github.com/assimp/assimp/blob/master/test/models/Collada/duck.dae

Which is under the "model" directory, which are distributed by assimp under their own BSD license (contrary to the model-non-bsd folder). That means that assimp were wrong in their assumption and do not respect this file license.

Looking at the license it is:

SPDX listed: https://spdx.org/licenses/SCEA.html
OpenCoDE accepted: https://wikijs.opencode.de/en/Hilfestellungen_und_Richtlinien/Lizenzcompliance
OpenSUSE accepted: https://en.opensuse.org/openSUSE_talk:Accepted_licences
**Not an OSI license**
**Not listed by FSF**

Reading it, it seems to be an source-code only Apache 2.0 similar license. So, very unrestrictive.

Is this license ok for debian @mzf-guest ? If so I will update the license.md about it, if not I will remove the file and find another, better licensed one. Juste le me know.


BTW, if assimp made a mistake with one license, they may have made a mistake with another, do not hesitate to investigate any of the assimp file if you feel it is needed.

**Comment by mwestphal** [comment]
https://github.com/assimp/assimp/issues/5144

**Comment by mwestphal** [comment]
fixed now.
