### ISSUE TITLE
A thought about exposing rendering pipeline to public.

### ISSUE THREAD

**Issue by YangShen398** [f3d-app/f3d#534]
**Is your feature request related to a problem? Please describe.**
I really like how F3D is set up in its minimal and bloat-free way. The only downside I experienced so far is that libf3d does not expose its rendering pipeline to the client. Sometimes I just have a vtkObject (e.g., vtkUnstructuredGrid or vtkPolyData) which I want to visualize. But if I use F3D as a dependency in my project without changing the source, I can only read a file from disk. 

Something as easy as this will satisfy all my needs.  
```
vtkNew<vtkUnstructuredGrid> ug;
// build my ug and then add it to f3d engine
f3d::engine eng;
eng->getRenderer()->addDataSet(ug);
```
Or maybe there is already a way to achieve this using the plugin? Please advise.

**Describe the solution you'd like**
Expose vktRenderer in the engine so we can use it to add vtkObject from memory.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Contribution**
Yes, I can contribute.

**Comment by mwestphal** [comment]
It was a design choice to make VTK dependency private and it is not planned to change.

That being said, I think this may be possible through a "dummy" plugin as long as you can make it communicate with your application and provide the unstructured grid there. You may want to give it a go just so we know if and how to do it.

Another way to implement this would be trough a `void*` API, or some kind of vtkDataSet marshalling operation, but adding such an API needs some reflexion to do it right.

**Comment by Meakk** [comment]
I also think it could be done through a plugin. It definitely makes sense if your VTK pipeline is fixed.  
For example, if you have a simulation code, you can set the inputs in a file, and run the simulation and the post-processing pipeline in the importer.

**Comment by mwestphal** [comment]
Once read/write to buffer is supported by VTK, implementing that should be trivial.

**Comment by Meakk** [comment]
Is there a WIP MR we can follow in VTK?

**Comment by mwestphal** [comment]
First layer has been implemented: 
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9663

Second layer is ongoing:
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9764

Then we need to implement it in the reader we want though.

**Comment by mwestphal** [comment]
@YangShen398 : please note a new API has been added to the loader. You can now load geometry from a dedicated mesh struct. You probably can convert from a VTK dataset without mush issue. Closing this.

#978 #980 #983
