### ISSUE TITLE
Issue building f3d-git from AUR

### ISSUE THREAD

**Issue by Technetium1** [f3d-app/f3d#538]
**Describe the bug**
`f3d-git` AUR package fails to build in a clean chroot

**System Information:**
 - OS: Arch Linux
 - GPU and GPU driver: N/A

**F3D Information**
https://aur.archlinux.org/packages/f3d-git

**Additional context**
This was found due to a request to add it to Chaotic-AUR: https://github.com/chaotic-aur/packages/issues/1760

Build log after applying a missing dependency via https://github.com/chaotic-aur/interfere/commit/0096f72366a7e695423a3c7bdc7ded8ed47244b8: 
[f3d-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/f3d-git.log)

**Comment by mwestphal** [comment]
Thanks for your reports. I've seen the other one on the f3d package. Would you be interested to be a co maintainer on both package ? TBH we are hardly using the package as we develop F3D, so it would make sence to have advanced users of F3D maintaining imo. Wdyt ?

**Comment by Technetium1** [comment]
Thanks, but I don't have any interest in using or maintaining this. I just want to make it available via Chaotic. Happy to help report any issues though. Once it's functional in a routine, you're welcome to utilize the automated build logs to ensure any updates you push to the AUR go smoothly within an hour of commit.

**Comment by mwestphal** [comment]
>  the automated build logs to ensure any updates you push to the AUR go smoothly within an hour of commit.

Could you elaborate on that ?

**Comment by Technetium1** [comment]
In the linked issue above, I committed this: https://github.com/chaotic-aur/packages/commit/5f9b1b333b8afb7debe1b7d0335224283c598e8f. It adds `f3d` to an hourly routine which checks if the AUR package has changed, which then does a rebuild if it has.

Once `f3d-git` is added, it will check for updates to both the AUR package and the git repo, and rebuild if there are changes to either. Packages are not added to a routine until they're building successfully.

You can find all the logs here: https://builds.garudalinux.org/repos/chaotic-aur/logs/

You can see more about Chaotic-AUR on the homepage: https://aur.chaotic.cx

**Comment by Meakk** [comment]
I updated the AURs

**Comment by mwestphal** [comment]
There is a comment from @Technetium1 on f3d-git but I dont see it in the new PKGBUILD:

> Missing utf8cpp in makedepends to build in clean chroot.

**Comment by mwestphal** [comment]
It is probably missing in f3d package too.

**Comment by Technetium1** [comment]
@mwestphal @Meakk `utf8cpp` is not required for `f3d`, but it _definitely_ is for `f3d-git`, or else this:

```
-- Could NOT find utf8cpp (missing: utf8cpp_INCLUDE_DIR)
-- Plugin: assimp 5.2.4 found
CMake Warning at plugins/assimp/CMakeLists.txt:9 (message):
Plugin: assimp: Animations are not working with assimp 5.1.0 and newer, use
assimp 5.0.X for animation support with assimp formats.


-- Could NOT find utf8cpp (missing: utf8cpp_INCLUDE_DIR)
CMake Error at /usr/share/cmake/draco/draco-targets.cmake:83 (message):
The imported target "draco::draco_static" references the file

"/usr/lib/libdraco.a"

but this file does not exist.  Possible reasons include:

* The file was deleted, renamed, or moved to another location.

* An install or uninstall procedure did not complete successfully.

* The installation package was faulty and contained

"/usr/share/cmake/draco/draco-targets.cmake"

but not all the files it references.

Call Stack (most recent call first):
/usr/share/cmake/draco/draco-config.cmake:27 (include)
plugins/draco/CMakeLists.txt:3 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/main-builder/pkgwork/src/f3d/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
```

**Comment by mwestphal** [comment]
We can fix that in f3d-git but this is a draco package issue imo
https://archlinux.org/packages/community/x86_64/draco/

**Comment by Technetium1** [comment]
@mwestphal I agree, in the meantime it would be good to have it manually specified. :)

**Comment by Technetium1** [comment]
@svenstaro is the `draco` maintainer

**Comment by mwestphal** [comment]
It looks like there is a few other issues with draco, looking at it.

**Comment by mwestphal** [comment]
- https://bugs.archlinux.org/task/76873
- https://bugs.archlinux.org/task/76874

@svenstaro

**Comment by mwestphal** [comment]
f3d-git has been fixed but I had to add a compat package to make draco work

**Comment by mwestphal** [comment]
in case someone find this, f3d is now in community and draco has been fixed.
