### ISSUE TITLE
Provide 32-bit preview handlers for greater compatibility

### ISSUE THREAD

**Issue by boromyr** [f3d-app/f3d#549]
**Is your feature request related to a problem? Please describe.**
The thumbnail manager doesn't work with 32-bit apps like XYplorer

**Describe the solution you'd like**
Compile the 32bit version to include in the F3D installation

**Comment by Meakk** [comment]
Are you sure it's related to the 32 bits architecture? Thumbnails on Windows are handled by a shell extension. Does XYplorer use shell extensions too?

**Comment by boromyr** [comment]
I'm 95% sure of it. XY uses the same extensions as the Windows shell, but often gives problems for those available only in 64bit. https://github.com/unlimitedbacon/stl-thumb doesn't work since it's 64bit only, I switched to https://papas-best.com/stlthumbnails_en which has both versions. https://github.com/EtheaDev/SVGShellExtensions works in XY since the author added 32bit version as well. I checked with shexView that the CLSID for F3D is only available in 64bit and is not registered as x64/x86 version

**Comment by mwestphal** [comment]
https://www.xyplorer.com/

Looks like there is a work around:
https://www.xyplorer.com/faq-topic.php?id=ctx64

FYI we are not likely to provide a 32 bit version for this usecase, as windows is moving away from 32 bit applications. XYPlorer will have to switch at some pont.

**Comment by boromyr** [comment]
The solution you reported is only for the context menu, but thank you for your research. Unfortunately, being written in VB6, XYplorer cannot be compiled in 64bit, but could I compile my own 32bit version for the preview manager? I use VS 2022, should I use cmake only for https://github.com/f3d-app/f3d/tree/master/winshellext? Correct me if I'm wrong

**Comment by mwestphal** [comment]
HI @boromyr 

you cant build only the shell extensions, you should configure and build the whole project and make sure to turn on 

`F3D_BUILD_WINDOWS_SHELL_THUMBNAILS_EXTENSION`

let us know if you have any issues building for 32 bit, we may want to fix them.

**Comment by mwestphal** [comment]
Closing this as we will not provide a 32bit version. We welcome any fixes that may be needed to compile on 32 bit though.
