### ISSUE TITLE
[Feature Request] Gnome-Sushi integration

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#55]
This tool seems to be really good. I am wondering if you ever consider to integrate this with gnome-sushi. A fast preview of 3d files by hitting spacebar would be awesome.

**Comment by geowarin** [comment]
More info here: https://gitlab.gnome.org/GNOME/sushi/-/issues/72

**Comment by mwestphal** [comment]
This should be much easier once we release the libf3d in alpha.

**Comment by geowarin** [comment]
Oh really? I was looking at how to embed f3d in a GtkGLArea but I have no real experience with gtk :smile:

**Comment by geowarin** [comment]
Really excited for this then. Glad to know this is in the pipe!

**Comment by mwestphal** [comment]
Hi @geowarin ,

Just to clarify, we (the F3D developpers) do not plan to implement this, but we have created the tools needed for this in F3D.
Anyone from the gnome sushi community can now use the libf3d to achieve that goal.

I will go ahead and close this and this feature (gnome sushi integration) will not be implemented in F3D directly.
