### ISSUE TITLE
MIME Types

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#58]
I came across F3D in my search for a minimal viewer for 3D models on linux, but it didn't seem to register itself as the default application for 3D files in my file browser.
As such i request the following:

## New feature description

1. [ ] Expand the [linux desktop entry](https://gitlab.kitware.com/f3d/f3d/-/blob/6e49276ba102b6e9a775c0325a432f8b301781df/resources/f3d.desktop) to include a [MimeType](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-0.9.5.html#mime-types) field, such that files can be opened with file managers

1. [ ] Make [this line](https://gitlab.kitware.com/f3d/f3d/-/blob/6e49276ba102b6e9a775c0325a432f8b301781df/resources/mime-types-3d-misc-formats.xml#L8) more specific. Could it be expanded it to only match known filename extensions?

1. [ ] Perhaps include the following MIME types i found while searching the internet, which [you do no seem to be using](https://gitlab.kitware.com/f3d/f3d/-/blob/6e49276ba102b6e9a775c0325a432f8b301781df/resources/f3d.thumbnailer#L6):
    * [`model/step`](https://www.iana.org/assignments/media-types/model/step)
    * [`model/step+xml`](https://www.iana.org/assignments/media-types/model/step+xml)
    * [`model/step+zip`](https://www.iana.org/assignments/media-types/model/step+zip)
    * [`model/step+xml+zip`](https://www.iana.org/assignments/media-types/model/step-xml+zip)
    * [`model/x.stl-ascii`](https://en.wikipedia.org/wiki/STL_(file_format))
    * [`model/x.stl-binary`](https://en.wikipedia.org/wiki/STL_(file_format))
    * [`application/x-3ds`](https://www.digipres.org/formats/sources/ffw/formats/#3ds)

## Contribution

I could contribute this, but I request comment on whether the listed MIME types look sound or not, would need direction on where it is preferable to put all the MIME types, and what exactly [this line](https://gitlab.kitware.com/f3d/f3d/-/blob/6e49276ba102b6e9a775c0325a432f8b301781df/resources/mime-types-3d-misc-formats.xml#L8) is supposed to match.

**Comment by mwestphal** [comment]
https://gitlab.kitware.com/f3d/f3d/-/issues/251

**Comment by pbsds** [comment]
Leaving this link here for later maybe: https://github.com/cnr-isti-vclab/meshlab/blob/master/scripts/Linux/resources/meshlab.desktop
