### ISSUE TITLE
Don't Run on Windows Server 2019

### ISSUE THREAD

**Issue by AlexBuzaev75** [f3d-app/f3d#585]
Last built Don't Run on Windows Server 2019

**Comment by mwestphal** [comment]
> Last built 

Which version are you using exactly ?

**Comment by AlexBuzaev75** [comment]
I try on Windows 2019 standart

пн, 30 янв. 2023 г. в 16:40, Mathieu Westphal ***@***.***>:

**Comment by mwestphal** [comment]
Where do you download F3D ? Which version of F3D are your using ?

**Comment by AlexBuzaev75** [comment]
I downloaded it here
https://github.com/f3d-app/f3d/releases/download/nightly/F3D-1.3.1-171-gb6f06f0-win64.exe

пн, 30 янв. 2023 г. в 16:47, Mathieu Westphal ***@***.***>:

**Comment by mwestphal** [comment]
Please try this version: https://github.com/f3d-app/f3d/releases/download/v1.3.1/f3d-1.3.1-win64.exe

**Comment by AlexBuzaev75** [comment]
Sorry, also don't run

пн, 30 янв. 2023 г. в 16:56, Mathieu Westphal ***@***.***>:

**Comment by mwestphal** [comment]
Ok, well, F3D was never tested on Windows Server 2019 and we dont have access to this OS. We can keep the issue open but I'm afraid it will not get fixed.

**Comment by AlexBuzaev75** [comment]
Can you solve it on any other Windows Server version?
I am sure that this bug is reproduce on any windows server version

пн, 30 янв. 2023 г. в 17:04, Mathieu Westphal ***@***.***>:

**Comment by mwestphal** [comment]
We do not have access to any Windows Server I'm afraid. Do you have an error message ?

**Comment by AlexBuzaev75** [comment]
Yes, I am attached in screenshot

пн, 30 янв. 2023 г. в 17:59, Mathieu Westphal ***@***.***>:

**Comment by mwestphal** [comment]
We cant see anything, please use github interface instead of mail: https://github.com/f3d-app/f3d/issues/585

**Comment by AlexBuzaev75** [comment]
![qwe](https://user-images.githubusercontent.com/123960243/215517759-e4718df1-ffdb-42af-80fc-6bdfa49746fb.png)
Attached

**Comment by mwestphal** [comment]
I'm afraid that is not enough to help you.

**Comment by Meakk** [comment]
You should probably try with Mesa:  
- Download https://github.com/pal1000/mesa-dist-win/releases/download/22.0.1/mesa3d-22.0.1-release-msvc.7z
- Extract and copy opengl32.dll, libglapi.dll, libgallium_wgl.dll in the same folder than f3d.exe

**Comment by AlexBuzaev75** [comment]
Yes, it's now work
Thank you very much

вт, 31 янв. 2023 г. в 16:07, Michael MIGLIORE ***@***.***>:

**Comment by mwestphal** [comment]
For reference, this is written here:

https://f3d.app/doc/user/LIMITATIONS_AND_TROUBLESHOOTING.html#windows
