### ISSUE TITLE
GLTF crash

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#59]
The app is crashing when trying to load this file:
https://github.com/mrdoob/three.js/blob/master/examples/models/gltf/LittlestTokyo.glb
It's most likely related to the DRACO compression.

**Comment by mwestphal** [comment]
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8670

**Comment by mwestphal** [comment]
FYI @Meakk

**Comment by Meakk** [comment]
Nice, thanks! 👍
