### ISSUE TITLE
FBX Normal Mapping is not working

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#603]
**Describe the bug**
A model with normal maps in FBX format is not shown with a normal map

**To Reproduce**
 1. Open fbx file with normal mapping ([normal.zip](https://github.com/f3d-app/f3d/files/10609684/normal.zip))

 3. Normal mapping is not visible
 4. normal.fbx : no normal, even though normal code is being executed
 
![fbx](https://user-images.githubusercontent.com/3129530/216788447-2e59ae9c-039d-459d-ae56-e3b3edd62fc3.png)

 5. normal.glb: normal is working great

![glb](https://user-images.githubusercontent.com/3129530/216788451-176b4953-0e2a-48c0-84ac-e1d35c7dcb12.png)

**Expected behavior**
Normal mapping should be visible

the fbx has been tested in Windows 3D viewer and works great.

**Comment by mwestphal** [comment]
@Meakk PTAL

**Comment by Meakk** [comment]
That's because there is no tangents generated by the assimp importer. Let me check if I can fix that easily.
