### ISSUE TITLE
DAE with UTF16LE data is not loaded

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#614]
**Describe the bug**
A dae dataset with UTF16LE data is not loaded

**To Reproduce**
 0. [cube_UTF16LE.dae.zip](https://github.com/f3d-app/f3d/files/10611454/cube_UTF16LE.dae.zip)
 1. Open the file using `f3d --dry-run cube_UTF16LE.dae`
 2. Empty

```
Warning: In vtkF3DAssimpImporter.cxx, line 584
vtkF3DAssimpImporter (0x5638eea97eb0): Assimp failed to load: /home/glow/aur/assimp/src/assimp-5.2.1/test/models/Collada/cube_UTF16LE.dae


Warning: In vtkF3DAssimpImporter.cxx, line 587
vtkF3DAssimpImporter (0x5638eea97eb0): Assimp error: Unable to read file, malformed XML

```

**Expected behavior**
![a](https://user-images.githubusercontent.com/3129530/216829832-cf76d782-2fd9-4cca-9ead-76fa51460380.png)

**System Information:**
 - OS: Linux and Windows
 - GPU and GPU driver:

**F3D Information**
Paste the content of `f3d --version`: 1.3.1 and master

**Comment by shambhupatil** [comment]
Not sure why, but I'm able to open the file with no issue.

**Comment by mwestphal** [comment]
Which version of assimp are you using ?

**Comment by shambhupatil** [comment]
It was v5.4.0. The one CI uses.

**Comment by mwestphal** [comment]
confirmed working
