### ISSUE TITLE
Apple Silicon Binary

### ISSUE THREAD

**Issue by Ramalama2** [f3d-app/f3d#626]
Hi Boys, as this here is the only nice step viewer that exists on macos, is it possible to compile an M1/M2 (Apple Silicon) Binary?
Or lets say that should be an Armv8a Binary, almost the same as for android, just for macos.

Or would this require to make the code, xcode compatible? Since its the only compiler that can compile for apple silicon?

Thanks btw! Great Project!

**Comment by mwestphal** [comment]
Hi @Ramalama2 

You can install F3D with brew on Mac M1: https://formulae.brew.sh/formula/f3d

We would love to provide  a Mac M1 binary as well but with hardware to test with, this is not possible for us. Please consider donating if that matters to you :)

https://github.com/sponsors/f3d-app

**Comment by Ramalama2** [comment]
> Hi @Ramalama2
> 
> You can install F3D with brew on Mac M1: https://formulae.brew.sh/formula/f3d
> 
> We would love to provide a Mac M1 binary as well but without hardware to test with, this is not possible for us. Please consider donating if that matters to you :)
> 
> https://github.com/sponsors/f3d-app

Hey @mwestphal 
Thx for the fast reply!
Im using f3d for macos already (over Rosetta).
Don't need brew for that, the dmg's you provide are working absolutely perfect.
If i need the executable in terminal or somewhere else i can simply symlink it from the app folder to /usr/bin etc...

Just wondered that no one asked the same already, I've searched and seems like no one cares.
Looks for me like macbook owners or apple users are all either video editors or photographers, lol.
Maybe there are some netflixers and websurfers, but nothing else 😂

I will donate then, but that won't bring you an macbook, but till that point i can at least contribute with testings or probably compile if you would tell me, what i have to change in the code to support a new platform 🙈

Hopefully things will change when fusion arrive finally at mid this year on apple silicon. Or inventor in 2025 😂

Cheers

**Comment by mwestphal** [comment]
> but till that point i can at least contribute with testings or probably compile if you would tell me, what i have to change in the code to support a new platform

That would indeed ba a first step. We have a superbuild that will build all the dependencies and create a package, you can take a look:
https://github.com/f3d-app/f3d-superbuild

Let me know if you have any questions with this.

**Comment by mwestphal** [comment]
And thanks for the sponsoring ! <3

**Comment by mwestphal** [comment]
Do not hesitate to come to our discord: https://discord.gg/XkUh2h7z

**Comment by Ramalama2** [comment]
> > but till that point i can at least contribute with testings or probably compile if you would tell me, what i have to change in the code to support a new platform
> 
> That would indeed ba a first step. We have a superbuild that will build all the dependencies and create a package, you can take a look: https://github.com/f3d-app/f3d-superbuild
> 
> Let me know if you have any questions with this.

Awesome, Thanks!
I will try and ask then in discord if i have questions.
Thanks very much!

**Comment by mwestphal** [comment]
Hi @Ramalama2 !

We have changed what you get from the different tier and I'm happy to say that you can have access to a dedicated room in our discord:

https://discord.f3d.app

There you will be able to vote for issues you would like us to fix/implement, once a month.

No obligation of course, thanks for your sponsoring !
