### ISSUE TITLE
Windows Nightly package do not install file associations as expected

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#628]
Since switching to the superbuild, FileAssociations are not working anymore on windows. This is caused by `F3D_FILE_ASSOCIATION_NSIS` not set in the superbuild.

An easy fix is to set it manually in the CMakeCache in the CI. A better fix is to recover the information from a F3DConfig.cmake.

**Comment by mwestphal** [comment]
Needs a F3DProvidedPlugins.json

**Comment by Meakk** [comment]
JSON files are generated in `${install}/share/f3d/plugins`, the next step is to read them in the superbuild.
