### ISSUE TITLE
[Windows] Desktop shortcut icon is not hidpi

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#631]
**Describe the bug**
Looks like modern applications have bigger and cleaner icons (see icons on the left vs icons on the right)

<img width="136" alt="image" src="https://user-images.githubusercontent.com/6069752/219302540-5ea6354d-8166-4b55-b056-e4732f989a4f.png">

**Comment by mwestphal** [comment]
Not windows specific, but I agree that F3D icon should be modernized.

**Comment by mwestphal** [comment]
Tested but I do not replicate the initial issue anyway.

1.3.1:

[![1 3](https://user-images.githubusercontent.com/3129530/220698760-b0d57d6d-a9cb-41d4-942d-6529c2fcb7f3.PNG)
](url)

master:

![master](https://user-images.githubusercontent.com/3129530/220698821-bea07405-c0fe-4a23-b31f-29233d5d68fd.PNG)
