### ISSUE TITLE
cmake with error during "F3D_PLUGIN_BUILD_ASSIMP on

### ISSUE THREAD

**Issue by Jenfong** [f3d-app/f3d#643]
**Describe the bug**
cmake with error during "F3D_PLUGIN_BUILD_ASSIMP" on

**To Reproduce**
 1. F3D master
 ```shell
[dev@localhost f3d]$ git branch
* master
[dev@localhost f3d]$ git pull
[dev@localhost f3d]$ git log
commit 503ba376452f3a64f821efc4b6e1b0aa3ad015fe (HEAD -> master, origin/master, origin/HEAD)
Merge: b33df6d 62b3e01
Author: Mathieu Westphal <mathieu.westphal@gmail.com>
Date:   Tue Mar 7 08:11:21 2023 +0100
```
 2. `mkdir build;cd build;`
 3. `cmake .. -DBUILD_TESTING=OFF -DF3D_PLUGIN_BUILD_ASSIMP=ON -DF3D_BINDINGS_JAVA=ON `

**Error info**
```shell
-- Configuring done (1.9s)
CMake Error in plugins/assimp/module/CMakeLists.txt:
  Imported target "assimp::assimp" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Expected behavior**
cmake corrected with assimp 

**System Information:**
 - OS: Fedora 37
 - GPU and GPU driver:

**F3D Information**
master (the lastest commit :503ba376452f3a64f821efc4b6e1b0aa3ad015fe)

**Additional context**
pls refer #https://github.com/assimp/assimp/issues/4474#issuecomment-1458326430

**Comment by mwestphal** [comment]
Hi @Jenfong 

How was assimp installed on your machine ?

**Comment by Jenfong** [comment]
> Hi @Jenfong
> 
> How was assimp installed on your machine ?
`sudo dnf install assimp*`

**Comment by mwestphal** [comment]
Thanks for sharing this work around!
