### ISSUE TITLE
Github migration

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#65]
- [x] Migration of repo
- [x] CI: #61 
- [x] Website: #66 
- [x] Issues 
- [x] Releases
- [x] MRs to PRs
- [x] Archive gitlab
- [x] reddit pass
- [x] blog pass
- [x] discourse pass
- [x] other websites pass
- [x] brew package
- [x] aur package
- [x] freebsd: comment below
- [x] nixpkgs: https://github.com/NixOS/nixpkgs/pull/147173
- [x] flathub: https://github.com/flathub/com.kitware.F3D/issues/25
- [x] OpenSuse community: https://build.opensuse.org/package/show/home:AndnoVember:Debian/f3d
- [x] Upcoming debian package : ongoing
- [x] GLTF Project Expolorer: https://github.com/KhronosGroup/glTF-Project-Explorer/pull/130
- [x] https://github.com/nschloe/awesome-scientific-computing : https://github.com/nschloe/awesome-scientific-computing/pull/76

**Comment by mwestphal** [comment]
@Meakk could you take care of closing and migrating the remaining gitlab MRs ?

**Comment by mwestphal** [comment]
@yurivict : please note F3D has migrated repository. I could not find a way to open an issue on freshports.

**Comment by mwestphal** [comment]
@bcdarwin : please note F3D has migrated repository. I could not find a way to open an issue on nixpkgs.

**Comment by yurivict** [comment]
> please note F3D has migrated repository. I could not find a way to open an issue on freshports.

For FreeBSD ports the right place is https://bugs.freebsd.org/bugzilla/ , but there's no need any more now, I'll update the port soon.

**Comment by bcdarwin** [comment]
For future reference, for Nixpkgs the issue tracker is at github.com/NixOS/nixpkgs but in the present instance I've already opened a PR.

**Comment by mwestphal** [comment]
Thanks for the info @bcdarwin @yurivict !

**Comment by mwestphal** [comment]
@Meakk : suggestion for f3d aur package:

```
# Maintainer: Michael Migliore <mcmigliore+aur@gmail.com>

export GIT_LFS_SKIP_SMUDGE=1
pkgname=f3d
pkgver=1.1.1
pkgrel=1
pkgdesc='A fast and minimalist 3D viewer'
arch=('x86_64')
url="https://gitlab.kitware.com/${pkgname}/${pkgname}"
license=('BSD')
depends=('vtk' 'ospray')
makedepends=('git' 'git-lfs' 'cmake')
source=("https://github.com/$pkgname-app/$pkgname/archive/refs/tags/v$pkgver.tar.gz")
sha256sums=('68bdbe3a90f2cd553d5e090a95d3c847e2a2f06abbe225ffecd47d3d29978b0a')

build() {
  cd "$srcdir/$pkgname-$pkgver"
  mkdir -p build
  cd build
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_TESTING=OFF \
        -DF3D_INSTALL_DEFAULT_CONFIGURATION_FILE=ON \
        ..
  make
}

package() {
  cd "$srcdir/$pkgname-$pkgver/build"
  make DESTDIR="$pkgdir" install
}
```

**Comment by mwestphal** [comment]
@Meakk :  suggestion for f3d-git aur package

```
# Maintainer: Michael Migliore <mcmigliore+aur@gmail.com>

export GIT_LFS_SKIP_SMUDGE=1
_name=f3d
pkgname=$_name-git
pkgver=v1.1.0.r133.ge68d74a
pkgrel=1
pkgdesc='A fast and minimalist 3D viewer'
arch=('x86_64')
url="https://github.com/$_name-app/$_name"
license=('BSD')
depends=('vtk' 'ospray' 'opencascade')
makedepends=('git' 'git-lfs' 'cmake')
provides=('f3d')
conflicts=('f3d')
source=("git+https://github.com/$_name-app/$_name.git")
sha256sums=('SKIP')

pkgver() {
    cd "$_name"
    git describe --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd "$srcdir/$_name"
  mkdir -p build
  cd build
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DF3D_MODULE_OCCT=ON \
        -DF3D_MODULE_RAYTRACING=ON \
        -DF3D_INSTALL_DEFAULT_CONFIGURATION_FILE=ON \
        ..
  make
}

package() {
  cd "$srcdir/$_name/build"
  make DESTDIR="$pkgdir" install
}
```

**Comment by mwestphal** [comment]
@Meakk : please update brew package when you can.

**Comment by mwestphal** [comment]
website and brew package will be updated with 1.2 release
