### ISSUE TITLE
.ply files have the wrong color

### ISSUE THREAD

**Issue by DesiOtaku** [f3d-app/f3d#750]
You can see the .ply model here: https://gitlab.com/cleardental/dentalfloss3dmodels/-/blob/main/Typo_Dont/UpperJawScan.ply

The colors when loading the model is completely off.

Correct version:
![Screenshot_20230421_134613](https://user-images.githubusercontent.com/410561/233702084-22aa1cd7-8c05-4687-826e-5188b2c2befb.png)

Incorrect version using the 2.0 version of f3d:
![Screenshot_20230421_134412](https://user-images.githubusercontent.com/410561/233702176-313ccf92-3cd4-4a42-849e-40e3b4802dda.png)

**Comment by mwestphal** [comment]
With .ply, by default the coloring uses magnitude instead of direct scalars, press Y until you switch to direct scalars mode.

(or `--comp=-2` in the command line, which you can set in your config files.

![correct](https://user-images.githubusercontent.com/3129530/233702369-dcaa7306-39aa-4bef-abbe-2fd27b50a659.png)

Is it standard to have RGB like that in .ply files  ? That is not something usual, that is why we did not configure it.

**Comment by DesiOtaku** [comment]
> Is it standard to have RGB like that in .ply files ? That is not something usual, that is why we did not configure it.

The .ply file is the output from a dental scanner (3Shape TRIOS). At least in the dental world, all the .ply files should have color similar to this file; but I don't know if other .ply files outside the dental world would be magnitude as well.

**Comment by mwestphal** [comment]
Looking at random test data from assimp or three.js, I dont see any RGB channel on it.

Maybe we should consider progressing on the specific config file issue: #28 

Wdyt @Meakk ?

**Comment by Meakk** [comment]
I don't think PLY files are used for scientific data requiring color mapping. Maybe we should just force direct coloring in the default config file?

**Comment by mwestphal** [comment]
According to wikipedia:

> A variety of properties can be stored, including color and transparency, surface normals, texture coordinates and data confidence values.

So color and transparency **can** be present but it is not systematic. Hard to say what is the right choice here.

**Comment by mwestphal** [comment]
hi @DesiOtaku 

This is now fixed in master, you can wait for the next release OR you can just download the nightly: https://github.com/f3d-app/f3d/releases/tag/nightly

**Comment by DesiOtaku** [comment]
Thanks. I'll try it later this week.
