### ISSUE TITLE
F3D ignores Command-Q, standard system-wide quit shortcut on macOS

### ISSUE THREAD

**Issue by epsimatic** [f3d-app/f3d#753]
**Describe the bug**

F3D ignores standard macOS system-wide keyboard shortcuts, like <kbd>⌘Q</kbd>, <kbd>⌘H</kbd>, <kbd>⌘M</kbd>

**To Reproduce**
Steps to reproduce the behaviour:

1. Start `f3d` on Mac with no arguments 
2. Press <kbd>Command</kbd> + <kbd>Q</kbd> (<kbd>⌘Q</kbd>)

**Expected behaviour**

Program quits

**Observed behaviour**

Program flips «Ambient occlusion» option (that's action on <kbd>Q</kbd>)

**System Information:**
 - OS: macOS 13.3.1 (22E261) / Apple M1 Pro

**F3D Information**
Paste the content of `f3d --version`:

```
F3D 2.0.0

F3D - A fast and minimalist 3D viewer
Version: 2.0.0.
Build date: 2023-04-20 17:06:45.
Build system: Darwin 64-bits.
Compiler: AppleClang 14.0.0.14000029.
External rendering module: ON.
Raytracing module: OFF.
VTK version: 9.2.6 (build 20230224).
```

**Additional context**

Other shortcuts that work in nearly every app, but don't work in F3D:

- <kbd>⌘Q</kbd> → Quit
- <kbd>⌘H</kbd> → Hide window
- <kbd>⌘M</kbd> → Minimise window
- Probably more. See the list below

---

Cross-checked it on Linux (EndeavourOS latest, Gnome 43 DE), and it quits by using standard Quit keyboard shortcut (customizable in gnome-settings → Keyboard) _in addition_ to <kbd>Esc</kbd>.

I actually thought these shortcuts are processed by the system and your app receives the quit / hide / minimise intent. Probably that's usually the case but you intercept keyboard events in a different way that stops the system from receiving those shortcuts.

---

Also, Apple HIG [[says](https://developer.apple.com/design/human-interface-guidelines/inputs/keyboards)](https://developer.apple.com/design/human-interface-guidelines/inputs/keyboards):

> Respect standard keyboard shortcuts. People expect the standard keyboard shortcuts to work, regardless of the app they’re using. You can also help people learn your app quickly by supporting the system-defined keyboard shortcuts that make sense in your app. 

Later on the same page it describes Command + Q as a quit shortcut, and others too.

**Comment by mwestphal** [comment]
We definitely do not have anything for to process system provided event to quit. We would have to check on an actual macOS system what happens when such event is triggered.

FYI @Meakk

**Comment by Meakk** [comment]
Noticed this issue as well. Might be an issue in the cocoa implementation in VTK capturing the command+Q event.
