### ISSUE TITLE
Scalars colouring defaults to Normal, makes STEP files look weird

### ISSUE THREAD

**Issue by epsimatic** [f3d-app/f3d#754]
**Describe the bug**

- On macOS, **Scalars coloring** is set to [Normal] by default and that makes STEP files look weird
- On Linux (add: with broken config) Scalars coloring is set to [OFF]

**To Reproduce**
Steps to reproduce the behaviour:

0. Get a fresh install of F3D 2.0.0 on macOS
1. Download [this](https://github.com/f3d-app/f3d/files/11300217/95165A619_Strong-Hold.Quick-Release.Pin.STEP.zip) file (or download STEP from [[here](https://www.mcmaster.com/95165A619/)](https://www.mcmaster.com/95165A619/) )
2. Start `f3d "95165A619_Strong-Hold Quick-Release Pin.STEP"`
3. Observe weird colouring
4. Press <kbd>H</kbd>
5. Notice: `Scalars coloring: [Normal]`

**Expected behaviour**

`Scalars coloring: [OFF]` and file renders as an uniform grey body

**Observed behaviour**

`Scalars coloring: [Normal]` and file renders in yellow-red spotty palette

| Mac | Expected behaviour (Linux) |
|---|---|
| ![](https://user-images.githubusercontent.com/1821846/233760872-27544237-2cb5-44c3-bc8f-1151cf22f89f.png) | ![](https://user-images.githubusercontent.com/1821846/233760885-01c117b3-679a-4385-918d-682616a1126f.png) |

**System Information:**
 - OS: macOS 13.3.1 (22E261) 
 - Cross checked on EndeavourOS latest / Gnome 43 / Wayland

**F3D Information**
Paste the content of `f3d --version`:

```
F3D 2.0.0

F3D - A fast and minimalist 3D viewer
Version: 2.0.0.
Build date: 2023-04-20 17:06:45.
Build system: Darwin 64-bits.
Compiler: AppleClang 14.0.0.14000029.
External rendering module: ON.
Raytracing module: OFF.
VTK version: 9.2.6 (build 20230224).
```

**Additional context**

Cross-checked it on Linux (EndeavourOS latest, Gnome 43 DE, Wayland), and it behaves as expected.

I'm sure I didn't make any changes to config files.

**Comment by mwestphal** [comment]
This is caused by the naming of the file. We expect STEP files to have the `.step` extension in the configuration file logic.

TBF I'd have expected this file to not even be openable at all when F3D checks that the reader can open it.


Wdyt @Meakk ? Should we force the config file regexp to be case insensitive ?


> Cross checked on EndeavourOS latest / Gnome 43 / Wayland

Your linux installation does not have config files for some reasons, but lets debug this in the other issue.

**Comment by epsimatic** [comment]
> This is caused by the naming of the file. We expect STEP files to have the `.step` extension in the configuration file logic. If you rename your file, this issue will go away.

That's why I pointed at McMaster-Carr website, they are a major player and they distribute those files.

> TBF I'd have expected this file to not even be openable at all when F3D checks that the reader can open it.

Do I feel like it's a bad idea? I like my picture viewer to try opening *any* picture with any, wrong and broken, extension, and I  like my video player doing the same. Why not handle files by their magic signature, not by extension?

> Your linux installation does not have config files for some reasons, but lets debug this in the other issue.

Please dismiss it. I've used Arch AUR package because I was lazy, the official package is still at 1.3.1 or so.

**Comment by mwestphal** [comment]
> Do I feel like it's a bad idea? 

YOu are right, we definitely should be able to open this file, I'm just trying to understand how it works. We will definitely fix this. Thanks for raising the issue.

> I've used Arch AUR package because I was lazy, the official package is still at 1.3.1 or so.

We need to update the AUR package, a bit too busy with the release right now.

**Comment by epsimatic** [comment]
Can confirm that after fixing F3D config (#752 ) it shows the same way on Linux

![Снимок экрана от 2023-04-22 17-12-38](https://user-images.githubusercontent.com/1821846/233780861-d6626dfb-7a5f-47cd-a6d7-2fe9b0f82274.png)

**Comment by Meakk** [comment]
> Wdyt @Meakk ? Should we force the config file regexp to be case insensitive ?

Yes I think so

**Comment by mwestphal** [comment]
Hi @epsimatic 

This is now fixed in master, you can wait for the next release OR you can just download the nightly: https://github.com/f3d-app/f3d/releases/tag/nightly
