### ISSUE TITLE
Respect model origin when displaying scene

### ISSUE THREAD

**Issue by epsimatic** [f3d-app/f3d#755]
**Is your feature request related to a problem? Please describe.**
When F3D opens an object, it puts the body on the ground plane, then centres it on two remaining axes, losing the model's origin in the process

**Describe the solution you'd like**
I'd like an option (I'd like it to be enabled by default) to keep the model's origin and place the model in the viewport scene according to the model creator's intent.

**Describe alternatives you've considered**

- An option: **Model placement: Origin / Centred**
- A hotkey to switch it
- A default in the config
- Model's origin displayed in the viewer

**Additional context**

The way F3d centres model mimics the behaviour of 3D slicer software like PrusaSlicer.   
It's desirable for a slicer (that can't print under the ground plane, can't print in air and have limited build plate dimensions), but that's completely irrelevant to a 3D viewer.

It might be desirable in some cases (Like a scene with an object that's moved way off the origin due to human error).

In other cases, it isn't:
- You're dealing with multi-component model split into several files in the same origin (ex.: multicoloured prints)
- The origin has a special meaning (an attachment point, or swivel point) 
- probably more

--

**I've made a test part** that contains 2 cubes, starting at world's origin: [origin-cubes.obj.zip](https://github.com/f3d-app/f3d/files/11300324/origin-cubes.obj.zip) (human-readable, you can see everything starts at 0), [FreeCAD source origin-cubes.FCStd.zip](https://github.com/f3d-app/f3d/files/11300325/origin-cubes.FCStd.zip)

You can notice F3D completely ignores model's origin on every axis.

| FreeCAD source | OJB in Meshlab | OBJ in F3D |
| --- | --- | --- |
| ![freecad](https://user-images.githubusercontent.com/1821846/233764267-d7ea7e03-0303-41be-95aa-1c1472c4440b.png) | ![meshlab](https://user-images.githubusercontent.com/1821846/233764285-38ca4adc-ba5e-490e-9a8e-8899616b62fb.png) | ![f3d](https://user-images.githubusercontent.com/1821846/233764293-e64c6b33-c446-4f7b-b7ff-e99792a5552d.png) |

**Contribution**
I probably can't contribute in this

**Comment by mwestphal** [comment]
F3D rely on the vtkOBJImporter and vtkOBJReader, so that looks like a VTK issue or limitations, needs to be investigated.

**Comment by snoyer** [comment]
> F3D rely on the vtkOBJImporter and vtkOBJReader, so that looks like a VTK issue or limitations, needs to be investigated.

The models are fine, you can check that by loading 2 different objects and they will be correctly positioned _relative to each other_... 

> When F3D opens an object, it puts the body on the ground plane, then centres it on two remaining axes, losing the model's origin in the process

It's actually the other way around, _the grid_ is positioned below the model (according to the up direction).
https://github.com/f3d-app/f3d/blob/f9a4778c219a9cae1b7ed1db8cefa2ebe3982150/library/VTKExtensions/Rendering/vtkF3DRenderer.cxx#L430-L435

This is good news because that will be easier to fix.

**Comment by mwestphal** [comment]
I completely misunderstood the issue !

Is it not just a matter of using `--up=+X` then ?

**Comment by mwestphal** [comment]
Ok, got it, @epsimatic want the grid to be positioned at the origin instead of being placed below the model. That is a reasonnnable request and should indeed be fairly simple. We still need to respect the --up as there is no way to guess it.

**Comment by snoyer** [comment]
Just need to decide on the UI and defaults I guess
```cpp
      double gridPos[3] = {0,0,0};
      if(something_something){
        for (int i = 0; i < 3; i++)
        {
          double size = bounds[2 * i + 1] - bounds[2 * i];
          gridPos[i] = 0.5 * (bounds[2 * i] + bounds[2 * i + 1] - this->UpVector[i] * size);
        }
      }
```
