### ISSUE TITLE
f3d archlinux package do not support plugins compilation

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#757]
**Describe the bug**
When installing the f3d archlinux package (maintained by @svenstaro) or f3d-git from the aur (maintainded the F3D maintainers), it is not possible to configure a plugin

**To Reproduce**
 1. 
 
 ```
yay -S f3d-git
cd example/plugins/example-plugin
mkdir build
cd build
cmake ../
```

 2.
 ```
 -- Configuring done (0.8s)
CMake Error at /usr/lib/cmake/vtk/VTK-targets.cmake:555 (set_target_properties):
  The link interface of target "VTK::nlohmannjson" contains:

    nlohmann_json::nlohmann_json

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/lib/cmake/vtk/vtk-config.cmake:138 (include)
  /usr/lib/cmake/f3d/f3dPlugin.cmake:157 (find_package)
  example-plugin/CMakeLists.txt:19 (f3d_plugin_build)


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

 ```
 

**Expected behavior**
Configure and build fine

**System Information:**
 - OS: ArchLinux

**Additional context**
This very well may be an issue with the VTK package of arch linux, but investigation is needed on our part before opening an bugreport there.

**Comment by Meakk** [comment]
Is it fixed if you install `nlohmann-json` Arch Linux package?

**Comment by mwestphal** [comment]
It is already installed
