### ISSUE TITLE
Shell extension for F3D file thumbnails not working when UAC is disabled

### ISSUE THREAD

**Issue by boromyr** [f3d-app/f3d#758]
## Describe the bug
The shell extension for CAD file thumbnails does not work when UAC (User Account Control) is disabled. As a result, F3D file thumbnails are not displayed.

## To Reproduce
1. Disable UAC from the operating system control panel.
2. Open Windows Explorer and navigate to a folder containing an F3D file.
3. The F3D file thumbnail is not displayed.

## Expected behavior
The F3D file thumbnail should be displayed even when UAC is disabled.

## System Information
- OS: Windows 11 22H2

## F3D Information
2.0.0 and earlier

**Comment by mwestphal** [comment]
I'm using Windows 10.0.19044 and am unable to reproduce.

Could you check on your side @Meakk ?

**Comment by boromyr** [comment]
Maybe it's a problem only present in Windows 11

**Comment by boromyr** [comment]
Weird, I also tried on a virtual machine and had the same problem. What version of Windows 11 did you try so I try to install the same version?

**Comment by mwestphal** [comment]
Lets try to find other Windows 11 users

**Comment by Meakk** [comment]
> What version of Windows 11 did you try so I try to install the same version?

Version 10.0.22621

Do you need to have UAC disabled when F3D is installed, or disabling it after the installation causes issue as well?

**Comment by boromyr** [comment]
@Meakk I had the same problem both installing with UAC disabled (and then re-enabled) and with UAC enabled. It's a common issue with preview handlers to have UAC disabled.
Tomorrow I'll try a clean installation of Windows 11 in a virtual machine and post the results.

**Comment by mwestphal** [comment]
@boromyr any news on the tests ?

**Comment by mwestphal** [comment]
@boromyr closing without feedback, feel free to reopen if you reproduce.
