### ISSUE TITLE
HDRi set in config file is not loaded when loading a file

### ISSUE THREAD

**Issue by misakieku** [f3d-app/f3d#765]
**Describe the bug**
I wrote `"hdri": "Cobblestone_Road_sm.hdr`" in 10_global.jason and reopen the f3d, but can't make HDRI work.

**To Reproduce**
 1. Open 10_global.jason
 2. insert `"hdri": "Cobblestone_Road_sm.hdr"` in the global module
 3. reopen f3d

**Expected behavior**
nothing in counsel

**System Information:**
 - OS: window 11
 - GPU and GPU driver: rtx 2060, Nvidia studio 531.61

**Comment by mwestphal** [comment]
Hi @misakieku 

This should work if you put the full path to the HDRi, eg:

"hdri": "C:/path/to/Cobblestone_Road_sm.hdr" 

Let us know

**Comment by misakieku** [comment]
> Hi @misakieku
> 
> This should work if you put the full path to the HDRi, eg:
> 
> "hdri": "C:/path/to/Cobblestone_Road_sm.hdr"
> 
> Let us know

Even if I put the file inside the bin folder?

**Comment by mwestphal** [comment]
yes, we dont try to find an HDRi relative to the bin folder I'm afraid.

maybe we should, but in thqt case I'd rather have a dedicate resources folder to store HDRis in instead.

**Comment by misakieku** [comment]
> yes, we dont try to find an HDRi relative to the bin folder I'm afraid.
> 
> maybe we should, but in that case I'd rather have a dedicate resources folder to store HDRis in instead.

OK. I find out that hdri will be working if I only open f3d and don't import any model. However, as soon as I import any model into f3d, hdri will be gone.

**Comment by mwestphal** [comment]
Sounds like a bug. I will try to reproduce.

**Comment by mwestphal** [comment]
@misakieku , sorry, no workaround apart from setting the hdri from command line with `--hdri`

**Comment by mwestphal** [comment]
Hi @misakieku 

This is now fixed in master, you can wait for the next release OR you can just download the nightly: https://github.com/f3d-app/f3d/releases/tag/nightly
