### ISSUE TITLE
Cannot register F3D in PATH when installing with NSIS

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#768]
When installing with the official package, registering in PATH can fail because there are too many entries already.  
It's not really F3D fault but we need to add something in the troubleshooting section or find a workaround.  
See https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell

**Comment by mwestphal** [comment]
Here is how the errors look:

![image](https://user-images.githubusercontent.com/3129530/234241478-79cdb860-ddbf-41da-a1cf-45866f130d01.png)

**Comment by mwestphal** [comment]
For referencing:

`Warning! PATH too long installer unable to modify PATH!`

**Comment by mwestphal** [comment]
According to @Fia3D this is a NSIS issue and I tend to agree:

 - https://github.com/SWI-Prolog/swipl-devel/issues/450
 - https://swi-prolog.discourse.group/t/unable-to-modify-path-during-installation/934
 - https://gitlab.com/graphviz/graphviz/-/issues/1770
 - https://nsis.sourceforge.io/Path_Manipulation
 
 This may be fixable on our end.

**Comment by mwestphal** [comment]
lets add something to the troubleshooting section at least
