### ISSUE TITLE
It's unclear to me how to set F3D_MODULE_OCCT option when building from AUR

### ISSUE THREAD

**Issue by Toughbook-CFC2** [f3d-app/f3d#78]
Hey, I'm sorry if this is not the right place for this, but I didn't know where else to put it. 
I want to use f3d to view .stp files. This is very convenient for use with project specific files for KiCAD.
I've looked into this for a while now and so far come up with nothing. How can I pass the mentioned parameter
to CMake, when I get my package from the AUR and build with makepkg ?
A small addition to the README would be greatly appreciated.
Thank you very much

**Comment by Meakk** [comment]
The OpenCascade module is not included in the `1.1.1` release.  
So you have to use the `f3d-git` AUR package.  
You just have to add `-DF3D_MODULE_OCCT=ON \` and add `opencascade` in the `depends` list.

**Comment by Toughbook-CFC2** [comment]
Thank you !

**Comment by Meakk** [comment]
I'm closing the issue, feel free to reopen it if you have more questions.  
I'll push the modification to the AUR when I find time.
