### ISSUE TITLE
USD Format support

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#780]
During the release 2.0.0, it appeared that many users are looking for .usd support, let's try to add it

**Comment by Meakk** [comment]
I have experience with the USD framework. It's a bit painful to use it with their plugin system but I agree it's important to support it.

**Comment by mwestphal** [comment]
https://github.com/f3d-app/f3d/pull/819

**Comment by mwestphal** [comment]
Should I move that to 2.3 ? @Meakk

**Comment by mwestphal** [comment]
- Merged in #819
- Packaged in https://github.com/f3d-app/f3d-superbuild/pull/124

**Comment by mwestphal** [comment]
Hey @philvoyer @Da3n0n @Vindaar @Lgt2x @superusercode, we are looking for nice looking USD file to share with the upcoming release, do you have anything to share ? :)
