### ISSUE TITLE
The command from the Gallery screen fails: Error parsing options: Option ‘r’ does not exist

### ISSUE THREAD

**Issue by yurivict** [f3d-app/f3d#79]
[gallery](https://f3d-app.github.io/f3d/gallery/)

```
$ f3d 202.vtp -xtgans -rd --samples=10 --range=-2,9
Error parsing options: Option ‘r’ does not exist
```

**Comment by Meakk** [comment]
That's because your f3d version is built without raytracing support.

**Comment by yurivict** [comment]
configure doesn't say that somethings is missing, and doesn't print the summary of options. There's no such option in CMakeLists.txt

How to enable raytracing support?

**Comment by mwestphal** [comment]
for version 1.1.1, you need to install ospray and build VTK with raytracing support, then F3D will detect it automatically.

**Comment by mwestphal** [comment]
This is already documented in the ReadMe, so I will go ahead and close this, but if you need further help @yurivict , do not hesitate to ask.

```
VTK >= 9.0.0 (optionally with raytracing capabilities to enable OSPray rendering).
```
