### ISSUE TITLE
Helps of packaging into Fedora

### ISSUE THREAD

**Issue by topazus** [f3d-app/f3d#801]
I recently made a package review request of f3d on Bugzilla, but there are some problems needs to be dealt.

> Comments:
a) Main license seems to be BSD-3-Clause with a few files under MIT license.  Is it possible
to add a license breakdown in the spec file?
b) Can the Java bindings also be built?
c) Can files in external directory be obtained from those packaged in Fedora?
https://github.com/f3d-app/f3d/blob/master/external/json.hpp
https://github.com/f3d-app/f3d/blob/master/external/cxxopts.hpp
If not, spec file should indicate they are bundled.
d) Building the example may be useful as a basic functionality test
e) Please use desktop-file-validate see
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_desktop_file_creation
f) libraries in main package should have sonames, in particular libf3d, plugin libraries used only
internally need not have sonames, but should then be in a subdirectory not in the LD_LIBRARY_PATH
g) devel package should have libraries without sonames, see
https://docs.fedoraproject.org/en-US/packaging-guidelines/C_and_C++/#_libraries
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_soname_handling
h) Where possible list file extensions used rather than just including an entire directory, for example
%files devel
%{_includedir}/f3d/*.h
%{_libdir}/cmake/f3d/*.cmake
%{_libdir}/cmake/f3d/*.in

see details: https://bugzilla.redhat.com/show_bug.cgi?id=2193288#c2

I need some explanations and information for the comment c) and f).

Also, I wonder the reasons why these following files are necessarily to be installed, https://github.com/f3d-app/f3d/blob/d822802bdbe6270cb492c9620f9f5af609b52750/library/CMakeLists.txt#L205-L208C34
```
      "${CMAKE_SOURCE_DIR}/cmake/plugin.cxx.in"
      "${CMAKE_SOURCE_DIR}/cmake/plugin.desktop.in"
      "${CMAKE_SOURCE_DIR}/cmake/plugin.thumbnailer.in"
      "${CMAKE_SOURCE_DIR}/cmake/readerBoilerPlate.h.in"
```

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2193288
https://topazus.fedorapeople.org/rpms/f3d.spec

**Comment by mwestphal** [comment]
> Can files in external directory be obtained from those packaged in Fedora?

No, these are header only libraries that we just put in F3D code.

> libraries in main package should have sonames, in particular libf3d, plugin libraries used only internally need not have sonames, but should then be in a subdirectory not in the LD_LIBRARY_PATH

That a good question. I think the libf3d should hafe a soname but we did not take care of it yet. Open an issue for that ?
In the meantime, you could move file around in your package to comply with fedora packaging constraints.

maybe @mzf-guest have some inputs here.

> plugin libraries used only internally need not have sonames, but should then be in a subdirectory not in the LD_LIBRARY_PATH

Intersting point that we did not consider at all. We could fix that in the future in F3D however F3D will look for plugins relatively to the binary location `../lib/libf3d-...`, so if you move them around plugin loading will not be automatic anymore.

Wdyt @Meakk ?

> Also, I wonder the reasons why these following files are necessarily to be installed,

This is the F3D plugin SDK, see https://github.com/YangShen398/F3D-ODB-Reader-Plugin for an example usage.

**Comment by topazus** [comment]
> No, these are header only libraries that we just put in F3D code.

I think he means if we can use system libraries of cxxopts and nlohmann-json by installing `cxxopts-devel` and `json-devel` fedora packages, instead of using the header files of [cxxopts.hpp](https://github.com/f3d-app/f3d/blob/master/external/cxxopts.hpp) and [json.hpp](https://github.com/f3d-app/f3d/blob/master/external/json.hpp) in the external directory.

**Comment by Meakk** [comment]
If we don't put plugins shared libraries in `/usr/lib`, what is the standard path?  
F3D internally use `dlopen` to load them, moving them outside of `LD_LOAD_LIBRARY` path is a problem in my opinion.

Regarding external libraries, it's probably easy to use system headers instead by enabling a CMake variable `F3D_USE_EXTERNAL_xxx`, we can add that even if I don't see the benefit since the libraries are header only.

**Comment by topazus** [comment]
> If we don't put plugins shared libraries in `/usr/lib`, what is the standard path?
> F3D internally use `dlopen` to load them, moving them outside of `LD_LOAD_LIBRARY` path is a problem in my opinion.

It seems that there is no standard directory of plugin shared libraries, but I think provide a `PLUGIN_INSTALL_DIR` option, so we can change the destination directory of `install()` to another location, maybe `${CMAKE_INSTALL_LIBDIR}/f3d` or `${CMAKE_INSTALL_LIBDIR}/f3d/plugins`? https://github.com/f3d-app/f3d/blob/0c1ee5d3e6085493f095d254a0afbd946a9b0b1b/cmake/f3dPlugin.cmake#L271-L277

Ref: https://github.com/casadi/casadi/commit/0a053710b045e9f672bff0ee475fe0c4dbe938c4
https://github.com/Unidata/netcdf-c/commit/ee5e1596f521542eb5d150725774e8a7f7c2ab4d

**Comment by Meakk** [comment]
Ok, sounds good, as ling as the default value stays `<prefix>/lib`

**Comment by bkmgit** [comment]
Fedora typically uses `<prefix>/lib64` but it need not be the default.

**Comment by bkmgit** [comment]
Using `${CMAKE_INSTALL_LIBDIR}/f3d/plugins` is good though, can change the value of `${CMAKE_INSTALL_LIBDIR}` appropriately

**Comment by mwestphal** [comment]
@bkmgit @topazus is external json and external cxxopts needed to move forward ?

**Comment by bkmgit** [comment]
If there are significant differences made, then bundling them is ok.
However, where possible being able to use the current packaged version
rather than bundling is preferred.

**Comment by mwestphal** [comment]
Ok, we will try to adress that.

**Comment by mwestphal** [comment]
I took a quick look, I think we need to update these dependencies first.

**Comment by mwestphal** [comment]
dedicated issue https://github.com/f3d-app/f3d/issues/830

Closing this one
