### ISSUE TITLE
Please make cmake print summary of main build options

### ISSUE THREAD

**Issue by yurivict** [f3d-app/f3d#81]
For example, is ```F3D_HAS_RAYTRACING``` set and why not if it isn't.

**Comment by Meakk** [comment]
Modularisation has been improved on master. Things should be clearer in v1.2.  
There are several `F3D_MODULE_` prefixed variables (including `F3D_MODULE_RAYTRACING`) with messages printed if required dependencies are missing.

**Comment by mwestphal** [comment]
I agree with @Meakk here, master output much more info about options, including RAYTRACING, closing this.
