### ISSUE TITLE
Add Support to EXR

### ISSUE THREAD

**Issue by Fia3D** [f3d-app/f3d#810]
**Is your feature request related to a problem? Please describe.**
OpenEXR is a really handy image format in graphics world and I use it to make some of my textures and almost all my hdri are in exr.

**Describe the solution you'd like**
Support hdri exr and also if possible textures.

**Describe alternatives you've considered**
I had to convert exr to hdr everytime I wanted to try an hdri, but the hdr format isn't easy to convert properly with the tools I use and getting informations about it is hard imo. I can also convert my texture to png in srgb colorspace but it would require I would loose color informations, for a finished model to use it's good but not for sharing with different workflow and colaborator.
 
Exr is used a lot for hdri now, even more when working with Blender and open source tools as the format is an open format.

More info about implementing it : https://openexr.com/en/latest/

**Comment by mwestphal** [comment]
EXR support should be added to VTK for that, but indeed would be nice to have.

**Comment by Meakk** [comment]
Started to work on it: #844

**Comment by mwestphal** [comment]
Right, doesn't need to be in VTK with the image reader factory stuff, nice.

**Comment by mwestphal** [comment]
Fixed by #844, but not available in the nightly yet. Will you take care of it @Meakk ?

**Comment by Meakk** [comment]
Added in the nightly in https://github.com/f3d-app/f3d-superbuild/pull/74

**Comment by mwestphal** [comment]
The next nightly will contain the feature.
