### ISSUE TITLE
Allow to hide hdri while using it's lightning environment 

### ISSUE THREAD

**Issue by Fia3D** [f3d-app/f3d#812]
**Is your feature request related to a problem? Please describe.**
When I try to generate thumbtails with hdri to have a better view of my different object (having a non flat light), the background transparency isn't here anymore. Can be also handy when previewing a model to have a dark background but an environnement lignting (like world opacity in blender preview mode)

**Describe the solution you'd like**
An option to have opacity / disabling of the skybox that is created in the scene when using hdri

**Describe alternatives you've considered**
Tried using a really blured image but it isn't enough

**Contribution**
I might be able to contribute this, but I don't know the project enough and I am not a C++ expert.

See : 
https://github.com/f3d-app/f3d/blob/890e478e14a16e6777beff8f12ce1768e2244d9d/library/VTKExtensions/Rendering/vtkF3DRenderer.cxx#L593-L599
or
https://github.com/f3d-app/f3d/blob/890e478e14a16e6777beff8f12ce1768e2244d9d/library/VTKExtensions/Rendering/vtkF3DRenderer.cxx#L180-L183

**Comment by mwestphal** [comment]
That would be nice. Is it a simple fix @Meakk ?

**Comment by mwestphal** [comment]
I tested your suggestion quickly @Fia3D and it works perfectly, I should be able to add that quickly

**Comment by mwestphal** [comment]
Not that quick after all, in any case, here it is: #932 

You can test the new options in the next nightly release @Fia3D :

`./bin/f3d --hdri-file=/path/to/file.hdr --hdri-ambient`
