### ISSUE TITLE
Popup appearing when scrolling fast in list of models with thumbnail not generated yet 

### ISSUE THREAD

**Issue by Fia3D** [f3d-app/f3d#813]
**Describe the bug**
A popup Press OK appear when f3d try to generate lots of thumbtail. Sometime if I open a file at same time this kind of popup appear, F3D can't load the model and write in console error alloc (I don't have the exact message for now)

**To Reproduce**
Scroll up and down in long list of file where thumbnail isn't generated.

**Expected behavior**
No popup.

**System Information:**
 - OS: Windows 10 
 - GPU and GPU driver: RTX 2060s 8GB / 531.61 (Studio Driver)

**F3D Information**
F3D 2.0.0

F3D - A fast and minimalist 3D viewer
Version: 2.0.0.
Build date: 2023-05-12 00:39:16.
Build system: Windows 64-bits.
Compiler: MSVC 19.34.31944.0.
External rendering module: ON.
Raytracing module: OFF.
VTK version: 9.2.6 (build 20230224).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2023 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

![image](https://github.com/f3d-app/f3d/assets/103204902/b66cfc1e-7cbf-4481-8575-ffa72aa23e27)

**Comment by mwestphal** [comment]
I can fix the popup but it means some of your models cant be opened by F3D.

**Comment by mwestphal** [comment]
Only "Exception" shows up with a popup.

**Comment by mwestphal** [comment]
Fixed and in the last nightly
