### ISSUE TITLE
Models are too dark, please add Ambient lighting

### ISSUE THREAD

**Issue by INeatFreak** [f3d-app/f3d#816]
**Is your feature request related to a problem? Please describe.**
The models are too dark on viewport when compared to the other 3d viewing programs.
Here's the comparison image with the window's default 3D Viewer: https://imgur.com/a/pzuUEmb

**Describe the solution you'd like**
Add ambient light (if already doesn't exist) and an option to increase the ambient light intensity

**Comment by Meakk** [comment]
You can add a hdri to nicely illuminate the model. Works on PBR materials only though.

**Comment by Meakk** [comment]
EXR is not supported yet. You can use your HDR file by using the option `--hdri=/path/to/file.hdr` or by adding the option directly in your JSON config file.

**Comment by mwestphal** [comment]
> and an option to increase the ambient light intensity 

There is already an option to increase light intensity though. `--light-intensity`

**Comment by mwestphal** [comment]
more info about all the options here: https://f3d.app/doc/user/OPTIONS.html

**Comment by mwestphal** [comment]
@Meakk : I think we need to adress this one soon: #34

**Comment by Meakk** [comment]
Agree

**Comment by INeatFreak** [comment]
None of the solutions provided worked. I've run it with the command that passes hdri and it did show up in the viewport but the model is still dark! I think there's an error in the lighting calculations.

Screenshot comparisons: https://imgur.com/a/pw3fUB7

**Comment by Meakk** [comment]
Yes, FBX files are not using PBR so the hdri will have no effect. Regarding the light intensity option, I think it should work.

**Comment by INeatFreak** [comment]
Unfortunately I had to uninstall this tool as It didn't met my requirements. I've wanted this mainly for thumbnails in explorer and loading the models really fast but the lighting is suboptimal for my needs so I've switched back to using default 3D Viewer but with another extension for windows called Space Thumbnails that provides the thumbnails I needed.

For anyone having the same problems mainly need the thumbnails can get it from [here](https://github.com/EYHN/space-thumbnails)

**Comment by mwestphal** [comment]
Thanks for sharing this great tools I had never heard off before !
