### ISSUE TITLE
Add soname to library

### ISSUE THREAD

**Issue by bkmgit** [f3d-app/f3d#821]
**Is your feature request related to a problem? Please describe.**
Sonames help avoid problems when linking when new interfaces are added.

**Describe the solution you'd like**
Add a soname to the shared library

**Describe alternatives you've considered**
Not considered alternatives

**Additional context**
Related to https://github.com/f3d-app/f3d/issues/801

**Contribution**
Not sure yet.

**Comment by mwestphal** [comment]
Noted, should be easy to do with CMake I hope.

**Comment by mwestphal** [comment]
fixed by #822
