### ISSUE TITLE
Upgrade cxxopts

### ISSUE THREAD

**Issue by jpouderoux** [f3d-app/f3d#83]
We are currently using cxxopts 2.2.0. We should upgrade to 3.0.0.

 - According the doc, there are some breaking changes in v3.
 - Some local changes might be reapplied. https://github.com/f3d-app/f3d/commits/master/src/cxxopts.hpp
 - Should we move this header library file to a submodule in a thirdparty directory (we might have other thirdparty libraries soon)?

**Comment by mwestphal** [comment]
could be done after 1.2, but i'm not sure that is actually needed.

**Comment by Meakk** [comment]
> The parser no longer modifies its arguments, so you can pass a const argc and argv and expect them not to be changed.

Just for that it should be done. Currently, we have a dirty workaround to support that so if it improves the code quality.

**Comment by mwestphal** [comment]
Good point, after 1.2 then
