### ISSUE TITLE
Support USE_EXTERNAL for third parties

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#830]
F3D relies on two third parties that are shipped directly in the code because they are header only libs.
It would be nice to support to use external lib at compilation time.

Please note some of these may be challenging to do right because of non retro-compatible changes between version of these libs.

- json
- cxxopts

FYI @topazus @bkmgit

**Comment by topazus** [comment]
It seems that there are some places need to be modified using with system libraries of nlohmann_json and cxxopts.
first, the #include directive of several files. `#include <json.hpp>` replaced with `#include <nlohmann/json.hpp>`
second, the catch exception of cxxopts library.
https://github.com/f3d-app/f3d/blob/877ccd6cc87186c438791918400f277978479fdb/application/F3DOptionsParser.cxx#L406-L410
maybe the following change?
```
-  catch (const cxxopts::OptionException& ex)
+  catch (const cxxopts::exceptions::exception& ex)
```
https://github.com/jarro2783/cxxopts/blob/master/include/cxxopts.hpp#L399

**Comment by mwestphal** [comment]
indeed, this is the change I catched when I tried to use the one from my system. Feel free to give it a go @topazus
