### ISSUE TITLE
Updating F3D on Windows fails

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#897]
**Describe the bug**
If the shell extension is running, F3D installer cannot override it.

<img width="369" alt="image" src="https://github.com/f3d-app/f3d/assets/6069752/d4b9becb-82dd-451d-a3ce-1c4a8d1e4fe5">

**Comment by mwestphal** [comment]
Uninstalling is needed, I don't think that's fixable with nsis

**Comment by DeveloperPaul123** [comment]
I don't think this is possible without a custom NSIS script

**Comment by Meakk** [comment]
After some time (I think when the thumbnails have been generated), clicking on "retry" worked. So I guess we need to add that in the troubleshooting section and close this issue?

**Comment by mwestphal** [comment]
Ha that make sense
