### ISSUE TITLE
Create a fonctionnal f3d-superbuild

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#9]
Release packages do not contain OSPRay, this requires creating some sort of a superbuild.

- [x] Create https://github.com/f3d-app/f3d-superbuild
- [x] Create a first version that builds VTK + F3D https://github.com/f3d-app/f3d-superbuild/pull/1
- [x] Add optional modules https://github.com/f3d-app/f3d-superbuild/pull/1
- [x] Add a simple CI https://github.com/f3d-app/f3d-superbuild/pull/2
- [x] Use window-latest: https://github.com/f3d-app/f3d-superbuild/pull/4
- [x] Add packaging https://github.com/f3d-app/f3d-superbuild/pull/6
- [x] Add packaging macos: https://github.com/f3d-app/f3d-superbuild/pull/9
- [x] Adding testing: https://github.com/f3d-app/f3d-superbuild/pull/8
- [x] Add source selection for VTK: https://github.com/f3d-app/f3d-superbuild/pull/7
- [x] Add source selection for F3D: https://github.com/f3d-app/f3d-superbuild/pull/7
- [x] Add cross platform CI that generate downloadable binary release out of it: https://github.com/f3d-app/f3d-superbuild/pull/6
- [x] Check every project for option we may not need : https://github.com/f3d-app/f3d-superbuild/pull/12
- [x] Avoid using LFS wherever possible: issue opened
- [x] Include fixes from pvsb: https://github.com/f3d-app/f3d-superbuild/pull/15
- [x] Last fixes: Better packaging, remove useless projects: https://github.com/f3d-app/f3d-superbuild/pull/17
- [x] Enable tbb in VTK: https://github.com/f3d-app/f3d-superbuild/pull/22
- [x] Add a release workflow: https://github.com/f3d-app/f3d-superbuild/pull/16
- [x] Tag 1.3.1 !
- [x] Make fsb work with f3d master: https://github.com/f3d-app/f3d-superbuild/pull/25
- [x] Add a nightly: https://github.com/f3d-app/f3d-superbuild/pull/27
- [x] Use scache
- [x] Publish release with an option
- [x] Rework CI by using matrix config if possible
- [x] Add extensive doc on sb
- [x] Clean fsb repo
- [x] Focus F3D CI on testing instead of binary release
- [x] Consider adding caching
- [x] Move docker logic to another repo: https://github.com/f3d-app/f3d-ci-docker/pull/2
- [x] Improve common sb chrpath : issue opened on common sb: https://gitlab.kitware.com/paraview/paraview-superbuild/-/issues/236
- [x] #588

**Comment by mwestphal** [comment]
https://gitlab.kitware.com/f3d/f3d/-/issues/112

**Comment by mwestphal** [comment]
@Meakk : looping back on this, I see a simple fix.

We can just create our own superbuild based on common-superbuild and adding vtk, ospray, OpenCascade, assimp.

I gave it a quick go based on paraview-superbuild and I have f3d + vtk working out of the box.

**Comment by mwestphal** [comment]
So I took a quick look at vcpkg.

In terms of fonctionnlity, it should be usage as well, and it contains vtk 9.0.1, assimp 5.0.1, opencascade 7.6.0 and does not contains ospray. 
So some works will be needed to add ospray and update at least vtk package somehow.

**Comment by mwestphal** [comment]
I took a quick loock at conan:

it contains assimp 5.1.0, opencascade 7.5.0, no ospray, no vtk. clearly not the best contender here.

**Comment by mwestphal** [comment]
@Meakk : I forgot that I actually already checked all that. Do you have a an advice here ?

**Comment by Meakk** [comment]
We definitely need a SB

**Comment by mwestphal** [comment]
First step done: https://github.com/f3d-app/f3d-superbuild/pull/1

**Comment by mwestphal** [comment]
https://github.com/f3d-app/f3d-superbuild/pull/2
