### ISSUE TITLE
Zoom to Mouse Position 

### ISSUE THREAD

**Issue by Da3n0n** [f3d-app/f3d#901]
basically exactly what the title is zoom to the mouse position in viewport 

would be nice to have the option or preferably by default , lots of applications both 3D and 2D use  or have this method available Blender, Sketchup , Photoshop , Resolve etc 

this would would be a  nice QOL  Feature but really not neccessary .

**Comment by mwestphal** [comment]
Godd idea!

**Comment by Da3n0n** [comment]
Sweet , glad you like this idea aswell : D

**Comment by Meakk** [comment]
We can already pick the focal point by pressing the mouse wheel. I think it's doing more or less what you are describing?

**Comment by RubendeBruin** [comment]
https://github.com/RubendeBruin/DAVE/blob/34fcca27fc9c4c87b03869d8f528b448738520e3/src/DAVE/visual_helpers/vtkBlenderLikeInteractionStyle.py#L201C10-L201C10

Will try to include this in the (still open) PR on VTK.

**Comment by mwestphal** [comment]
> We can already pick the focal point by pressing the mouse wheel. I think it's doing more or less what you are describing?

It is related but definitewly not the same feature

**Comment by mwestphal** [comment]
> https://github.com/RubendeBruin/DAVE/blob/34fcca27fc9c4c87b03869d8f528b448738520e3/src/DAVE/visual_helpers/vtkBlenderLikeInteractionStyle.py#L201C10-L201C10
> 
> Will try to include this in the (still open) PR on VTK.

@RubendeBruin no need, this feature is already present in VTK, exposing it in F3D should be quite trivial.

**Comment by 0x006E** [comment]
I would like to try to add this feature.

**Comment by 0x006E** [comment]
I have added PR #1199
