### ISSUE TITLE
Flaky tests in CI

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#92]
An issue to track flaky tests in ci:

Ubuntu: master:
- TestSSAO (SEGFAULT)
- TestVolumeNoArray (SEGFAULT)
- TestGridWithDepthPeeling (SEGFAULT)
- TestScalars (SEGFAULT)
- TestNonExistentConfigFile (SEGFAULT)

Ubuntu: 9.1.0:
- TestPLY: Segfault
- TestPLY (SEGFAULT)
- TestGLTFReaderWithAnimation: Segfault
- TestGridWithDepthPeeling (SEGFAULT)
- TestInteractionCheatsheetScalars (SEGFAULT)
- TestUnsupportedInputOutput (SEGFAULT)
 - TestInteractionDirectory (SEGFAULT)

Ubuntu: 9.0.0:
 - TestPointCloudBar (SEGFAULT)
 - TestPointCloudBar (SEGFAULT)
 - TestPLY (SEGFAULT)
 - TestUTF8 (SEGFAULT)

MacOS: Timeouts
- TestSSAO
- TestSSAO (Timeout)
- TestDepthPeeling
- TestDepthPeelingToneMapping (Timeout)
- TestDepthPeeling (Timeout)

**Comment by mwestphal** [comment]
@Meakk lets track flaky issues here

**Comment by mwestphal** [comment]
@Open-Cascade-SAS

**Comment by mwestphal** [comment]
@OCCT

**Comment by mwestphal** [comment]
I've run all these tests through valgrind, on 9.10 we only have this uninitialized issue fixed here:
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8682

I will update vtk version for the master build, this should make these issues disapear in master. If that is the case, we would be able to use rerun-failed for 9.10 or apply a patch.

For 9.0 issue, no idea, nothing came up.

**Comment by mwestphal** [comment]
https://github.com/f3d-app/f3d/pull/121

**Comment by mwestphal** [comment]
still possible segfault with vtk master.

**Comment by Meakk** [comment]
Should be better now with https://github.com/f3d-app/f3d/pull/154  
Closing this issue for now. We can reopen it later if needed.
