### ISSUE TITLE
How to close the log window？

### ISSUE THREAD

**Issue by willsonnma** [f3d-app/f3d#921]
I am a 3D scanner supplier, in my work often look at STL format models without color, but every time I open the STL model will appear in to log window, affecting the aesthetics, can I have the option to turn off the log window without a display?

**Comment by Meakk** [comment]
Please take a look at https://github.com/f3d-app/f3d/issues/229

You have a `--quiet` command line option. You can also add this option to your config file to make it permanent.  
Let me know if it works so I can close this issue.

**Comment by willsonnma** [comment]
I'm sorry for not reading the instructions carefully, now I've solved this problem with the rules. 
Using `[install_dir]\share\f3d\configs(config.json,.d)`, 
I modified the parameters inside and it exactly worked as I wanted, great, thanks to meakk.
The results are as follows：
```
{
  "global":
  {
    "axis": true,
    "tone-mapping": true,
    "grid": true,
    "progress": true,
    "anti-aliasing": true,
    "filename": true,
    "scalars": "",
    "camera-direction": "-1,-0.5,-1",
    "quiet": true
  }
}
```
