### ISSUE TITLE
F3D final alpha blending is incorrect

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#968]
A proper alpha blending must pre-multiply the colors by the alpha value and do the compositing in the linear color space.  
A comment have been added in the render pass code. More investigation is needed.

**Comment by mwestphal** [comment]
Do you have a screenshot to illustrate the bug ? I have no idea how to recognise it.

**Comment by mwestphal** [comment]
Any news on this @Meakk ?

**Comment by Meakk** [comment]
It's not urgent, I don't plan to work on it anytime soon

**Comment by mwestphal** [comment]
@Meakk care to improve the issue description so that `help-wanted` label could be added ?

**Comment by Meakk** [comment]
I need time to clarify that, what about a label `workflow: investigation` or `workflow: research`?

**Comment by mwestphal** [comment]
Indeed, that seems needed, I will finish my current pass on issues and think about a complete workflow.
