### ISSUE TITLE
On archlinux systems, thumbnails cannot be displayed in the file manager

### ISSUE THREAD

**Issue by yueduz** [f3d-app/f3d#969]
**Describe the bug**

![截图 2023-09-02 00-38-37](https://github.com/f3d-app/f3d/assets/1448159/c4daf8d9-07e9-417b-9f1e-07cef085fd0c)

**To Reproduce**
1 open coredumpctl
2 Use the file manager to open the folder with the step file

**Expected behavior**
generate thumbnails correctly

**System Information:**
 - OS: archlinux
 - GPU and GPU driver: intel arc a750

**F3D Information**
Paste the content of `f3d --version`: 2.1.0

**Additional context**
A memory dump occurs while generating thumbnails

**Comment by mwestphal** [comment]
It's working perfectly on my archlinux, with pcmanfm, which file manager or desktop environnement are you using ?

Are you using the package from pacman ?

**Comment by yueduz** [comment]
After I use pcmanfm, thumbnails are displayed normally. I used Nautilus before

**Comment by mwestphal** [comment]
From https://f3d.app/doc/user/LIMITATIONS_AND_TROUBLESHOOTING.html
```
Some file managers (eg: Nautilus) are using sandboxing for thumbnails, which the F3D standard binary release does not support as it needs access to the Xorg server to render anything. In that case, you want to use the headless version of F3D that rely on EGL instead of Xorg, available in the [releases page](https://github.com/f3d-app/f3d/releases). If you use the portable archive, make sure to extract it somewhere the sandboxing system has access to, eg: Nautilus uses bwrap and gives it access to /usr but not to /opt.
```

In short, you need to use the EGL binary release to be able to get thumbnails with nautilus.

**Comment by mwestphal** [comment]
Please note F3D now support headless and non-headless in a single version, you can try the last nightly for that: https://github.com/f3d-app/f3d/releases/tag/nightly
