### ISSUE TITLE
Add an option to control backface culling

### ISSUE THREAD

**Issue by wbhu** [f3d-app/f3d#971]
**Context**
F3D is used to render different kind of geometries, most of them contain oriented faces with a concept of backfaces and frontfaces. F3D currently always show the backface but it would be useful to control that behavior.

**Suggested Solution**
 - Add a CLI and libf3d option to control the behavior
 - Use the option in vtkF3DRenderer to set the backface flag on the actors
 - VTK API to use: https://vtk.org/doc/nightly/html/classvtkProperty.html#a19e98e81aba936017e8b9eeb26658d75

**Comment by mwestphal** [comment]
I think that would be pretty trivial to add, wdyt @Meakk ?

**Comment by Meakk** [comment]
Yes, it's just a flag on the actors

**Comment by Meakk** [comment]
Here's a file I create for testing: [backface.zip](https://github.com/f3d-app/f3d/files/13688064/backface.zip)

And the visualization in ParaView:

1. Front/Back display:

<img width="654" alt="image" src="https://github.com/f3d-app/f3d/assets/6069752/ca02fa59-eac0-4c02-8305-f8de4a3fc05e">

2. With backface culling:

<img width="656" alt="image" src="https://github.com/f3d-app/f3d/assets/6069752/ab019633-5851-4b2d-8ba2-eef5b2357e4e">

3. In f3d:

<img width="904" alt="image" src="https://github.com/f3d-app/f3d/assets/6069752/0070cf4e-fafc-466b-888e-0bf3dcdd958d">

**Comment by snoyer** [comment]
From a related discussion on Discord we've also got an `.obj` file with cubes from @theuser021: [backface-cubes.zip](https://github.com/f3d-app/f3d/files/13691381/backface-cubes.zip)

MeshLab rendering options for reference:

- single (back facing dark) ![meshlab-backface-single](https://github.com/f3d-app/f3d/assets/489715/5d716fd9-d735-432d-8f38-c69a223c3fff)
- double (back facing same color as front facing) ![meshlab-backface-double](https://github.com/f3d-app/f3d/assets/489715/facca900-d725-46d0-98c4-65d54c0eb1a9) 
- cull (back facing not displayed) ![meshlab-backface-cull](https://github.com/f3d-app/f3d/assets/489715/6eb59602-d322-4ae7-9a88-7d4315a3d365)
- fancy (two different colors) 
![meshlab-backface-fancy](https://github.com/f3d-app/f3d/assets/489715/b3b97943-b27f-4c82-86d2-ef551abe5cbb)

**Comment by mwestphal** [comment]
Improved the issue.

**Comment by Raghav-B** [comment]
Is anyone working on this? I would love to be able to help out + its a feature I really want to have!

**Comment by mwestphal** [comment]
Well go for it! Are you on discord already?

https://discord.f3d.app

**Comment by Raghav-B** [comment]
Just joined! Thanks!

**Comment by mwestphal** [comment]
any news on this one @Raghav-B ?

**Comment by Raghav-B** [comment]
@mwestphal 
I'm really sorry, I completely missed your messages on Discord. I know this a really simple feature that can be added in a couple of hours but I really haven't had the bandwidth these past 2 months due to some personal issues. I would have really liked to help out with this but it would be better if you could assign this to someone else if you need this done timely.

**Comment by mwestphal** [comment]
No worries:)

**Comment by KeflerExe** [comment]
Im working on it :)
