### ISSUE TITLE
Certain features are not working on ARM-based CPUs packages (eg: macOS Silicon)

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#976]
**Context**
F3D is shipped on different platform, including macOS ARM64.
However, that package come with limitations, lets try to improve that.

**Improvement to do**
 - [x] Exodus:

In the Exodus plugin, we are using the official VTK reader which uses HDF5 internally.  
We are using cross-compiling from an x86_64 host to generate ARM-based packages like for Apple Silicon architecture.  
However, HDF5 fails to compile when cross-compiling for some reason (or it does not compile on ARM at all?).  
When GitHub releases Apple Silicon runners, let's try to fix that.

 - [x] Raytracing:

Does not work with ARM64 yet

 - [x] CI Testing

While we can cross-compile for AMR64, we have no way to actually test the results, investigate how to fix that

**Comment by Meakk** [comment]
Can we close this one @mwestphal ?

**Comment by mwestphal** [comment]
` -DENABLE_exodus=${{ contains(env.CMAKE_OSX_ARCHITECTURES, 'arm64') && 'OFF' || 'ON' }}`

Exodus is not fixed, lets try to enable it in CI.

**Comment by mwestphal** [comment]
All topics have been fixed.

**Comment by mwestphal** [comment]
Doc should be udpdated
