### ISSUE TITLE
Default camera position change between 1.3.1 and 2.1.0

### ISSUE THREAD

**Issue by mzf-guest** [f3d-app/f3d#984]
**Describe the bug**

I'm updating the Debian package from 1.3.1 to 2.1.0 and the regression tests are failing. The behavior change seems to be the default camera position and/or zoom level. The tests don't use any config file.

Step file using 1.3.1:
![cube_step_ref](https://github.com/f3d-app/f3d/assets/49956482/35896d37-266e-4c1f-b109-4bb4f923793a)

Step file using 2.1.0:
![cube_step](https://github.com/f3d-app/f3d/assets/49956482/95e75d83-4b1b-47c4-86d1-2cc902fa27a1)

VTP file using 1.3.1:
![cube_vtp_ref](https://github.com/f3d-app/f3d/assets/49956482/1ffab83c-fa79-4db1-a004-a282644cc1c8)

VTP file using 2.1.0:
![cube_vtp](https://github.com/f3d-app/f3d/assets/49956482/4ffd4b30-619a-4a7c-92f1-49da06ff3a0a)

DAE file using 1.3.1:
![cube_dae_ref](https://github.com/f3d-app/f3d/assets/49956482/7da20048-e82c-4a80-aaa9-3c0701495489)

DAE file using 2.1.0:
![cube_dae](https://github.com/f3d-app/f3d/assets/49956482/569f6dfa-d248-4586-b288-c0daeae101e1)

**To Reproduce**
with version 1.3.1 and version 2.1.0, just run `xvfb-run f3d -s --resolution=640,480 --output=output.png myfile.step` and compare the generated screenshots.

**Expected behavior**

The exact same screenshots between 1.3.1 and 2.1.0.

**System Information:**
 - OS: Debian SID
 - GPU and GPU driver: probably not relevant as it uses `xvfb` command.

**Additional Information**

It looks like the default camera placement changed between the 1.3.1 and 2.1.0 version. Could you please confirm? In this case, this is not a big deal and I'll likely just update the reference screenshots.

Thanks!

François

**Comment by Meakk** [comment]
I think we are now using the ResetCameraScreenSpace in VTK in order to fill more viewport space. It's most likely the reason.  
@mwestphal please confirm

**Comment by mwestphal** [comment]
Yes, confirmed. This is a voluntary change

**Comment by mzf-guest** [comment]
Thanks for your quick answer. I just wanted to check that it was expected. This is the case, so I'll just update the reference pictures for the tests.
